package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

public abstract class CYCLOTRON_SHAPE_FILE_10 {
    public static final String[][] CYCLOTRON_SHAPE_10_IDENTITY = transpose(new String[][] {
        {
            "                                                                                                                                     ",
            "                                                          AAAAAAAAAAAAAAAAA                                                          ",
            "                                                     AAAAA                 AAAAA                                                     ",
            "                                                 AAAA                           AAAA                                                 ",
            "                                             AAAA                                   AAAA                                             ",
            "                                           AA                                           AA                                           ",
            "                                        AAA                                               AAA                                        ",
            "                                      AA                                                     AA                                      ",
            "                                    AA                                                         AA                                    ",
            "                                  AA                                                             AA                                  ",
            "                                 A                                                                 A                                 ",
            "                               AA                                                                   AA                               ",
            "                              A                                                                       A                              ",
            "                            AA                                                                         AA                            ",
            "                           A                                                                             A                           ",
            "                          A                                                                               A                          ",
            "                        AA                                                                                 AA                        ",
            "                       A                                                                                     A                       ",
            "                      A                                                                                       A                      ",
            "                     A                                                                                         A                     ",
            "                    A                                                                                           A                    ",
            "                   A                                                                                             A                   ",
            "                  A                                                                                               A                  ",
            "                 A                                                                                                 A                 ",
            "                A                                                                                                   A                ",
            "                A                                                                                                   A                ",
            "               A                                                                                                     A               ",
            "              A                                                                                                       A              ",
            "             A                                                                                                         A             ",
            "             A                                                                                                         A             ",
            "            A                                                                                                           A            ",
            "           A                                                                                                             A           ",
            "           A                                                                                                             A           ",
            "          A                                                                                                               A          ",
            "         A                                                                                                                 A         ",
            "         A                                                                                                                 A         ",
            "        A                                                                                                                   A        ",
            "        A                                                                                                                   A        ",
            "       A                                                                                                                     A       ",
            "       A                                                                                                                     A       ",
            "      A                                                                                                                       A      ",
            "      A                                                                                                                       A      ",
            "      A                                                                                                                       A      ",
            "     A                                                                                                                         A     ",
            "     A                                                                                                                         A     ",
            "    A                                                                                                                           A    ",
            "    A                                                                                                                           A    ",
            "    A                                                                                                                           A    ",
            "    A                                                                                                                           A    ",
            "   A                                                                                                                             A   ",
            "   A                                                                                                                             A   ",
            "   A                                                                                                                             A   ",
            "   A                                                                                                                             A   ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "   A                                                                                                                             A   ",
            "   A                                                                                                                             A   ",
            "   A                                                                                                                             A   ",
            "   A                                                                                                                             A   ",
            "    A                                                                                                                           A    ",
            "    A                                                                                                                           A    ",
            "    A                                                                                                                           A    ",
            "    A                                                                                                                           A    ",
            "     A                                                                                                                         A     ",
            "     A                                                                                                                         A     ",
            "      A                                                                                                                       A      ",
            "      A                                                                                                                       A      ",
            "      A                                                                                                                       A      ",
            "       A                                                                                                                     A       ",
            "       A                                                                                                                     A       ",
            "        A                                                                                                                   A        ",
            "        A                                                                                                                   A        ",
            "         A                                                                                                                 A         ",
            "         A                                                                                                                 A         ",
            "          A                                                                                                               A          ",
            "           A                                                                                                             A           ",
            "           A                                                                                                             A           ",
            "            A                                                                                                           A            ",
            "             A                                                                                                         A             ",
            "             A                                                                                                         A             ",
            "              A                                                                                                       A              ",
            "               A                                                                                                     A               ",
            "                A                                                                                                   A                ",
            "                A                                                                                                   A                ",
            "                 A                                                                                                 A                 ",
            "                  A                                                                                               A                  ",
            "                   A                                                                                             A                   ",
            "                    A                                                                                           A                    ",
            "                     A                                                                                         A                     ",
            "                      A                                                                                       A                      ",
            "                       A                                                                                     A                       ",
            "                        AA                                                                                 AA                        ",
            "                          A                                                                               A                          ",
            "                           A                                                                             A                           ",
            "                            AA                                                                         AA                            ",
            "                              A                                                                       A                              ",
            "                               AA                                                                   AA                               ",
            "                                 A                                                                 A                                 ",
            "                                  AA                                                             AA                                  ",
            "                                    AA                                                         AA                                    ",
            "                                      AA                                                     AA                                      ",
            "                                        AAA                                               AAA                                        ",
            "                                           AA                                           AA                                           ",
            "                                             AAAA                                   AAAA                                             ",
            "                                                 AAAA                           AAAA                                                 ",
            "                                                     AAAAA                 AAAAA                                                     ",
            "                                                          AAAAAAAAAAAAAAAAA                                                          ",
            "                                                                                                                                     "
        },
        {
            "                                                          AAAAAAAA~AAAAAAAA                                                          ",
            "                                                     AAAAABBBBBBBBBBBBBBBBBAAAAA                                                     ",
            "                                                 AAAABBBBBAAAAAAAAAAAAAAAAABBBBBAAAA                                                 ",
            "                                             AAAABBBBAAAAAA               AAAAAABBBBAAAA                                             ",
            "                                           AABBBBAAAA                           AAAABBBBAA                                           ",
            "                                        AAABBAAAA                                   AAAABBAAA                                        ",
            "                                      AABBBAAA                                         AAABBBAA                                      ",
            "                                    AABBAAA                                               AAABBAA                                    ",
            "                                  AABBAAA                                                   AAABBAA                                  ",
            "                                AABBAAA                                                       AAABBAA                                ",
            "                               AABAAA                                                           AAABAA                               ",
            "                             AABBAA                                                               AABBAA                             ",
            "                            AABAA                                                                   AABAA                            ",
            "                           ABBAA                                                                     AABBA                           ",
            "                         AABAA                                                                         AABAA                         ",
            "                        AABAA                                                                           AABAA                        ",
            "                       ABBAA                                                                             AABBA                       ",
            "                      ABAA                                                                                 AABA                      ",
            "                     ABAA                                                                                   AABA                     ",
            "                    ABAA                                                                                     AABA                    ",
            "                   ABAA                                                                                       AABA                   ",
            "                  ABAA                                                                                         AABA                  ",
            "                 ABAA                                                                                           AABA                 ",
            "                ABAA                                                                                             AABA                ",
            "               ABAA                                                                                               AABA               ",
            "              AABA                                                                                                 ABAA              ",
            "              ABA                                                                                                   ABA              ",
            "             ABAA                                                                                                   AABA             ",
            "            ABAA                                                                                                     AABA            ",
            "           AABA                                                                                                       ABAA           ",
            "           ABA                                                                                                         ABA           ",
            "          ABAA                                                                                                         AABA          ",
            "         AABA                                                                                                           ABAA         ",
            "         ABA                                                                                                             ABA         ",
            "        ABAA                                                                                                             AABA        ",
            "        ABA                                                                                                               ABA        ",
            "       ABAA                                                                                                               AABA       ",
            "       ABA                                                                                                                 ABA       ",
            "      ABAA                                                                                                                 AABA      ",
            "      ABA                                                                                                                   ABA      ",
            "     ABAA                                                                                                                   AABA     ",
            "     ABA                                                                                                                     ABA     ",
            "     ABA                                                                                                                     ABA     ",
            "    ABA                                                                                                                       ABA    ",
            "    ABA                                                                                                                       ABA    ",
            "   ABAA                                                                                                                       AABA   ",
            "   ABA                                                                                                                         ABA   ",
            "   ABA                                                                                                                         ABA   ",
            "   ABA                                                                                                                         ABA   ",
            "  ABA                                                                                                                           ABA  ",
            "  ABA                                                                                                                           ABA  ",
            "  ABA                                                                                                                           ABA  ",
            "  ABA                                                                                                                           ABA  ",
            " ABA                                                                                                                             ABA ",
            " ABA                                                                                                                             ABA ",
            " ABA                                                                                                                             ABA ",
            " ABA                                                                                                                             ABA ",
            " ABA                                                                                                                             ABA ",
            "ABAA                                                                                                                             AABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABA                                                                                                                               ABA",
            "ABAA                                                                                                                             AABA",
            " ABA                                                                                                                             ABA ",
            " ABA                                                                                                                             ABA ",
            " ABA                                                                                                                             ABA ",
            " ABA                                                                                                                             ABA ",
            " ABA                                                                                                                             ABA ",
            "  ABA                                                                                                                           ABA  ",
            "  ABA                                                                                                                           ABA  ",
            "  ABA                                                                                                                           ABA  ",
            "  ABA                                                                                                                           ABA  ",
            "   ABA                                                                                                                         ABA   ",
            "   ABA                                                                                                                         ABA   ",
            "   ABA                                                                                                                         ABA   ",
            "   ABAA                                                                                                                       AABA   ",
            "    ABA                                                                                                                       ABA    ",
            "    ABA                                                                                                                       ABA    ",
            "     ABA                                                                                                                     ABA     ",
            "     ABA                                                                                                                     ABA     ",
            "     ABAA                                                                                                                   AABA     ",
            "      ABA                                                                                                                   ABA      ",
            "      ABAA                                                                                                                 AABA      ",
            "       ABA                                                                                                                 ABA       ",
            "       ABAA                                                                                                               AABA       ",
            "        ABA                                                                                                               ABA        ",
            "        ABAA                                                                                                             AABA        ",
            "         ABA                                                                                                             ABA         ",
            "         AABA                                                                                                           ABAA         ",
            "          ABAA                                                                                                         AABA          ",
            "           ABA                                                                                                         ABA           ",
            "           AABA                                                                                                       ABAA           ",
            "            ABAA                                                                                                     AABA            ",
            "             ABAA                                                                                                   AABA             ",
            "              ABA                                                                                                   ABA              ",
            "              AABA                                                                                                 ABAA              ",
            "               ABAA                                                                                               AABA               ",
            "                ABAA                                                                                             AABA                ",
            "                 ABAA                                                                                           AABA                 ",
            "                  ABAA                                                                                         AABA                  ",
            "                   ABAA                                                                                       AABA                   ",
            "                    ABAA                                                                                     AABA                    ",
            "                     ABAA                                                                                   AABA                     ",
            "                      ABAA                                                                                 AABA                      ",
            "                       ABBAA                                                                             AABBA                       ",
            "                        AABAA                                                                           AABAA                        ",
            "                         AABAA                                                                         AABAA                         ",
            "                           ABBAA                                                                     AABBA                           ",
            "                            AABAA                                                                   AABAA                            ",
            "                             AABBAA                                                               AABBAA                             ",
            "                               AABAAA                                                           AAABAA                               ",
            "                                AABBAAA                                                       AAABBAA                                ",
            "                                  AABBAAA                                                   AAABBAA                                  ",
            "                                    AABBAAA                                               AAABBAA                                    ",
            "                                      AABBBAAA                                         AAABBBAA                                      ",
            "                                        AAABBAAAA                                   AAAABBAAA                                        ",
            "                                           AABBBBAAAA                           AAAABBBBAA                                           ",
            "                                             AAAABBBBAAAAAA               AAAAAABBBBAAAA                                             ",
            "                                                 AAAABBBBBAAAAAAAAAAAAAAAAABBBBBAAAA                                                 ",
            "                                                     AAAAABBBBBBBBBBBBBBBBBAAAAA                                                     ",
            "                                                          AAAAAAAAAAAAAAAAA                                                          "
        },
        {
            "                                                                                                                                     ",
            "                                                          AAAAAAAAAAAAAAAAA                                                          ",
            "                                                     AAAAA                 AAAAA                                                     ",
            "                                                 AAAA                           AAAA                                                 ",
            "                                             AAAA                                   AAAA                                             ",
            "                                           AA                                           AA                                           ",
            "                                        AAA                                               AAA                                        ",
            "                                      AA                                                     AA                                      ",
            "                                    AA                                                         AA                                    ",
            "                                  AA                                                             AA                                  ",
            "                                 A                                                                 A                                 ",
            "                               AA                                                                   AA                               ",
            "                              A                                                                       A                              ",
            "                            AA                                                                         AA                            ",
            "                           A                                                                             A                           ",
            "                          A                                                                               A                          ",
            "                        AA                                                                                 AA                        ",
            "                       A                                                                                     A                       ",
            "                      A                                                                                       A                      ",
            "                     A                                                                                         A                     ",
            "                    A                                                                                           A                    ",
            "                   A                                                                                             A                   ",
            "                  A                                                                                               A                  ",
            "                 A                                                                                                 A                 ",
            "                A                                                                                                   A                ",
            "                A                                                                                                   A                ",
            "               A                                                                                                     A               ",
            "              A                                                                                                       A              ",
            "             A                                                                                                         A             ",
            "             A                                                                                                         A             ",
            "            A                                                                                                           A            ",
            "           A                                                                                                             A           ",
            "           A                                                                                                             A           ",
            "          A                                                                                                               A          ",
            "         A                                                                                                                 A         ",
            "         A                                                                                                                 A         ",
            "        A                                                                                                                   A        ",
            "        A                                                                                                                   A        ",
            "       A                                                                                                                     A       ",
            "       A                                                                                                                     A       ",
            "      A                                                                                                                       A      ",
            "      A                                                                                                                       A      ",
            "      A                                                                                                                       A      ",
            "     A                                                                                                                         A     ",
            "     A                                                                                                                         A     ",
            "    A                                                                                                                           A    ",
            "    A                                                                                                                           A    ",
            "    A                                                                                                                           A    ",
            "    A                                                                                                                           A    ",
            "   A                                                                                                                             A   ",
            "   A                                                                                                                             A   ",
            "   A                                                                                                                             A   ",
            "   A                                                                                                                             A   ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            " A                                                                                                                                 A ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "  A                                                                                                                               A  ",
            "   A                                                                                                                             A   ",
            "   A                                                                                                                             A   ",
            "   A                                                                                                                             A   ",
            "   A                                                                                                                             A   ",
            "    A                                                                                                                           A    ",
            "    A                                                                                                                           A    ",
            "    A                                                                                                                           A    ",
            "    A                                                                                                                           A    ",
            "     A                                                                                                                         A     ",
            "     A                                                                                                                         A     ",
            "      A                                                                                                                       A      ",
            "      A                                                                                                                       A      ",
            "      A                                                                                                                       A      ",
            "       A                                                                                                                     A       ",
            "       A                                                                                                                     A       ",
            "        A                                                                                                                   A        ",
            "        A                                                                                                                   A        ",
            "         A                                                                                                                 A         ",
            "         A                                                                                                                 A         ",
            "          A                                                                                                               A          ",
            "           A                                                                                                             A           ",
            "           A                                                                                                             A           ",
            "            A                                                                                                           A            ",
            "             A                                                                                                         A             ",
            "             A                                                                                                         A             ",
            "              A                                                                                                       A              ",
            "               A                                                                                                     A               ",
            "                A                                                                                                   A                ",
            "                A                                                                                                   A                ",
            "                 A                                                                                                 A                 ",
            "                  A                                                                                               A                  ",
            "                   A                                                                                             A                   ",
            "                    A                                                                                           A                    ",
            "                     A                                                                                         A                     ",
            "                      A                                                                                       A                      ",
            "                       A                                                                                     A                       ",
            "                        AA                                                                                 AA                        ",
            "                          A                                                                               A                          ",
            "                           A                                                                             A                           ",
            "                            AA                                                                         AA                            ",
            "                              A                                                                       A                              ",
            "                               AA                                                                   AA                               ",
            "                                 A                                                                 A                                 ",
            "                                  AA                                                             AA                                  ",
            "                                    AA                                                         AA                                    ",
            "                                      AA                                                     AA                                      ",
            "                                        AAA                                               AAA                                        ",
            "                                           AA                                           AA                                           ",
            "                                             AAAA                                   AAAA                                             ",
            "                                                 AAAA                           AAAA                                                 ",
            "                                                     AAAAA                 AAAAA                                                     ",
            "                                                          AAAAAAAAAAAAAAAAA                                                          ",
            "                                                                                                                                     "
        }
    });
}
