package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

public abstract class CYCLOTRON_SHAPE_FILE_11 {
    public static final String[][] CYCLOTRON_SHAPE_11_IDENTITY = transpose(new String[][] {
        {
            "                                                                                                                                               ",
            "                                                               AAAAAAAAAAAAAAAAA                                                               ",
            "                                                         AAAAAA                 AAAAAA                                                         ",
            "                                                     AAAA                             AAAA                                                     ",
            "                                                  AAA                                     AAA                                                  ",
            "                                               AAA                                           AAA                                               ",
            "                                            AAA                                                 AAA                                            ",
            "                                          AA                                                       AA                                          ",
            "                                        AA                                                           AA                                        ",
            "                                      AA                                                               AA                                      ",
            "                                    AA                                                                   AA                                    ",
            "                                   A                                                                       A                                   ",
            "                                 AA                                                                         AA                                 ",
            "                                A                                                                             A                                ",
            "                              AA                                                                               AA                              ",
            "                             A                                                                                   A                             ",
            "                            A                                                                                     A                            ",
            "                          AA                                                                                       AA                          ",
            "                         A                                                                                           A                         ",
            "                        A                                                                                             A                        ",
            "                       A                                                                                               A                       ",
            "                      A                                                                                                 A                      ",
            "                     A                                                                                                   A                     ",
            "                    A                                                                                                     A                    ",
            "                   A                                                                                                       A                   ",
            "                  A                                                                                                         A                  ",
            "                 A                                                                                                           A                 ",
            "                 A                                                                                                           A                 ",
            "                A                                                                                                             A                ",
            "               A                                                                                                               A               ",
            "              A                                                                                                                 A              ",
            "              A                                                                                                                 A              ",
            "             A                                                                                                                   A             ",
            "            A                                                                                                                     A            ",
            "            A                                                                                                                     A            ",
            "           A                                                                                                                       A           ",
            "          A                                                                                                                         A          ",
            "          A                                                                                                                         A          ",
            "         A                                                                                                                           A         ",
            "         A                                                                                                                           A         ",
            "        A                                                                                                                             A        ",
            "        A                                                                                                                             A        ",
            "       A                                                                                                                               A       ",
            "       A                                                                                                                               A       ",
            "      A                                                                                                                                 A      ",
            "      A                                                                                                                                 A      ",
            "      A                                                                                                                                 A      ",
            "     A                                                                                                                                   A     ",
            "     A                                                                                                                                   A     ",
            "     A                                                                                                                                   A     ",
            "    A                                                                                                                                     A    ",
            "    A                                                                                                                                     A    ",
            "    A                                                                                                                                     A    ",
            "   A                                                                                                                                       A   ",
            "   A                                                                                                                                       A   ",
            "   A                                                                                                                                       A   ",
            "   A                                                                                                                                       A   ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "   A                                                                                                                                       A   ",
            "   A                                                                                                                                       A   ",
            "   A                                                                                                                                       A   ",
            "   A                                                                                                                                       A   ",
            "    A                                                                                                                                     A    ",
            "    A                                                                                                                                     A    ",
            "    A                                                                                                                                     A    ",
            "     A                                                                                                                                   A     ",
            "     A                                                                                                                                   A     ",
            "     A                                                                                                                                   A     ",
            "      A                                                                                                                                 A      ",
            "      A                                                                                                                                 A      ",
            "      A                                                                                                                                 A      ",
            "       A                                                                                                                               A       ",
            "       A                                                                                                                               A       ",
            "        A                                                                                                                             A        ",
            "        A                                                                                                                             A        ",
            "         A                                                                                                                           A         ",
            "         A                                                                                                                           A         ",
            "          A                                                                                                                         A          ",
            "          A                                                                                                                         A          ",
            "           A                                                                                                                       A           ",
            "            A                                                                                                                     A            ",
            "            A                                                                                                                     A            ",
            "             A                                                                                                                   A             ",
            "              A                                                                                                                 A              ",
            "              A                                                                                                                 A              ",
            "               A                                                                                                               A               ",
            "                A                                                                                                             A                ",
            "                 A                                                                                                           A                 ",
            "                 A                                                                                                           A                 ",
            "                  A                                                                                                         A                  ",
            "                   A                                                                                                       A                   ",
            "                    A                                                                                                     A                    ",
            "                     A                                                                                                   A                     ",
            "                      A                                                                                                 A                      ",
            "                       A                                                                                               A                       ",
            "                        A                                                                                             A                        ",
            "                         A                                                                                           A                         ",
            "                          AA                                                                                       AA                          ",
            "                            A                                                                                     A                            ",
            "                             A                                                                                   A                             ",
            "                              AA                                                                               AA                              ",
            "                                A                                                                             A                                ",
            "                                 AA                                                                         AA                                 ",
            "                                   A                                                                       A                                   ",
            "                                    AA                                                                   AA                                    ",
            "                                      AA                                                               AA                                      ",
            "                                        AA                                                           AA                                        ",
            "                                          AA                                                       AA                                          ",
            "                                            AAA                                                 AAA                                            ",
            "                                               AAA                                           AAA                                               ",
            "                                                  AAA                                     AAA                                                  ",
            "                                                     AAAA                             AAAA                                                     ",
            "                                                         AAAAAA                 AAAAAA                                                         ",
            "                                                               AAAAAAAAAAAAAAAAA                                                               ",
            "                                                                                                                                               "
        },
        {
            "                                                               AAAAAAAA~AAAAAAAA                                                               ",
            "                                                         AAAAAABBBBBBBBBBBBBBBBBAAAAAA                                                         ",
            "                                                     AAAABBBBBBAAAAAAAAAAAAAAAAABBBBBBAAAA                                                     ",
            "                                                 AAAABBBBAAAAAA                 AAAAAABBBBAAAA                                                 ",
            "                                               AAABBBAAAA                             AAAABBBAAA                                               ",
            "                                            AAABBBAAA                                     AAABBBAAA                                            ",
            "                                          AABBBAAA                                           AAABBBAA                                          ",
            "                                        AABBAAA                                                 AAABBAA                                        ",
            "                                      AABBAAA                                                     AAABBAA                                      ",
            "                                    AABBAA                                                           AABBAA                                    ",
            "                                  AABBAA                                                               AABBAA                                  ",
            "                                 AABAAA                                                                 AAABAA                                 ",
            "                               AABBAA                                                                     AABBAA                               ",
            "                              AABAA                                                                         AABAA                              ",
            "                             ABBAA                                                                           AABBA                             ",
            "                           AABAA                                                                               AABAA                           ",
            "                          AABAA                                                                                 AABAA                          ",
            "                         ABBAA                                                                                   AABBA                         ",
            "                        ABAA                                                                                       AABA                        ",
            "                       ABAA                                                                                         AABA                       ",
            "                      ABAA                                                                                           AABA                      ",
            "                     ABAA                                                                                             AABA                     ",
            "                    ABAA                                                                                               AABA                    ",
            "                   ABAA                                                                                                 AABA                   ",
            "                  ABAA                                                                                                   AABA                  ",
            "                 ABAA                                                                                                     AABA                 ",
            "                ABAA                                                                                                       AABA                ",
            "               AABA                                                                                                         ABAA               ",
            "               ABA                                                                                                           ABA               ",
            "              ABAA                                                                                                           AABA              ",
            "             ABAA                                                                                                             AABA             ",
            "            AABA                                                                                                               ABAA            ",
            "            ABA                                                                                                                 ABA            ",
            "           ABAA                                                                                                                 AABA           ",
            "          AABA                                                                                                                   ABAA          ",
            "          ABA                                                                                                                     ABA          ",
            "         ABAA                                                                                                                     AABA         ",
            "         ABA                                                                                                                       ABA         ",
            "        ABAA                                                                                                                       AABA        ",
            "        ABA                                                                                                                         ABA        ",
            "       ABA                                                                                                                           ABA       ",
            "       ABA                                                                                                                           ABA       ",
            "      ABA                                                                                                                             ABA      ",
            "      ABA                                                                                                                             ABA      ",
            "     ABAA                                                                                                                             AABA     ",
            "     ABA                                                                                                                               ABA     ",
            "     ABA                                                                                                                               ABA     ",
            "    ABA                                                                                                                                 ABA    ",
            "    ABA                                                                                                                                 ABA    ",
            "   AABA                                                                                                                                 ABAA   ",
            "   ABA                                                                                                                                   ABA   ",
            "   ABA                                                                                                                                   ABA   ",
            "   ABA                                                                                                                                   ABA   ",
            "  ABA                                                                                                                                     ABA  ",
            "  ABA                                                                                                                                     ABA  ",
            "  ABA                                                                                                                                     ABA  ",
            "  ABA                                                                                                                                     ABA  ",
            " ABA                                                                                                                                       ABA ",
            " ABA                                                                                                                                       ABA ",
            " ABA                                                                                                                                       ABA ",
            " ABA                                                                                                                                       ABA ",
            " ABA                                                                                                                                       ABA ",
            " ABA                                                                                                                                       ABA ",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            "ABA                                                                                                                                         ABA",
            " ABA                                                                                                                                       ABA ",
            " ABA                                                                                                                                       ABA ",
            " ABA                                                                                                                                       ABA ",
            " ABA                                                                                                                                       ABA ",
            " ABA                                                                                                                                       ABA ",
            " ABA                                                                                                                                       ABA ",
            "  ABA                                                                                                                                     ABA  ",
            "  ABA                                                                                                                                     ABA  ",
            "  ABA                                                                                                                                     ABA  ",
            "  ABA                                                                                                                                     ABA  ",
            "   ABA                                                                                                                                   ABA   ",
            "   ABA                                                                                                                                   ABA   ",
            "   ABA                                                                                                                                   ABA   ",
            "   AABA                                                                                                                                 ABAA   ",
            "    ABA                                                                                                                                 ABA    ",
            "    ABA                                                                                                                                 ABA    ",
            "     ABA                                                                                                                               ABA     ",
            "     ABA                                                                                                                               ABA     ",
            "     ABAA                                                                                                                             AABA     ",
            "      ABA                                                                                                                             ABA      ",
            "      ABA                                                                                                                             ABA      ",
            "       ABA                                                                                                                           ABA       ",
            "       ABA                                                                                                                           ABA       ",
            "        ABA                                                                                                                         ABA        ",
            "        ABAA                                                                                                                       AABA        ",
            "         ABA                                                                                                                       ABA         ",
            "         ABAA                                                                                                                     AABA         ",
            "          ABA                                                                                                                     ABA          ",
            "          AABA                                                                                                                   ABAA          ",
            "           ABAA                                                                                                                 AABA           ",
            "            ABA                                                                                                                 ABA            ",
            "            AABA                                                                                                               ABAA            ",
            "             ABAA                                                                                                             AABA             ",
            "              ABAA                                                                                                           AABA              ",
            "               ABA                                                                                                           ABA               ",
            "               AABA                                                                                                         ABAA               ",
            "                ABAA                                                                                                       AABA                ",
            "                 ABAA                                                                                                     AABA                 ",
            "                  ABAA                                                                                                   AABA                  ",
            "                   ABAA                                                                                                 AABA                   ",
            "                    ABAA                                                                                               AABA                    ",
            "                     ABAA                                                                                             AABA                     ",
            "                      ABAA                                                                                           AABA                      ",
            "                       ABAA                                                                                         AABA                       ",
            "                        ABAA                                                                                       AABA                        ",
            "                         ABBAA                                                                                   AABBA                         ",
            "                          AABAA                                                                                 AABAA                          ",
            "                           AABAA                                                                               AABAA                           ",
            "                             ABBAA                                                                           AABBA                             ",
            "                              AABAA                                                                         AABAA                              ",
            "                               AABBAA                                                                     AABBAA                               ",
            "                                 AABAAA                                                                 AAABAA                                 ",
            "                                  AABBAA                                                               AABBAA                                  ",
            "                                    AABBAA                                                           AABBAA                                    ",
            "                                      AABBAAA                                                     AAABBAA                                      ",
            "                                        AABBAAA                                                 AAABBAA                                        ",
            "                                          AABBBAAA                                           AAABBBAA                                          ",
            "                                            AAABBBAAA                                     AAABBBAAA                                            ",
            "                                               AAABBBAAAA                             AAAABBBAAA                                               ",
            "                                                 AAAABBBBAAAAAA                 AAAAAABBBBAAAA                                                 ",
            "                                                     AAAABBBBBBAAAAAAAAAAAAAAAAABBBBBBAAAA                                                     ",
            "                                                         AAAAAABBBBBBBBBBBBBBBBBAAAAAA                                                         ",
            "                                                               AAAAAAAAAAAAAAAAA                                                               "
        },
        {
            "                                                                                                                                               ",
            "                                                               AAAAAAAAAAAAAAAAA                                                               ",
            "                                                         AAAAAA                 AAAAAA                                                         ",
            "                                                     AAAA                             AAAA                                                     ",
            "                                                  AAA                                     AAA                                                  ",
            "                                               AAA                                           AAA                                               ",
            "                                            AAA                                                 AAA                                            ",
            "                                          AA                                                       AA                                          ",
            "                                        AA                                                           AA                                        ",
            "                                      AA                                                               AA                                      ",
            "                                    AA                                                                   AA                                    ",
            "                                   A                                                                       A                                   ",
            "                                 AA                                                                         AA                                 ",
            "                                A                                                                             A                                ",
            "                              AA                                                                               AA                              ",
            "                             A                                                                                   A                             ",
            "                            A                                                                                     A                            ",
            "                          AA                                                                                       AA                          ",
            "                         A                                                                                           A                         ",
            "                        A                                                                                             A                        ",
            "                       A                                                                                               A                       ",
            "                      A                                                                                                 A                      ",
            "                     A                                                                                                   A                     ",
            "                    A                                                                                                     A                    ",
            "                   A                                                                                                       A                   ",
            "                  A                                                                                                         A                  ",
            "                 A                                                                                                           A                 ",
            "                 A                                                                                                           A                 ",
            "                A                                                                                                             A                ",
            "               A                                                                                                               A               ",
            "              A                                                                                                                 A              ",
            "              A                                                                                                                 A              ",
            "             A                                                                                                                   A             ",
            "            A                                                                                                                     A            ",
            "            A                                                                                                                     A            ",
            "           A                                                                                                                       A           ",
            "          A                                                                                                                         A          ",
            "          A                                                                                                                         A          ",
            "         A                                                                                                                           A         ",
            "         A                                                                                                                           A         ",
            "        A                                                                                                                             A        ",
            "        A                                                                                                                             A        ",
            "       A                                                                                                                               A       ",
            "       A                                                                                                                               A       ",
            "      A                                                                                                                                 A      ",
            "      A                                                                                                                                 A      ",
            "      A                                                                                                                                 A      ",
            "     A                                                                                                                                   A     ",
            "     A                                                                                                                                   A     ",
            "     A                                                                                                                                   A     ",
            "    A                                                                                                                                     A    ",
            "    A                                                                                                                                     A    ",
            "    A                                                                                                                                     A    ",
            "   A                                                                                                                                       A   ",
            "   A                                                                                                                                       A   ",
            "   A                                                                                                                                       A   ",
            "   A                                                                                                                                       A   ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            " A                                                                                                                                           A ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "  A                                                                                                                                         A  ",
            "   A                                                                                                                                       A   ",
            "   A                                                                                                                                       A   ",
            "   A                                                                                                                                       A   ",
            "   A                                                                                                                                       A   ",
            "    A                                                                                                                                     A    ",
            "    A                                                                                                                                     A    ",
            "    A                                                                                                                                     A    ",
            "     A                                                                                                                                   A     ",
            "     A                                                                                                                                   A     ",
            "     A                                                                                                                                   A     ",
            "      A                                                                                                                                 A      ",
            "      A                                                                                                                                 A      ",
            "      A                                                                                                                                 A      ",
            "       A                                                                                                                               A       ",
            "       A                                                                                                                               A       ",
            "        A                                                                                                                             A        ",
            "        A                                                                                                                             A        ",
            "         A                                                                                                                           A         ",
            "         A                                                                                                                           A         ",
            "          A                                                                                                                         A          ",
            "          A                                                                                                                         A          ",
            "           A                                                                                                                       A           ",
            "            A                                                                                                                     A            ",
            "            A                                                                                                                     A            ",
            "             A                                                                                                                   A             ",
            "              A                                                                                                                 A              ",
            "              A                                                                                                                 A              ",
            "               A                                                                                                               A               ",
            "                A                                                                                                             A                ",
            "                 A                                                                                                           A                 ",
            "                 A                                                                                                           A                 ",
            "                  A                                                                                                         A                  ",
            "                   A                                                                                                       A                   ",
            "                    A                                                                                                     A                    ",
            "                     A                                                                                                   A                     ",
            "                      A                                                                                                 A                      ",
            "                       A                                                                                               A                       ",
            "                        A                                                                                             A                        ",
            "                         A                                                                                           A                         ",
            "                          AA                                                                                       AA                          ",
            "                            A                                                                                     A                            ",
            "                             A                                                                                   A                             ",
            "                              AA                                                                               AA                              ",
            "                                A                                                                             A                                ",
            "                                 AA                                                                         AA                                 ",
            "                                   A                                                                       A                                   ",
            "                                    AA                                                                   AA                                    ",
            "                                      AA                                                               AA                                      ",
            "                                        AA                                                           AA                                        ",
            "                                          AA                                                       AA                                          ",
            "                                            AAA                                                 AAA                                            ",
            "                                               AAA                                           AAA                                               ",
            "                                                  AAA                                     AAA                                                  ",
            "                                                     AAAA                             AAAA                                                     ",
            "                                                         AAAAAA                 AAAAAA                                                         ",
            "                                                               AAAAAAAAAAAAAAAAA                                                               ",
            "                                                                                                                                               "
        }
    });
}
