package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_8 {
    public static final String[][] CYCLOTRON_SHAPE_8_IDENTITY = transpose(new String[][] {
        {
            "                                                                                                                   ",
            "                                                  BBBBB     BBBBB                                                  ",
            "                                             BBBBBBBBBB     BBBBBBBBBB                                             ",
            "                                         BBBBBBBBBBBBBB     BBBBBBBBBBBBBB                                         ",
            "                                      BBBBBBBBBBBB               BBBBBBBBBBBB                                      ",
            "                                   BBBBBBBBBB                         BBBBBBBBBB                                   ",
            "                                 BBBBBBBB                                 BBBBBBBB                                 ",
            "                               BBBBBBBB                                     BBBBBBBB                               ",
            "                             BBBBBBB                                           BBBBBBB                             ",
            "                            BBBBBB                                               BBBBBB                            ",
            "                          BBBBBB                                                   BBBBBB                          ",
            "                         BBBBB                                                       BBBBB                         ",
            "                       BBBBBB                                                         BBBBBB                       ",
            "                      BBBBB                                                             BBBBB                      ",
            "                     BBBBB                                                               BBBBB                     ",
            "                    BBBBB                                                                 BBBBB                    ",
            "                  BBBBB                                                                     BBBBB                  ",
            "                 BBBBB                                                                       BBBBB                 ",
            "                BBBBB                                                                         BBBBB                ",
            "                BBBB                                                                           BBBB                ",
            "               BBBB                                                                             BBBB               ",
            "              BBBB                                                                               BBBB              ",
            "             BBBB                                                                                 BBBB             ",
            "            BBBB                                                                                   BBBB            ",
            "            BBBB                                                                                   BBBB            ",
            "           BBBB                                                                                     BBBB           ",
            "          BBBB                                                                                       BBBB          ",
            "          BBB                                                                                         BBB          ",
            "         BBBB                                                                                         BBBB         ",
            "        BBBB                                                                                           BBBB        ",
            "        BBB                                                                                             BBB        ",
            "       BBBB                                                                                             BBBB       ",
            "       BBB                                                                                               BBB       ",
            "      BBBB                                                                                               BBBB      ",
            "      BBB                                                                                                 BBB      ",
            "     BBBB                                                                                                 BBBB     ",
            "     BBB                                                                                                   BBB     ",
            "     BBB                                                                                                   BBB     ",
            "    BBBB                                                                                                   BBBB    ",
            "    BBB                                                                                                     BBB    ",
            "    BBB                                                                                                     BBB    ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "    BBB                                                                                                     BBB    ",
            "    BBB                                                                                                     BBB    ",
            "    BBBB                                                                                                   BBBB    ",
            "     BBB                                                                                                   BBB     ",
            "     BBB                                                                                                   BBB     ",
            "     BBBB                                                                                                 BBBB     ",
            "      BBB                                                                                                 BBB      ",
            "      BBBB                                                                                               BBBB      ",
            "       BBB                                                                                               BBB       ",
            "       BBBB                                                                                             BBBB       ",
            "        BBB                                                                                             BBB        ",
            "        BBBB                                                                                           BBBB        ",
            "         BBBB                                                                                         BBBB         ",
            "          BBB                                                                                         BBB          ",
            "          BBBB                                                                                       BBBB          ",
            "           BBBB                                                                                     BBBB           ",
            "            BBBB                                                                                   BBBB            ",
            "            BBBB                                                                                   BBBB            ",
            "             BBBB                                                                                 BBBB             ",
            "              BBBB                                                                               BBBB              ",
            "               BBBB                                                                             BBBB               ",
            "                BBBB                                                                           BBBB                ",
            "                BBBBB                                                                         BBBBB                ",
            "                 BBBBB                                                                       BBBBB                 ",
            "                  BBBBB                                                                     BBBBB                  ",
            "                    BBBBB                                                                 BBBBB                    ",
            "                     BBBBB                                                               BBBBB                     ",
            "                      BBBBB                                                             BBBBB                      ",
            "                       BBBBBB                                                         BBBBBB                       ",
            "                         BBBBB                                                       BBBBB                         ",
            "                          BBBBBB                                                   BBBBBB                          ",
            "                            BBBBBB                                               BBBBBB                            ",
            "                             BBBBBBB                                           BBBBBBB                             ",
            "                               BBBBBBBB                                     BBBBBBBB                               ",
            "                                 BBBBBBBB                                 BBBBBBBB                                 ",
            "                                   BBBBBBBBBB                         BBBBBBBBBB                                   ",
            "                                      BBBBBBBBBBBB               BBBBBBBBBBBB                                      ",
            "                                         BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                         ",
            "                                             BBBBBBBBBBBBBBBBBBBBBBBBB                                             ",
            "                                                  BBBBBBBBBBBBBBB                                                  ",
            "                                                                                                                   "
        },
        {
            "                                                  BBBBB     BBBBB                                                  ",
            "                                             BBBBBWWWWW     WWWWWBBBBB                                             ",
            "                                         BBBBWWWWWWWWWW     WWWWWWWWWWBBBB                                         ",
            "                                      BBBWWWWWWWWWWWWWW     WWWWWWWWWWWWWWBBB                                      ",
            "                                   BBBWWWWWWWWWWWWBBBBB     BBBBBWWWWWWWWWWWWBBB                                   ",
            "                                 BBWWWWWWWWWWBBBBB               BBBBBWWWWWWWWWWBB                                 ",
            "                               BBWWWWWWWWBBBB                         BBBBWWWWWWWWBB                               ",
            "                             BBWWWWWWWWBB                                 BBWWWWWWWWBB                             ",
            "                            BWWWWWWWBBB                                     BBBWWWWWWWB                            ",
            "                          BBWWWWWWBB                                           BBWWWWWWBB                          ",
            "                         BWWWWWWBB                                               BBWWWWWWB                         ",
            "                       BBWWWWWBB                                                   BBWWWWWBB                       ",
            "                      BWWWWWWB                                                       BWWWWWWB                      ",
            "                     BWWWWWBB                                                         BBWWWWWB                     ",
            "                    BWWWWWB                                                             BWWWWWB                    ",
            "                  BBWWWWWB                                                               BWWWWWBB                  ",
            "                 BWWWWWBB                                                                 BBWWWWWB                 ",
            "                BWWWWWB                                                                     BWWWWWB                ",
            "               BWWWWWB                                                                       BWWWWWB               ",
            "               BWWWWB                                                                         BWWWWB               ",
            "              BWWWWB                                                                           BWWWWB              ",
            "             BWWWWB                                                                             BWWWWB             ",
            "            BWWWWB                                                                               BWWWWB            ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "          BWWWWB                                                                                   BWWWWB          ",
            "         BWWWWB                                                                                     BWWWWB         ",
            "         BWWWB                                                                                       BWWWB         ",
            "        BWWWWB                                                                                       BWWWWB        ",
            "       BWWWWB                                                                                         BWWWWB       ",
            "       BWWWB                                                                                           BWWWB       ",
            "      BWWWWB                                                                                           BWWWWB      ",
            "      BWWWB                                                                                             BWWWB      ",
            "     BWWWWB                                                                                             BWWWWB     ",
            "     BWWWB                                                                                               BWWWB     ",
            "    BWWWWB                                                                                               BWWWWB    ",
            "    BWWWB                                                                                                 BWWWB    ",
            "    BWWWB                                                                                                 BWWWB    ",
            "   BWWWWB                                                                                                 BWWWWB   ",
            "   BWWWB                                                                                                   BWWWB   ",
            "   BWWWB                                                                                                   BWWWB   ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "   BWWWB                                                                                                   BWWWB   ",
            "   BWWWB                                                                                                   BWWWB   ",
            "   BWWWWB                                                                                                 BWWWWB   ",
            "    BWWWB                                                                                                 BWWWB    ",
            "    BWWWB                                                                                                 BWWWB    ",
            "    BWWWWB                                                                                               BWWWWB    ",
            "     BWWWB                                                                                               BWWWB     ",
            "     BWWWWB                                                                                             BWWWWB     ",
            "      BWWWB                                                                                             BWWWB      ",
            "      BWWWWB                                                                                           BWWWWB      ",
            "       BWWWB                                                                                           BWWWB       ",
            "       BWWWWB                                                                                         BWWWWB       ",
            "        BWWWWB                                                                                       BWWWWB        ",
            "         BWWWB                                                                                       BWWWB         ",
            "         BWWWWB                                                                                     BWWWWB         ",
            "          BWWWWB                                                                                   BWWWWB          ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "            BWWWWB                                                                               BWWWWB            ",
            "             BWWWWB                                                                             BWWWWB             ",
            "              BWWWWB                                                                           BWWWWB              ",
            "               BWWWWB                                                                         BWWWWB               ",
            "               BWWWWWB                                                                       BWWWWWB               ",
            "                BWWWWWB                                                                     BWWWWWB                ",
            "                 BWWWWWBB                                                                 BBWWWWWB                 ",
            "                  BBWWWWWB                                                               BWWWWWBB                  ",
            "                    BWWWWWB                                                             BWWWWWB                    ",
            "                     BWWWWWBB                                                         BBWWWWWB                     ",
            "                      BWWWWWWB                                                       BWWWWWWB                      ",
            "                       BBWWWWWBB                                                   BBWWWWWBB                       ",
            "                         BWWWWWWBB                                               BBWWWWWWB                         ",
            "                          BBWWWWWWBB                                           BBWWWWWWBB                          ",
            "                            BWWWWWWWBBB                                     BBBWWWWWWWB                            ",
            "                             BBWWWWWWWWBB                                 BBWWWWWWWWBB                             ",
            "                               BBWWWWWWWWBBBB                         BBBBWWWWWWWWBB                               ",
            "                                 BBWWWWWWWWWWBBBBB               BBBBBWWWWWWWWWWBB                                 ",
            "                                   BBBWWWWWWWWWWWWBBBBBBBBBBBBBBBWWWWWWWWWWWWBBB                                   ",
            "                                      BBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                      ",
            "                                         BBBBWWWWWWWWWWWWWWWWWWWWWWWWWBBBB                                         ",
            "                                             BBBBBWWWWWWWWWWWWWWWBBBBB                                             ",
            "                                                  BBBBBBBBBBBBBBB                                                  "
        },
        {
            "                                                  BBBBB     BBBBB                                                  ",
            "                                             BBBBBWWWWW  ~  WWWWWBBBBB                                             ",
            "                                         BBBBWWWWWXXXXXXXXXXXXXXXWWWWWBBBB                                         ",
            "                                      BBBWWWWXXXXXWWWWW     WWWWWXXXXXWWWWBBB                                      ",
            "                                   BBBWWWXXXXWWWWWBBBBB     BBBBBWWWWWXXXXWWWBBB                                   ",
            "                                 BBWWWXXXWWWWBBBBB               BBBBBWWWWXXXWWWBB                                 ",
            "                               BBWWWXXWWWBBBB                         BBBBWWWXXWWWBB                               ",
            "                             BBWWWXXWWWBB                                 BBWWWXXWWWBB                             ",
            "                            BWWWXXWWBBB                                     BBBWWXXWWWB                            ",
            "                          BBWWXXWWBB                                           BBWWXXWWBB                          ",
            "                         BWWXXWWBB                                               BBWWXXWWB                         ",
            "                       BBWWXWWBB                                                   BBWWXWWBB                       ",
            "                      BWWXXWWB                                                       BWWXXWWB                      ",
            "                     BWWXWWBB                                                         BBWWXWWB                     ",
            "                    BWWXWWB                                                             BWWXWWB                    ",
            "                  BBWXXWWB                                                               BWWXXWBB                  ",
            "                 BWWXWWBB                                                                 BBWWXWWB                 ",
            "                BWWXWWB                                                                     BWWXWWB                ",
            "               BWWXWWB                                                                       BWWXWWB               ",
            "               BWXWWB                                                                         BWWXWB               ",
            "              BWXWWB                                                                           BWWXWB              ",
            "             BWXWWB                                                                             BWWXWB             ",
            "            BWWXWB                                                                               BWXWWB            ",
            "           BWWXWB                                                                                 BWXWWB           ",
            "           BWXWWB                                                                                 BWWXWB           ",
            "          BWXWWB                                                                                   BWWXWB          ",
            "         BWWXWB                                                                                     BWXWWB         ",
            "         BWXWB                                                                                       BWXWB         ",
            "        BWXWWB                                                                                       BWWXWB        ",
            "       BWWXWB                                                                                         BWXWWB       ",
            "       BWXWB                                                                                           BWXWB       ",
            "      BWWXWB                                                                                           BWXWWB      ",
            "      BWXWB                                                                                             BWXWB      ",
            "     BWWXWB                                                                                             BWXWWB     ",
            "     BWXWB                                                                                               BWXWB     ",
            "    BWWXWB                                                                                               BWXWWB    ",
            "    BWXWB                                                                                                 BWXWB    ",
            "    BWXWB                                                                                                 BWXWB    ",
            "   BWXWWB                                                                                                 BWWXWB   ",
            "   BWXWB                                                                                                   BWXWB   ",
            "   BWXWB                                                                                                   BWXWB   ",
            "  BWXWB                                                                                                     BWXWB  ",
            "  BWXWB                                                                                                     BWXWB  ",
            "  BWXWB                                                                                                     BWXWB  ",
            "  BWXWB                                                                                                     BWXWB  ",
            " BWXWB                                                                                                       BWXWB ",
            " BWXWB                                                                                                       BWXWB ",
            " BWXWB                                                                                                       BWXWB ",
            " BWXWB                                                                                                       BWXWB ",
            " BWXWB                                                                                                       BWXWB ",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            "BWXWB                                                                                                         BWXWB",
            " BWXWB                                                                                                       BWXWB ",
            " BWXWB                                                                                                       BWXWB ",
            " BWXWB                                                                                                       BWXWB ",
            " BWXWB                                                                                                       BWXWB ",
            " BWXWB                                                                                                       BWXWB ",
            "  BWXWB                                                                                                     BWXWB  ",
            "  BWXWB                                                                                                     BWXWB  ",
            "  BWXWB                                                                                                     BWXWB  ",
            "  BWXWB                                                                                                     BWXWB  ",
            "   BWXWB                                                                                                   BWXWB   ",
            "   BWXWB                                                                                                   BWXWB   ",
            "   BWXWWB                                                                                                 BWWXWB   ",
            "    BWXWB                                                                                                 BWXWB    ",
            "    BWXWB                                                                                                 BWXWB    ",
            "    BWWXWB                                                                                               BWXWWB    ",
            "     BWXWB                                                                                               BWXWB     ",
            "     BWWXWB                                                                                             BWXWWB     ",
            "      BWXWB                                                                                             BWXWB      ",
            "      BWWXWB                                                                                           BWXWWB      ",
            "       BWXWB                                                                                           BWXWB       ",
            "       BWWXWB                                                                                         BWXWWB       ",
            "        BWXWWB                                                                                       BWWXWB        ",
            "         BWXWB                                                                                       BWXWB         ",
            "         BWWXWB                                                                                     BWXWWB         ",
            "          BWXWWB                                                                                   BWWXWB          ",
            "           BWXWWB                                                                                 BWWXWB           ",
            "           BWWXWB                                                                                 BWXWWB           ",
            "            BWWXWB                                                                               BWXWWB            ",
            "             BWXWWB                                                                             BWWXWB             ",
            "              BWXWWB                                                                           BWWXWB              ",
            "               BWXWWB                                                                         BWWXWB               ",
            "               BWWXWWB                                                                       BWWXWWB               ",
            "                BWWXWWB                                                                     BWWXWWB                ",
            "                 BWWXWWBB                                                                 BBWWXWWB                 ",
            "                  BBWXXWWB                                                               BWWXXWBB                  ",
            "                    BWWXWWB                                                             BWWXWWB                    ",
            "                     BWWXWWBB                                                         BBWWXWWB                     ",
            "                      BWWXXWWB                                                       BWWXXWWB                      ",
            "                       BBWWXWWBB                                                   BBWWXWWBB                       ",
            "                         BWWXXWWBB                                               BBWWXXWWB                         ",
            "                          BBWWXXWWBB                                           BBWWXXWWBB                          ",
            "                            BWWWXXWWBBB                                     BBBWWXXWWWB                            ",
            "                             BBWWWXXWWWBB                                 BBWWWXXWWWBB                             ",
            "                               BBWWWXXWWWBBBB                         BBBBWWWXXWWWBB                               ",
            "                                 BBWWWXXXWWWWBBBBB               BBBBBWWWWXXXWWWBB                                 ",
            "                                   BBBWWWXXXXWWWWWBBBBBBBBBBBBBBBWWWWWXXXXWWWBBB                                   ",
            "                                      BBBWWWWXXXXXWWWWWWWWWWWWWWWXXXXXWWWWBBB                                      ",
            "                                         BBBBWWWWWXXXXXXXXXXXXXXXWWWWWBBBB                                         ",
            "                                             BBBBBWWWWWWWWWWWWWWWBBBBB                                             ",
            "                                                  BBBBBBBBBBBBBBB                                                  "
        },
        {
            "                                                  BBBBB     BBBBB                                                  ",
            "                                             BBBBBWWWWW     WWWWWBBBBB                                             ",
            "                                         BBBBWWWWWWWWWW     WWWWWWWWWWBBBB                                         ",
            "                                      BBBWWWWWWWWWWWWWW     WWWWWWWWWWWWWWBBB                                      ",
            "                                   BBBWWWWWWWWWWWWBBBBB     BBBBBWWWWWWWWWWWWBBB                                   ",
            "                                 BBWWWWWWWWWWBBBBB               BBBBBWWWWWWWWWWBB                                 ",
            "                               BBWWWWWWWWBBBB                         BBBBWWWWWWWWBB                               ",
            "                             BBWWWWWWWWBB                                 BBWWWWWWWWBB                             ",
            "                            BWWWWWWWBBB                                     BBBWWWWWWWB                            ",
            "                          BBWWWWWWBB                                           BBWWWWWWBB                          ",
            "                         BWWWWWWBB                                               BBWWWWWWB                         ",
            "                       BBWWWWWBB                                                   BBWWWWWBB                       ",
            "                      BWWWWWWB                                                       BWWWWWWB                      ",
            "                     BWWWWWBB                                                         BBWWWWWB                     ",
            "                    BWWWWWB                                                             BWWWWWB                    ",
            "                  BBWWWWWB                                                               BWWWWWBB                  ",
            "                 BWWWWWBB                                                                 BBWWWWWB                 ",
            "                BWWWWWB                                                                     BWWWWWB                ",
            "               BWWWWWB                                                                       BWWWWWB               ",
            "               BWWWWB                                                                         BWWWWB               ",
            "              BWWWWB                                                                           BWWWWB              ",
            "             BWWWWB                                                                             BWWWWB             ",
            "            BWWWWB                                                                               BWWWWB            ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "          BWWWWB                                                                                   BWWWWB          ",
            "         BWWWWB                                                                                     BWWWWB         ",
            "         BWWWB                                                                                       BWWWB         ",
            "        BWWWWB                                                                                       BWWWWB        ",
            "       BWWWWB                                                                                         BWWWWB       ",
            "       BWWWB                                                                                           BWWWB       ",
            "      BWWWWB                                                                                           BWWWWB      ",
            "      BWWWB                                                                                             BWWWB      ",
            "     BWWWWB                                                                                             BWWWWB     ",
            "     BWWWB                                                                                               BWWWB     ",
            "    BWWWWB                                                                                               BWWWWB    ",
            "    BWWWB                                                                                                 BWWWB    ",
            "    BWWWB                                                                                                 BWWWB    ",
            "   BWWWWB                                                                                                 BWWWWB   ",
            "   BWWWB                                                                                                   BWWWB   ",
            "   BWWWB                                                                                                   BWWWB   ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "   BWWWB                                                                                                   BWWWB   ",
            "   BWWWB                                                                                                   BWWWB   ",
            "   BWWWWB                                                                                                 BWWWWB   ",
            "    BWWWB                                                                                                 BWWWB    ",
            "    BWWWB                                                                                                 BWWWB    ",
            "    BWWWWB                                                                                               BWWWWB    ",
            "     BWWWB                                                                                               BWWWB     ",
            "     BWWWWB                                                                                             BWWWWB     ",
            "      BWWWB                                                                                             BWWWB      ",
            "      BWWWWB                                                                                           BWWWWB      ",
            "       BWWWB                                                                                           BWWWB       ",
            "       BWWWWB                                                                                         BWWWWB       ",
            "        BWWWWB                                                                                       BWWWWB        ",
            "         BWWWB                                                                                       BWWWB         ",
            "         BWWWWB                                                                                     BWWWWB         ",
            "          BWWWWB                                                                                   BWWWWB          ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "            BWWWWB                                                                               BWWWWB            ",
            "             BWWWWB                                                                             BWWWWB             ",
            "              BWWWWB                                                                           BWWWWB              ",
            "               BWWWWB                                                                         BWWWWB               ",
            "               BWWWWWB                                                                       BWWWWWB               ",
            "                BWWWWWB                                                                     BWWWWWB                ",
            "                 BWWWWWBB                                                                 BBWWWWWB                 ",
            "                  BBWWWWWB                                                               BWWWWWBB                  ",
            "                    BWWWWWB                                                             BWWWWWB                    ",
            "                     BWWWWWBB                                                         BBWWWWWB                     ",
            "                      BWWWWWWB                                                       BWWWWWWB                      ",
            "                       BBWWWWWBB                                                   BBWWWWWBB                       ",
            "                         BWWWWWWBB                                               BBWWWWWWB                         ",
            "                          BBWWWWWWBB                                           BBWWWWWWBB                          ",
            "                            BWWWWWWWBBB                                     BBBWWWWWWWB                            ",
            "                             BBWWWWWWWWBB                                 BBWWWWWWWWBB                             ",
            "                               BBWWWWWWWWBBBB                         BBBBWWWWWWWWBB                               ",
            "                                 BBWWWWWWWWWWBBBBB               BBBBBWWWWWWWWWWBB                                 ",
            "                                   BBBWWWWWWWWWWWWBBBBBBBBBBBBBBBWWWWWWWWWWWWBBB                                   ",
            "                                      BBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                      ",
            "                                         BBBBWWWWWWWWWWWWWWWWWWWWWWWWWBBBB                                         ",
            "                                             BBBBBWWWWWWWWWWWWWWWBBBBB                                             ",
            "                                                  BBBBBBBBBBBBBBB                                                  "
        },
        {
            "                                                                                                                   ",
            "                                                  BBBBB     BBBBB                                                  ",
            "                                             BBBBBBBBBB     BBBBBBBBBB                                             ",
            "                                         BBBBBBBBBBBBBB     BBBBBBBBBBBBBB                                         ",
            "                                      BBBBBBBBBBBB               BBBBBBBBBBBB                                      ",
            "                                   BBBBBBBBBB                         BBBBBBBBBB                                   ",
            "                                 BBBBBBBB                                 BBBBBBBB                                 ",
            "                               BBBBBBBB                                     BBBBBBBB                               ",
            "                             BBBBBBB                                           BBBBBBB                             ",
            "                            BBBBBB                                               BBBBBB                            ",
            "                          BBBBBB                                                   BBBBBB                          ",
            "                         BBBBB                                                       BBBBB                         ",
            "                       BBBBBB                                                         BBBBBB                       ",
            "                      BBBBB                                                             BBBBB                      ",
            "                     BBBBB                                                               BBBBB                     ",
            "                    BBBBB                                                                 BBBBB                    ",
            "                  BBBBB                                                                     BBBBB                  ",
            "                 BBBBB                                                                       BBBBB                 ",
            "                BBBBB                                                                         BBBBB                ",
            "                BBBB                                                                           BBBB                ",
            "               BBBB                                                                             BBBB               ",
            "              BBBB                                                                               BBBB              ",
            "             BBBB                                                                                 BBBB             ",
            "            BBBB                                                                                   BBBB            ",
            "            BBBB                                                                                   BBBB            ",
            "           BBBB                                                                                     BBBB           ",
            "          BBBB                                                                                       BBBB          ",
            "          BBB                                                                                         BBB          ",
            "         BBBB                                                                                         BBBB         ",
            "        BBBB                                                                                           BBBB        ",
            "        BBB                                                                                             BBB        ",
            "       BBBB                                                                                             BBBB       ",
            "       BBB                                                                                               BBB       ",
            "      BBBB                                                                                               BBBB      ",
            "      BBB                                                                                                 BBB      ",
            "     BBBB                                                                                                 BBBB     ",
            "     BBB                                                                                                   BBB     ",
            "     BBB                                                                                                   BBB     ",
            "    BBBB                                                                                                   BBBB    ",
            "    BBB                                                                                                     BBB    ",
            "    BBB                                                                                                     BBB    ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "    BBB                                                                                                     BBB    ",
            "    BBB                                                                                                     BBB    ",
            "    BBBB                                                                                                   BBBB    ",
            "     BBB                                                                                                   BBB     ",
            "     BBB                                                                                                   BBB     ",
            "     BBBB                                                                                                 BBBB     ",
            "      BBB                                                                                                 BBB      ",
            "      BBBB                                                                                               BBBB      ",
            "       BBB                                                                                               BBB       ",
            "       BBBB                                                                                             BBBB       ",
            "        BBB                                                                                             BBB        ",
            "        BBBB                                                                                           BBBB        ",
            "         BBBB                                                                                         BBBB         ",
            "          BBB                                                                                         BBB          ",
            "          BBBB                                                                                       BBBB          ",
            "           BBBB                                                                                     BBBB           ",
            "            BBBB                                                                                   BBBB            ",
            "            BBBB                                                                                   BBBB            ",
            "             BBBB                                                                                 BBBB             ",
            "              BBBB                                                                               BBBB              ",
            "               BBBB                                                                             BBBB               ",
            "                BBBB                                                                           BBBB                ",
            "                BBBBB                                                                         BBBBB                ",
            "                 BBBBB                                                                       BBBBB                 ",
            "                  BBBBB                                                                     BBBBB                  ",
            "                    BBBBB                                                                 BBBBB                    ",
            "                     BBBBB                                                               BBBBB                     ",
            "                      BBBBB                                                             BBBBB                      ",
            "                       BBBBBB                                                         BBBBBB                       ",
            "                         BBBBB                                                       BBBBB                         ",
            "                          BBBBBB                                                   BBBBBB                          ",
            "                            BBBBBB                                               BBBBBB                            ",
            "                             BBBBBBB                                           BBBBBBB                             ",
            "                               BBBBBBBB                                     BBBBBBBB                               ",
            "                                 BBBBBBBB                                 BBBBBBBB                                 ",
            "                                   BBBBBBBBBB                         BBBBBBBBBB                                   ",
            "                                      BBBBBBBBBBBB               BBBBBBBBBBBB                                      ",
            "                                         BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                         ",
            "                                             BBBBBBBBBBBBBBBBBBBBBBBBB                                             ",
            "                                                  BBBBBBBBBBBBBBB                                                  ",
            "                                                                                                                   "
        }
    });
}
