package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_3 {
    public static final String[][] CYCLOTRON_SHAPE_3_IDENTITY = transpose(new String[][] {
        {
            "                                                                 ",
            "                           BBB     BBB                           ",
            "                       BBBBBBB     BBBBBBB                       ",
            "                    BBBBBBBBBB     BBBBBBBBBB                    ",
            "                  BBBBBBBBB           BBBBBBBBB                  ",
            "                BBBBBBB                   BBBBBBB                ",
            "               BBBBBB                       BBBBBB               ",
            "             BBBBBB                           BBBBBB             ",
            "            BBBBB                               BBBBB            ",
            "           BBBBB                                 BBBBB           ",
            "          BBBBB                                   BBBBB          ",
            "         BBBB                                       BBBB         ",
            "        BBBB                                         BBBB        ",
            "       BBBB                                           BBBB       ",
            "       BBBB                                           BBBB       ",
            "      BBBB                                             BBBB      ",
            "     BBBB                                               BBBB     ",
            "     BBB                                                 BBB     ",
            "    BBBB                                                 BBBB    ",
            "    BBB                                                   BBB    ",
            "   BBBB                                                   BBBB   ",
            "   BBB                                                     BBB   ",
            "   BBB                                                     BBB   ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "   BBB                                                     BBB   ",
            "   BBB                                                     BBB   ",
            "   BBBB                                                   BBBB   ",
            "    BBB                                                   BBB    ",
            "    BBBB                                                 BBBB    ",
            "     BBB                                                 BBB     ",
            "     BBBB                                               BBBB     ",
            "      BBBB                                             BBBB      ",
            "       BBBB                                           BBBB       ",
            "       BBBB                                           BBBB       ",
            "        BBBB                                         BBBB        ",
            "         BBBB                                       BBBB         ",
            "          BBBBB                                   BBBBB          ",
            "           BBBBB                                 BBBBB           ",
            "            BBBBB                               BBBBB            ",
            "             BBBBBB                           BBBBBB             ",
            "               BBBBBB                       BBBBBB               ",
            "                BBBBBBB                   BBBBBBB                ",
            "                  BBBBBBBBB           BBBBBBBBB                  ",
            "                    BBBBBBBBBBBBBBBBBBBBBBBBB                    ",
            "                       BBBBBBBBBBBBBBBBBBB                       ",
            "                           BBBBBBBBBBB                           ",
            "                                                                 "
        },
        {
            "                           BBB     BBB                           ",
            "                       BBBBWWW     WWWBBBB                       ",
            "                    BBBWWWWWWW     WWWWWWWBBB                    ",
            "                  BBWWWWWWWWWW     WWWWWWWWWWBB                  ",
            "                BBWWWWWWWWWBBB     BBBWWWWWWWWWBB                ",
            "               BWWWWWWWBBBB           BBBBWWWWWWWB               ",
            "             BBWWWWWWBB                   BBWWWWWWBB             ",
            "            BWWWWWWBB                       BBWWWWWWB            ",
            "           BWWWWWBB                           BBWWWWWB           ",
            "          BWWWWWB                               BWWWWWB          ",
            "         BWWWWWB                                 BWWWWWB         ",
            "        BWWWWBB                                   BBWWWWB        ",
            "       BWWWWB                                       BWWWWB       ",
            "      BWWWWB                                         BWWWWB      ",
            "      BWWWWB                                         BWWWWB      ",
            "     BWWWWB                                           BWWWWB     ",
            "    BWWWWB                                             BWWWWB    ",
            "    BWWWB                                               BWWWB    ",
            "   BWWWWB                                               BWWWWB   ",
            "   BWWWB                                                 BWWWB   ",
            "  BWWWWB                                                 BWWWWB  ",
            "  BWWWB                                                   BWWWB  ",
            "  BWWWB                                                   BWWWB  ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            "  BWWWB                                                   BWWWB  ",
            "  BWWWB                                                   BWWWB  ",
            "  BWWWWB                                                 BWWWWB  ",
            "   BWWWB                                                 BWWWB   ",
            "   BWWWWB                                               BWWWWB   ",
            "    BWWWB                                               BWWWB    ",
            "    BWWWWB                                             BWWWWB    ",
            "     BWWWWB                                           BWWWWB     ",
            "      BWWWWB                                         BWWWWB      ",
            "      BWWWWB                                         BWWWWB      ",
            "       BWWWWB                                       BWWWWB       ",
            "        BWWWWBB                                   BBWWWWB        ",
            "         BWWWWWB                                 BWWWWWB         ",
            "          BWWWWWB                               BWWWWWB          ",
            "           BWWWWWBB                           BBWWWWWB           ",
            "            BWWWWWWBB                       BBWWWWWWB            ",
            "             BBWWWWWWBB                   BBWWWWWWBB             ",
            "               BWWWWWWWBBBB           BBBBWWWWWWWB               ",
            "                BBWWWWWWWWWBBBBBBBBBBBWWWWWWWWWBB                ",
            "                  BBWWWWWWWWWWWWWWWWWWWWWWWWWBB                  ",
            "                    BBBWWWWWWWWWWWWWWWWWWWBBB                    ",
            "                       BBBBWWWWWWWWWWWBBBB                       ",
            "                           BBBBBBBBBBB                           "
        },
        {
            "                           BBB     BBB                           ",
            "                       BBBBWWW  ~  WWWBBBB                       ",
            "                    BBBWWWWXXXXXXXXXXXWWWWBBB                    ",
            "                  BBWWWXXXXWWW     WWWXXXXWWWBB                  ",
            "                BBWWWXXWWWWBBB     BBBWWWWXXWWWBB                ",
            "               BWWXXXWWBBBB           BBBBWWXXXWWB               ",
            "             BBWWXWWWBB                   BBWWWXWWBB             ",
            "            BWWXXWWBB                       BBWWXXWWB            ",
            "           BWWXWWBB                           BBWWXWWB           ",
            "          BWWXWWB                               BWWXWWB          ",
            "         BWWXWWB                                 BWWXWWB         ",
            "        BWWXWBB                                   BBWXWWB        ",
            "       BWWXWB                                       BWXWWB       ",
            "      BWWXWB                                         BWXWWB      ",
            "      BWXWWB                                         BWWXWB      ",
            "     BWXWWB                                           BWWXWB     ",
            "    BWWXWB                                             BWXWWB    ",
            "    BWXWB                                               BWXWB    ",
            "   BWXWWB                                               BWWXWB   ",
            "   BWXWB                                                 BWXWB   ",
            "  BWWXWB                                                 BWXWWB  ",
            "  BWXWB                                                   BWXWB  ",
            "  BWXWB                                                   BWXWB  ",
            " BWXWB                                                     BWXWB ",
            " BWXWB                                                     BWXWB ",
            " BWXWB                                                     BWXWB ",
            " BWXWB                                                     BWXWB ",
            "BWXWB                                                       BWXWB",
            "BWXWB                                                       BWXWB",
            "BWXWB                                                       BWXWB",
            "BWXWB                                                       BWXWB",
            "BWXWB                                                       BWXWB",
            "BWXWB                                                       BWXWB",
            "BWXWB                                                       BWXWB",
            "BWXWB                                                       BWXWB",
            "BWXWB                                                       BWXWB",
            "BWXWB                                                       BWXWB",
            "BWXWB                                                       BWXWB",
            " BWXWB                                                     BWXWB ",
            " BWXWB                                                     BWXWB ",
            " BWXWB                                                     BWXWB ",
            " BWXWB                                                     BWXWB ",
            "  BWXWB                                                   BWXWB  ",
            "  BWXWB                                                   BWXWB  ",
            "  BWWXWB                                                 BWXWWB  ",
            "   BWXWB                                                 BWXWB   ",
            "   BWXWWB                                               BWWXWB   ",
            "    BWXWB                                               BWXWB    ",
            "    BWWXWB                                             BWXWWB    ",
            "     BWXWWB                                           BWWXWB     ",
            "      BWXWWB                                         BWWXWB      ",
            "      BWWXWB                                         BWXWWB      ",
            "       BWWXWB                                       BWXWWB       ",
            "        BWWXWBB                                   BBWXWWB        ",
            "         BWWXWWB                                 BWWXWWB         ",
            "          BWWXWWB                               BWWXWWB          ",
            "           BWWXWWBB                           BBWWXWWB           ",
            "            BWWXXWWBB                       BBWWXXWWB            ",
            "             BBWWXWWWBB                   BBWWWXWWBB             ",
            "               BWWXXXWWBBBB           BBBBWWXXXWWB               ",
            "                BBWWWXXWWWWBBBBBBBBBBBWWWWXXWWWBB                ",
            "                  BBWWWXXXXWWWWWWWWWWWXXXXWWWBB                  ",
            "                    BBBWWWWXXXXXXXXXXXWWWWBBB                    ",
            "                       BBBBWWWWWWWWWWWBBBB                       ",
            "                           BBBBBBBBBBB                           "
        },
        {
            "                           BBB     BBB                           ",
            "                       BBBBWWW     WWWBBBB                       ",
            "                    BBBWWWWWWW     WWWWWWWBBB                    ",
            "                  BBWWWWWWWWWW     WWWWWWWWWWBB                  ",
            "                BBWWWWWWWWWBBB     BBBWWWWWWWWWBB                ",
            "               BWWWWWWWBBBB           BBBBWWWWWWWB               ",
            "             BBWWWWWWBB                   BBWWWWWWBB             ",
            "            BWWWWWWBB                       BBWWWWWWB            ",
            "           BWWWWWBB                           BBWWWWWB           ",
            "          BWWWWWB                               BWWWWWB          ",
            "         BWWWWWB                                 BWWWWWB         ",
            "        BWWWWBB                                   BBWWWWB        ",
            "       BWWWWB                                       BWWWWB       ",
            "      BWWWWB                                         BWWWWB      ",
            "      BWWWWB                                         BWWWWB      ",
            "     BWWWWB                                           BWWWWB     ",
            "    BWWWWB                                             BWWWWB    ",
            "    BWWWB                                               BWWWB    ",
            "   BWWWWB                                               BWWWWB   ",
            "   BWWWB                                                 BWWWB   ",
            "  BWWWWB                                                 BWWWWB  ",
            "  BWWWB                                                   BWWWB  ",
            "  BWWWB                                                   BWWWB  ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            "  BWWWB                                                   BWWWB  ",
            "  BWWWB                                                   BWWWB  ",
            "  BWWWWB                                                 BWWWWB  ",
            "   BWWWB                                                 BWWWB   ",
            "   BWWWWB                                               BWWWWB   ",
            "    BWWWB                                               BWWWB    ",
            "    BWWWWB                                             BWWWWB    ",
            "     BWWWWB                                           BWWWWB     ",
            "      BWWWWB                                         BWWWWB      ",
            "      BWWWWB                                         BWWWWB      ",
            "       BWWWWB                                       BWWWWB       ",
            "        BWWWWBB                                   BBWWWWB        ",
            "         BWWWWWB                                 BWWWWWB         ",
            "          BWWWWWB                               BWWWWWB          ",
            "           BWWWWWBB                           BBWWWWWB           ",
            "            BWWWWWWBB                       BBWWWWWWB            ",
            "             BBWWWWWWBB                   BBWWWWWWBB             ",
            "               BWWWWWWWBBBB           BBBBWWWWWWWB               ",
            "                BBWWWWWWWWWBBBBBBBBBBBWWWWWWWWWBB                ",
            "                  BBWWWWWWWWWWWWWWWWWWWWWWWWWBB                  ",
            "                    BBBWWWWWWWWWWWWWWWWWWWBBB                    ",
            "                       BBBBWWWWWWWWWWWBBBB                       ",
            "                           BBBBBBBBBBB                           "
        },
        {
            "                                                                 ",
            "                           BBB     BBB                           ",
            "                       BBBBBBB     BBBBBBB                       ",
            "                    BBBBBBBBBB     BBBBBBBBBB                    ",
            "                  BBBBBBBBB           BBBBBBBBB                  ",
            "                BBBBBBB                   BBBBBBB                ",
            "               BBBBBB                       BBBBBB               ",
            "             BBBBBB                           BBBBBB             ",
            "            BBBBB                               BBBBB            ",
            "           BBBBB                                 BBBBB           ",
            "          BBBBB                                   BBBBB          ",
            "         BBBB                                       BBBB         ",
            "        BBBB                                         BBBB        ",
            "       BBBB                                           BBBB       ",
            "       BBBB                                           BBBB       ",
            "      BBBB                                             BBBB      ",
            "     BBBB                                               BBBB     ",
            "     BBB                                                 BBB     ",
            "    BBBB                                                 BBBB    ",
            "    BBB                                                   BBB    ",
            "   BBBB                                                   BBBB   ",
            "   BBB                                                     BBB   ",
            "   BBB                                                     BBB   ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "   BBB                                                     BBB   ",
            "   BBB                                                     BBB   ",
            "   BBBB                                                   BBBB   ",
            "    BBB                                                   BBB    ",
            "    BBBB                                                 BBBB    ",
            "     BBB                                                 BBB     ",
            "     BBBB                                               BBBB     ",
            "      BBBB                                             BBBB      ",
            "       BBBB                                           BBBB       ",
            "       BBBB                                           BBBB       ",
            "        BBBB                                         BBBB        ",
            "         BBBB                                       BBBB         ",
            "          BBBBB                                   BBBBB          ",
            "           BBBBB                                 BBBBB           ",
            "            BBBBB                               BBBBB            ",
            "             BBBBBB                           BBBBBB             ",
            "               BBBBBB                       BBBBBB               ",
            "                BBBBBBB                   BBBBBBB                ",
            "                  BBBBBBBBB           BBBBBBBBB                  ",
            "                    BBBBBBBBBBBBBBBBBBBBBBBBB                    ",
            "                       BBBBBBBBBBBBBBBBBBB                       ",
            "                           BBBBBBBBBBB                           ",
            "                                                                 "
        }
    });
}
