package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_7 {
    public static final String[][] CYCLOTRON_SHAPE_7_IDENTITY = transpose(new String[][] {
        {
            "                                                                                                         ",
            "                                             BBBBB     BBBBB                                             ",
            "                                        BBBBBBBBBB     BBBBBBBBBB                                        ",
            "                                     BBBBBBBBBBBBB     BBBBBBBBBBBBB                                     ",
            "                                  BBBBBBBBBBBB             BBBBBBBBBBBB                                  ",
            "                               BBBBBBBBBB                       BBBBBBBBBB                               ",
            "                             BBBBBBBB                               BBBBBBBB                             ",
            "                           BBBBBBBB                                   BBBBBBBB                           ",
            "                          BBBBBB                                         BBBBBB                          ",
            "                        BBBBBB                                             BBBBBB                        ",
            "                       BBBBB                                                 BBBBB                       ",
            "                     BBBBBB                                                   BBBBBB                     ",
            "                    BBBBB                                                       BBBBB                    ",
            "                   BBBBB                                                         BBBBB                   ",
            "                  BBBBB                                                           BBBBB                  ",
            "                BBBBB                                                               BBBBB                ",
            "               BBBBB                                                                 BBBBB               ",
            "               BBBB                                                                   BBBB               ",
            "              BBBB                                                                     BBBB              ",
            "             BBBB                                                                       BBBB             ",
            "            BBBB                                                                         BBBB            ",
            "           BBBB                                                                           BBBB           ",
            "           BBBB                                                                           BBBB           ",
            "          BBBB                                                                             BBBB          ",
            "         BBBB                                                                               BBBB         ",
            "         BBB                                                                                 BBB         ",
            "        BBBB                                                                                 BBBB        ",
            "       BBBB                                                                                   BBBB       ",
            "       BBB                                                                                     BBB       ",
            "      BBBB                                                                                     BBBB      ",
            "      BBB                                                                                       BBB      ",
            "     BBBB                                                                                       BBBB     ",
            "     BBB                                                                                         BBB     ",
            "     BBB                                                                                         BBB     ",
            "    BBBB                                                                                         BBBB    ",
            "    BBB                                                                                           BBB    ",
            "    BBB                                                                                           BBB    ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "  BBBB                                                                                             BBBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            " BBBB                                                                                               BBBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBBB                                                                                               BBBB ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBBB                                                                                             BBBB  ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "    BBB                                                                                           BBB    ",
            "    BBB                                                                                           BBB    ",
            "    BBBB                                                                                         BBBB    ",
            "     BBB                                                                                         BBB     ",
            "     BBB                                                                                         BBB     ",
            "     BBBB                                                                                       BBBB     ",
            "      BBB                                                                                       BBB      ",
            "      BBBB                                                                                     BBBB      ",
            "       BBB                                                                                     BBB       ",
            "       BBBB                                                                                   BBBB       ",
            "        BBBB                                                                                 BBBB        ",
            "         BBB                                                                                 BBB         ",
            "         BBBB                                                                               BBBB         ",
            "          BBBB                                                                             BBBB          ",
            "           BBBB                                                                           BBBB           ",
            "           BBBB                                                                           BBBB           ",
            "            BBBB                                                                         BBBB            ",
            "             BBBB                                                                       BBBB             ",
            "              BBBB                                                                     BBBB              ",
            "               BBBB                                                                   BBBB               ",
            "               BBBBB                                                                 BBBBB               ",
            "                BBBBB                                                               BBBBB                ",
            "                  BBBBB                                                           BBBBB                  ",
            "                   BBBBB                                                         BBBBB                   ",
            "                    BBBBB                                                       BBBBB                    ",
            "                     BBBBBB                                                   BBBBBB                     ",
            "                       BBBBB                                                 BBBBB                       ",
            "                        BBBBBB                                             BBBBBB                        ",
            "                          BBBBBB                                         BBBBBB                          ",
            "                           BBBBBBBB                                   BBBBBBBB                           ",
            "                             BBBBBBBB                               BBBBBBBB                             ",
            "                               BBBBBBBBBB                       BBBBBBBBBB                               ",
            "                                  BBBBBBBBBBBB             BBBBBBBBBBBB                                  ",
            "                                     BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                     ",
            "                                        BBBBBBBBBBBBBBBBBBBBBBBBB                                        ",
            "                                             BBBBBBBBBBBBBBB                                             ",
            "                                                                                                         "
        },
        {
            "                                             BBBBB     BBBBB                                             ",
            "                                        BBBBBWWWWW     WWWWWBBBBB                                        ",
            "                                     BBBWWWWWWWWWW     WWWWWWWWWWBBB                                     ",
            "                                  BBBWWWWWWWWWWWWW     WWWWWWWWWWWWWBBB                                  ",
            "                               BBBWWWWWWWWWWWWBBBB     BBBBWWWWWWWWWWWWBBB                               ",
            "                             BBWWWWWWWWWWBBBBB             BBBBBWWWWWWWWWWBB                             ",
            "                           BBWWWWWWWWBBBB                       BBBBWWWWWWWWBB                           ",
            "                          BWWWWWWWWBB                               BBWWWWWWWWB                          ",
            "                        BBWWWWWWBBB                                   BBBWWWWWWBB                        ",
            "                       BWWWWWWBB                                         BBWWWWWWB                       ",
            "                     BBWWWWWBB                                             BBWWWWWBB                     ",
            "                    BWWWWWWB                                                 BWWWWWWB                    ",
            "                   BWWWWWBB                                                   BBWWWWWB                   ",
            "                  BWWWWWB                                                       BWWWWWB                  ",
            "                BBWWWWWB                                                         BWWWWWBB                ",
            "               BWWWWWBB                                                           BBWWWWWB               ",
            "              BWWWWWB                                                               BWWWWWB              ",
            "              BWWWWB                                                                 BWWWWB              ",
            "             BWWWWB                                                                   BWWWWB             ",
            "            BWWWWB                                                                     BWWWWB            ",
            "           BWWWWB                                                                       BWWWWB           ",
            "          BWWWWB                                                                         BWWWWB          ",
            "          BWWWWB                                                                         BWWWWB          ",
            "         BWWWWB                                                                           BWWWWB         ",
            "        BWWWWB                                                                             BWWWWB        ",
            "        BWWWB                                                                               BWWWB        ",
            "       BWWWWB                                                                               BWWWWB       ",
            "      BWWWWB                                                                                 BWWWWB      ",
            "      BWWWB                                                                                   BWWWB      ",
            "     BWWWWB                                                                                   BWWWWB     ",
            "     BWWWB                                                                                     BWWWB     ",
            "    BWWWWB                                                                                     BWWWWB    ",
            "    BWWWB                                                                                       BWWWB    ",
            "    BWWWB                                                                                       BWWWB    ",
            "   BWWWWB                                                                                       BWWWWB   ",
            "   BWWWB                                                                                         BWWWB   ",
            "   BWWWB                                                                                         BWWWB   ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            " BWWWWB                                                                                           BWWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            "BWWWWB                                                                                             BWWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWWB                                                                                             BWWWWB",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWWB                                                                                           BWWWWB ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            "   BWWWB                                                                                         BWWWB   ",
            "   BWWWB                                                                                         BWWWB   ",
            "   BWWWWB                                                                                       BWWWWB   ",
            "    BWWWB                                                                                       BWWWB    ",
            "    BWWWB                                                                                       BWWWB    ",
            "    BWWWWB                                                                                     BWWWWB    ",
            "     BWWWB                                                                                     BWWWB     ",
            "     BWWWWB                                                                                   BWWWWB     ",
            "      BWWWB                                                                                   BWWWB      ",
            "      BWWWWB                                                                                 BWWWWB      ",
            "       BWWWWB                                                                               BWWWWB       ",
            "        BWWWB                                                                               BWWWB        ",
            "        BWWWWB                                                                             BWWWWB        ",
            "         BWWWWB                                                                           BWWWWB         ",
            "          BWWWWB                                                                         BWWWWB          ",
            "          BWWWWB                                                                         BWWWWB          ",
            "           BWWWWB                                                                       BWWWWB           ",
            "            BWWWWB                                                                     BWWWWB            ",
            "             BWWWWB                                                                   BWWWWB             ",
            "              BWWWWB                                                                 BWWWWB              ",
            "              BWWWWWB                                                               BWWWWWB              ",
            "               BWWWWWBB                                                           BBWWWWWB               ",
            "                BBWWWWWB                                                         BWWWWWBB                ",
            "                  BWWWWWB                                                       BWWWWWB                  ",
            "                   BWWWWWBB                                                   BBWWWWWB                   ",
            "                    BWWWWWWB                                                 BWWWWWWB                    ",
            "                     BBWWWWWBB                                             BBWWWWWBB                     ",
            "                       BWWWWWWBB                                         BBWWWWWWB                       ",
            "                        BBWWWWWWBBB                                   BBBWWWWWWBB                        ",
            "                          BWWWWWWWWBB                               BBWWWWWWWWB                          ",
            "                           BBWWWWWWWWBBBB                       BBBBWWWWWWWWBB                           ",
            "                             BBWWWWWWWWWWBBBBB             BBBBBWWWWWWWWWWBB                             ",
            "                               BBBWWWWWWWWWWWWBBBBBBBBBBBBBWWWWWWWWWWWWBBB                               ",
            "                                  BBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                  ",
            "                                     BBBWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                     ",
            "                                        BBBBBWWWWWWWWWWWWWWWBBBBB                                        ",
            "                                             BBBBBBBBBBBBBBB                                             "
        },
        {
            "                                             BBBBB     BBBBB                                             ",
            "                                        BBBBBWWWWW  ~  WWWWWBBBBB                                        ",
            "                                     BBBWWWWWXXXXXXXXXXXXXXXWWWWWBBB                                     ",
            "                                  BBBWWWXXXXXWWWWW     WWWWWXXXXXWWWBBB                                  ",
            "                               BBBWWWXXXWWWWWWBBBB     BBBBWWWWWWXXXWWWBBB                               ",
            "                             BBWWWXXXWWWWBBBBB             BBBBBWWWWXXXWWWBB                             ",
            "                           BBWWWXXWWWBBBB                       BBBBWWWXXWWWBB                           ",
            "                          BWWWXXWWWBB                               BBWWWXXWWWB                          ",
            "                        BBWWXXWWBBB                                   BBBWWXXWWBB                        ",
            "                       BWWXXWWBB                                         BBWWXXWWB                       ",
            "                     BBWWXWWBB                                             BBWWXWWBB                     ",
            "                    BWWXXWWB                                                 BWWXXWWB                    ",
            "                   BWWXWWBB                                                   BBWWXWWB                   ",
            "                  BWWXWWB                                                       BWWXWWB                  ",
            "                BBWXXWWB                                                         BWWXXWBB                ",
            "               BWWXWWBB                                                           BBWWXWWB               ",
            "              BWWXWWB                                                               BWWXWWB              ",
            "              BWXWWB                                                                 BWWXWB              ",
            "             BWXWWB                                                                   BWWXWB             ",
            "            BWXWWB                                                                     BWWXWB            ",
            "           BWWXWB                                                                       BWXWWB           ",
            "          BWWXWB                                                                         BWXWWB          ",
            "          BWXWWB                                                                         BWWXWB          ",
            "         BWXWWB                                                                           BWWXWB         ",
            "        BWWXWB                                                                             BWXWWB        ",
            "        BWXWB                                                                               BWXWB        ",
            "       BWXWWB                                                                               BWWXWB       ",
            "      BWWXWB                                                                                 BWXWWB      ",
            "      BWXWB                                                                                   BWXWB      ",
            "     BWWXWB                                                                                   BWXWWB     ",
            "     BWXWB                                                                                     BWXWB     ",
            "    BWWXWB                                                                                     BWXWWB    ",
            "    BWXWB                                                                                       BWXWB    ",
            "    BWXWB                                                                                       BWXWB    ",
            "   BWXWWB                                                                                       BWWXWB   ",
            "   BWXWB                                                                                         BWXWB   ",
            "   BWXWB                                                                                         BWXWB   ",
            "  BWXWB                                                                                           BWXWB  ",
            "  BWXWB                                                                                           BWXWB  ",
            "  BWXWB                                                                                           BWXWB  ",
            " BWXWWB                                                                                           BWWXWB ",
            " BWXWB                                                                                             BWXWB ",
            " BWXWB                                                                                             BWXWB ",
            " BWXWB                                                                                             BWXWB ",
            " BWXWB                                                                                             BWXWB ",
            "BWXWWB                                                                                             BWWXWB",
            "BWXWB                                                                                               BWXWB",
            "BWXWB                                                                                               BWXWB",
            "BWXWB                                                                                               BWXWB",
            "BWXWB                                                                                               BWXWB",
            "BWXWB                                                                                               BWXWB",
            "BWXWB                                                                                               BWXWB",
            "BWXWB                                                                                               BWXWB",
            "BWXWB                                                                                               BWXWB",
            "BWXWB                                                                                               BWXWB",
            "BWXWB                                                                                               BWXWB",
            "BWXWB                                                                                               BWXWB",
            "BWXWB                                                                                               BWXWB",
            "BWXWB                                                                                               BWXWB",
            "BWXWWB                                                                                             BWWXWB",
            " BWXWB                                                                                             BWXWB ",
            " BWXWB                                                                                             BWXWB ",
            " BWXWB                                                                                             BWXWB ",
            " BWXWB                                                                                             BWXWB ",
            " BWXWWB                                                                                           BWWXWB ",
            "  BWXWB                                                                                           BWXWB  ",
            "  BWXWB                                                                                           BWXWB  ",
            "  BWXWB                                                                                           BWXWB  ",
            "   BWXWB                                                                                         BWXWB   ",
            "   BWXWB                                                                                         BWXWB   ",
            "   BWXWWB                                                                                       BWWXWB   ",
            "    BWXWB                                                                                       BWXWB    ",
            "    BWXWB                                                                                       BWXWB    ",
            "    BWWXWB                                                                                     BWXWWB    ",
            "     BWXWB                                                                                     BWXWB     ",
            "     BWWXWB                                                                                   BWXWWB     ",
            "      BWXWB                                                                                   BWXWB      ",
            "      BWWXWB                                                                                 BWXWWB      ",
            "       BWXWWB                                                                               BWWXWB       ",
            "        BWXWB                                                                               BWXWB        ",
            "        BWWXWB                                                                             BWXWWB        ",
            "         BWXWWB                                                                           BWWXWB         ",
            "          BWXWWB                                                                         BWWXWB          ",
            "          BWWXWB                                                                         BWXWWB          ",
            "           BWWXWB                                                                       BWXWWB           ",
            "            BWXWWB                                                                     BWWXWB            ",
            "             BWXWWB                                                                   BWWXWB             ",
            "              BWXWWB                                                                 BWWXWB              ",
            "              BWWXWWB                                                               BWWXWWB              ",
            "               BWWXWWBB                                                           BBWWXWWB               ",
            "                BBWXXWWB                                                         BWWXXWBB                ",
            "                  BWWXWWB                                                       BWWXWWB                  ",
            "                   BWWXWWBB                                                   BBWWXWWB                   ",
            "                    BWWXXWWB                                                 BWWXXWWB                    ",
            "                     BBWWXWWBB                                             BBWWXWWBB                     ",
            "                       BWWXXWWBB                                         BBWWXXWWB                       ",
            "                        BBWWXXWWBBB                                   BBBWWXXWWBB                        ",
            "                          BWWWXXWWWBB                               BBWWWXXWWWB                          ",
            "                           BBWWWXXWWWBBBB                       BBBBWWWXXWWWBB                           ",
            "                             BBWWWXXXWWWWBBBBB             BBBBBWWWWXXXWWWBB                             ",
            "                               BBBWWWXXXWWWWWWBBBBBBBBBBBBBWWWWWWXXXWWWBBB                               ",
            "                                  BBBWWWXXXXXWWWWWWWWWWWWWWWXXXXXWWWBBB                                  ",
            "                                     BBBWWWWWXXXXXXXXXXXXXXXWWWWWBBB                                     ",
            "                                        BBBBBWWWWWWWWWWWWWWWBBBBB                                        ",
            "                                             BBBBBBBBBBBBBBB                                             "
        },
        {
            "                                             BBBBB     BBBBB                                             ",
            "                                        BBBBBWWWWW     WWWWWBBBBB                                        ",
            "                                     BBBWWWWWWWWWW     WWWWWWWWWWBBB                                     ",
            "                                  BBBWWWWWWWWWWWWW     WWWWWWWWWWWWWBBB                                  ",
            "                               BBBWWWWWWWWWWWWBBBB     BBBBWWWWWWWWWWWWBBB                               ",
            "                             BBWWWWWWWWWWBBBBB             BBBBBWWWWWWWWWWBB                             ",
            "                           BBWWWWWWWWBBBB                       BBBBWWWWWWWWBB                           ",
            "                          BWWWWWWWWBB                               BBWWWWWWWWB                          ",
            "                        BBWWWWWWBBB                                   BBBWWWWWWBB                        ",
            "                       BWWWWWWBB                                         BBWWWWWWB                       ",
            "                     BBWWWWWBB                                             BBWWWWWBB                     ",
            "                    BWWWWWWB                                                 BWWWWWWB                    ",
            "                   BWWWWWBB                                                   BBWWWWWB                   ",
            "                  BWWWWWB                                                       BWWWWWB                  ",
            "                BBWWWWWB                                                         BWWWWWBB                ",
            "               BWWWWWBB                                                           BBWWWWWB               ",
            "              BWWWWWB                                                               BWWWWWB              ",
            "              BWWWWB                                                                 BWWWWB              ",
            "             BWWWWB                                                                   BWWWWB             ",
            "            BWWWWB                                                                     BWWWWB            ",
            "           BWWWWB                                                                       BWWWWB           ",
            "          BWWWWB                                                                         BWWWWB          ",
            "          BWWWWB                                                                         BWWWWB          ",
            "         BWWWWB                                                                           BWWWWB         ",
            "        BWWWWB                                                                             BWWWWB        ",
            "        BWWWB                                                                               BWWWB        ",
            "       BWWWWB                                                                               BWWWWB       ",
            "      BWWWWB                                                                                 BWWWWB      ",
            "      BWWWB                                                                                   BWWWB      ",
            "     BWWWWB                                                                                   BWWWWB     ",
            "     BWWWB                                                                                     BWWWB     ",
            "    BWWWWB                                                                                     BWWWWB    ",
            "    BWWWB                                                                                       BWWWB    ",
            "    BWWWB                                                                                       BWWWB    ",
            "   BWWWWB                                                                                       BWWWWB   ",
            "   BWWWB                                                                                         BWWWB   ",
            "   BWWWB                                                                                         BWWWB   ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            " BWWWWB                                                                                           BWWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            "BWWWWB                                                                                             BWWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWWB                                                                                             BWWWWB",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWWB                                                                                           BWWWWB ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            "   BWWWB                                                                                         BWWWB   ",
            "   BWWWB                                                                                         BWWWB   ",
            "   BWWWWB                                                                                       BWWWWB   ",
            "    BWWWB                                                                                       BWWWB    ",
            "    BWWWB                                                                                       BWWWB    ",
            "    BWWWWB                                                                                     BWWWWB    ",
            "     BWWWB                                                                                     BWWWB     ",
            "     BWWWWB                                                                                   BWWWWB     ",
            "      BWWWB                                                                                   BWWWB      ",
            "      BWWWWB                                                                                 BWWWWB      ",
            "       BWWWWB                                                                               BWWWWB       ",
            "        BWWWB                                                                               BWWWB        ",
            "        BWWWWB                                                                             BWWWWB        ",
            "         BWWWWB                                                                           BWWWWB         ",
            "          BWWWWB                                                                         BWWWWB          ",
            "          BWWWWB                                                                         BWWWWB          ",
            "           BWWWWB                                                                       BWWWWB           ",
            "            BWWWWB                                                                     BWWWWB            ",
            "             BWWWWB                                                                   BWWWWB             ",
            "              BWWWWB                                                                 BWWWWB              ",
            "              BWWWWWB                                                               BWWWWWB              ",
            "               BWWWWWBB                                                           BBWWWWWB               ",
            "                BBWWWWWB                                                         BWWWWWBB                ",
            "                  BWWWWWB                                                       BWWWWWB                  ",
            "                   BWWWWWBB                                                   BBWWWWWB                   ",
            "                    BWWWWWWB                                                 BWWWWWWB                    ",
            "                     BBWWWWWBB                                             BBWWWWWBB                     ",
            "                       BWWWWWWBB                                         BBWWWWWWB                       ",
            "                        BBWWWWWWBBB                                   BBBWWWWWWBB                        ",
            "                          BWWWWWWWWBB                               BBWWWWWWWWB                          ",
            "                           BBWWWWWWWWBBBB                       BBBBWWWWWWWWBB                           ",
            "                             BBWWWWWWWWWWBBBBB             BBBBBWWWWWWWWWWBB                             ",
            "                               BBBWWWWWWWWWWWWBBBBBBBBBBBBBWWWWWWWWWWWWBBB                               ",
            "                                  BBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                  ",
            "                                     BBBWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                     ",
            "                                        BBBBBWWWWWWWWWWWWWWWBBBBB                                        ",
            "                                             BBBBBBBBBBBBBBB                                             "
        },
        {
            "                                                                                                         ",
            "                                             BBBBB     BBBBB                                             ",
            "                                        BBBBBBBBBB     BBBBBBBBBB                                        ",
            "                                     BBBBBBBBBBBBB     BBBBBBBBBBBBB                                     ",
            "                                  BBBBBBBBBBBB             BBBBBBBBBBBB                                  ",
            "                               BBBBBBBBBB                       BBBBBBBBBB                               ",
            "                             BBBBBBBB                               BBBBBBBB                             ",
            "                           BBBBBBBB                                   BBBBBBBB                           ",
            "                          BBBBBB                                         BBBBBB                          ",
            "                        BBBBBB                                             BBBBBB                        ",
            "                       BBBBB                                                 BBBBB                       ",
            "                     BBBBBB                                                   BBBBBB                     ",
            "                    BBBBB                                                       BBBBB                    ",
            "                   BBBBB                                                         BBBBB                   ",
            "                  BBBBB                                                           BBBBB                  ",
            "                BBBBB                                                               BBBBB                ",
            "               BBBBB                                                                 BBBBB               ",
            "               BBBB                                                                   BBBB               ",
            "              BBBB                                                                     BBBB              ",
            "             BBBB                                                                       BBBB             ",
            "            BBBB                                                                         BBBB            ",
            "           BBBB                                                                           BBBB           ",
            "           BBBB                                                                           BBBB           ",
            "          BBBB                                                                             BBBB          ",
            "         BBBB                                                                               BBBB         ",
            "         BBB                                                                                 BBB         ",
            "        BBBB                                                                                 BBBB        ",
            "       BBBB                                                                                   BBBB       ",
            "       BBB                                                                                     BBB       ",
            "      BBBB                                                                                     BBBB      ",
            "      BBB                                                                                       BBB      ",
            "     BBBB                                                                                       BBBB     ",
            "     BBB                                                                                         BBB     ",
            "     BBB                                                                                         BBB     ",
            "    BBBB                                                                                         BBBB    ",
            "    BBB                                                                                           BBB    ",
            "    BBB                                                                                           BBB    ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "  BBBB                                                                                             BBBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            " BBBB                                                                                               BBBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBBB                                                                                               BBBB ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBBB                                                                                             BBBB  ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "    BBB                                                                                           BBB    ",
            "    BBB                                                                                           BBB    ",
            "    BBBB                                                                                         BBBB    ",
            "     BBB                                                                                         BBB     ",
            "     BBB                                                                                         BBB     ",
            "     BBBB                                                                                       BBBB     ",
            "      BBB                                                                                       BBB      ",
            "      BBBB                                                                                     BBBB      ",
            "       BBB                                                                                     BBB       ",
            "       BBBB                                                                                   BBBB       ",
            "        BBBB                                                                                 BBBB        ",
            "         BBB                                                                                 BBB         ",
            "         BBBB                                                                               BBBB         ",
            "          BBBB                                                                             BBBB          ",
            "           BBBB                                                                           BBBB           ",
            "           BBBB                                                                           BBBB           ",
            "            BBBB                                                                         BBBB            ",
            "             BBBB                                                                       BBBB             ",
            "              BBBB                                                                     BBBB              ",
            "               BBBB                                                                   BBBB               ",
            "               BBBBB                                                                 BBBBB               ",
            "                BBBBB                                                               BBBBB                ",
            "                  BBBBB                                                           BBBBB                  ",
            "                   BBBBB                                                         BBBBB                   ",
            "                    BBBBB                                                       BBBBB                    ",
            "                     BBBBBB                                                   BBBBBB                     ",
            "                       BBBBB                                                 BBBBB                       ",
            "                        BBBBBB                                             BBBBBB                        ",
            "                          BBBBBB                                         BBBBBB                          ",
            "                           BBBBBBBB                                   BBBBBBBB                           ",
            "                             BBBBBBBB                               BBBBBBBB                             ",
            "                               BBBBBBBBBB                       BBBBBBBBBB                               ",
            "                                  BBBBBBBBBBBB             BBBBBBBBBBBB                                  ",
            "                                     BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                     ",
            "                                        BBBBBBBBBBBBBBBBBBBBBBBBB                                        ",
            "                                             BBBBBBBBBBBBBBB                                             ",
            "                                                                                                         "
        }
    });
}
