package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_6 {
    public static final String[][] CYCLOTRON_SHAPE_6_IDENTITY = transpose(new String[][] {
        {
            "                                                                                               ",
            "                                         BBBB     BBBB                                         ",
            "                                    BBBBBBBBB     BBBBBBBBB                                    ",
            "                                BBBBBBBBBBBBB     BBBBBBBBBBBBB                                ",
            "                              BBBBBBBBBBB             BBBBBBBBBBB                              ",
            "                           BBBBBBBBB                       BBBBBBBBB                           ",
            "                         BBBBBBBB                             BBBBBBBB                         ",
            "                        BBBBBBB                                 BBBBBBB                        ",
            "                      BBBBBB                                       BBBBBB                      ",
            "                     BBBBB                                           BBBBB                     ",
            "                   BBBBBB                                             BBBBBB                   ",
            "                  BBBBB                                                 BBBBB                  ",
            "                 BBBBB                                                   BBBBB                 ",
            "                BBBBB                                                     BBBBB                ",
            "               BBBB                                                         BBBB               ",
            "              BBBB                                                           BBBB              ",
            "             BBBB                                                             BBBB             ",
            "            BBBB                                                               BBBB            ",
            "           BBBB                                                                 BBBB           ",
            "          BBBB                                                                   BBBB          ",
            "          BBBB                                                                   BBBB          ",
            "         BBBB                                                                     BBBB         ",
            "        BBBB                                                                       BBBB        ",
            "        BBB                                                                         BBB        ",
            "       BBBB                                                                         BBBB       ",
            "      BBBB                                                                           BBBB      ",
            "      BBB                                                                             BBB      ",
            "     BBBB                                                                             BBBB     ",
            "     BBB                                                                               BBB     ",
            "     BBB                                                                               BBB     ",
            "    BBBB                                                                               BBBB    ",
            "    BBB                                                                                 BBB    ",
            "   BBBB                                                                                 BBBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBBB                                                                                 BBBB   ",
            "    BBB                                                                                 BBB    ",
            "    BBBB                                                                               BBBB    ",
            "     BBB                                                                               BBB     ",
            "     BBB                                                                               BBB     ",
            "     BBBB                                                                             BBBB     ",
            "      BBB                                                                             BBB      ",
            "      BBBB                                                                           BBBB      ",
            "       BBBB                                                                         BBBB       ",
            "        BBB                                                                         BBB        ",
            "        BBBB                                                                       BBBB        ",
            "         BBBB                                                                     BBBB         ",
            "          BBBB                                                                   BBBB          ",
            "          BBBB                                                                   BBBB          ",
            "           BBBB                                                                 BBBB           ",
            "            BBBB                                                               BBBB            ",
            "             BBBB                                                             BBBB             ",
            "              BBBB                                                           BBBB              ",
            "               BBBB                                                         BBBB               ",
            "                BBBBB                                                     BBBBB                ",
            "                 BBBBB                                                   BBBBB                 ",
            "                  BBBBB                                                 BBBBB                  ",
            "                   BBBBBB                                             BBBBBB                   ",
            "                     BBBBB                                           BBBBB                     ",
            "                      BBBBBB                                       BBBBBB                      ",
            "                        BBBBBBB                                 BBBBBBB                        ",
            "                         BBBBBBBB                             BBBBBBBB                         ",
            "                           BBBBBBBBB                       BBBBBBBBB                           ",
            "                              BBBBBBBBBBB             BBBBBBBBBBB                              ",
            "                                BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                ",
            "                                    BBBBBBBBBBBBBBBBBBBBBBB                                    ",
            "                                         BBBBBBBBBBBBB                                         ",
            "                                                                                               "
        },
        {
            "                                         BBBB     BBBB                                         ",
            "                                    BBBBBWWWW     WWWWBBBBB                                    ",
            "                                BBBBWWWWWWWWW     WWWWWWWWWBBBB                                ",
            "                              BBWWWWWWWWWWWWW     WWWWWWWWWWWWWBB                              ",
            "                           BBBWWWWWWWWWWWBBBB     BBBBWWWWWWWWWWWBBB                           ",
            "                         BBWWWWWWWWWBBBBB             BBBBBWWWWWWWWWBB                         ",
            "                        BWWWWWWWWBBB                       BBBWWWWWWWWB                        ",
            "                      BBWWWWWWWBB                             BBWWWWWWWBB                      ",
            "                     BWWWWWWBBB                                 BBBWWWWWWB                     ",
            "                   BBWWWWWBB                                       BBWWWWWBB                   ",
            "                  BWWWWWWB                                           BWWWWWWB                  ",
            "                 BWWWWWBB                                             BBWWWWWB                 ",
            "                BWWWWWB                                                 BWWWWWB                ",
            "               BWWWWWB                                                   BWWWWWB               ",
            "              BWWWWBB                                                     BBWWWWB              ",
            "             BWWWWB                                                         BWWWWB             ",
            "            BWWWWB                                                           BWWWWB            ",
            "           BWWWWB                                                             BWWWWB           ",
            "          BWWWWB                                                               BWWWWB          ",
            "         BWWWWB                                                                 BWWWWB         ",
            "         BWWWWB                                                                 BWWWWB         ",
            "        BWWWWB                                                                   BWWWWB        ",
            "       BWWWWB                                                                     BWWWWB       ",
            "       BWWWB                                                                       BWWWB       ",
            "      BWWWWB                                                                       BWWWWB      ",
            "     BWWWWB                                                                         BWWWWB     ",
            "     BWWWB                                                                           BWWWB     ",
            "    BWWWWB                                                                           BWWWWB    ",
            "    BWWWB                                                                             BWWWB    ",
            "    BWWWB                                                                             BWWWB    ",
            "   BWWWWB                                                                             BWWWWB   ",
            "   BWWWB                                                                               BWWWB   ",
            "  BWWWWB                                                                               BWWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWWB                                                                               BWWWWB  ",
            "   BWWWB                                                                               BWWWB   ",
            "   BWWWWB                                                                             BWWWWB   ",
            "    BWWWB                                                                             BWWWB    ",
            "    BWWWB                                                                             BWWWB    ",
            "    BWWWWB                                                                           BWWWWB    ",
            "     BWWWB                                                                           BWWWB     ",
            "     BWWWWB                                                                         BWWWWB     ",
            "      BWWWWB                                                                       BWWWWB      ",
            "       BWWWB                                                                       BWWWB       ",
            "       BWWWWB                                                                     BWWWWB       ",
            "        BWWWWB                                                                   BWWWWB        ",
            "         BWWWWB                                                                 BWWWWB         ",
            "         BWWWWB                                                                 BWWWWB         ",
            "          BWWWWB                                                               BWWWWB          ",
            "           BWWWWB                                                             BWWWWB           ",
            "            BWWWWB                                                           BWWWWB            ",
            "             BWWWWB                                                         BWWWWB             ",
            "              BWWWWBB                                                     BBWWWWB              ",
            "               BWWWWWB                                                   BWWWWWB               ",
            "                BWWWWWB                                                 BWWWWWB                ",
            "                 BWWWWWBB                                             BBWWWWWB                 ",
            "                  BWWWWWWB                                           BWWWWWWB                  ",
            "                   BBWWWWWBB                                       BBWWWWWBB                   ",
            "                     BWWWWWWBBB                                 BBBWWWWWWB                     ",
            "                      BBWWWWWWWBB                             BBWWWWWWWBB                      ",
            "                        BWWWWWWWWBBB                       BBBWWWWWWWWB                        ",
            "                         BBWWWWWWWWWBBBBB             BBBBBWWWWWWWWWBB                         ",
            "                           BBBWWWWWWWWWWWBBBBBBBBBBBBBWWWWWWWWWWWBBB                           ",
            "                              BBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBB                              ",
            "                                BBBBWWWWWWWWWWWWWWWWWWWWWWWBBBB                                ",
            "                                    BBBBBWWWWWWWWWWWWWBBBBB                                    ",
            "                                         BBBBBBBBBBBBB                                         "
        },
        {
            "                                         BBBB     BBBB                                         ",
            "                                    BBBBBWWWW  ~  WWWWBBBBB                                    ",
            "                                BBBBWWWWWXXXXXXXXXXXXXWWWWWBBBB                                ",
            "                              BBWWWWXXXXXWWWW     WWWWXXXXXWWWWBB                              ",
            "                           BBBWWWXXXWWWWWBBBB     BBBBWWWWWXXXWWWBBB                           ",
            "                         BBWWWXXXWWWBBBBB             BBBBBWWWXXXWWWBB                         ",
            "                        BWWWXXWWWBBB                       BBBWWWXXWWWB                        ",
            "                      BBWWXXWWWBB                             BBWWWXXWWBB                      ",
            "                     BWWXXWWBBB                                 BBBWWXXWWB                     ",
            "                   BBWWXWWBB                                       BBWWXWWBB                   ",
            "                  BWWXXWWB                                           BWWXXWWB                  ",
            "                 BWWXWWBB                                             BBWWXWWB                 ",
            "                BWWXWWB                                                 BWWXWWB                ",
            "               BWXXWWB                                                   BWWXXWB               ",
            "              BWXWWBB                                                     BBWWXWB              ",
            "             BWXWWB                                                         BWWXWB             ",
            "            BWXWWB                                                           BWWXWB            ",
            "           BWXWWB                                                             BWWXWB           ",
            "          BWWXWB                                                               BWXWWB          ",
            "         BWWXWB                                                                 BWXWWB         ",
            "         BWXWWB                                                                 BWWXWB         ",
            "        BWXWWB                                                                   BWWXWB        ",
            "       BWWXWB                                                                     BWXWWB       ",
            "       BWXWB                                                                       BWXWB       ",
            "      BWXWWB                                                                       BWWXWB      ",
            "     BWWXWB                                                                         BWXWWB     ",
            "     BWXWB                                                                           BWXWB     ",
            "    BWWXWB                                                                           BWXWWB    ",
            "    BWXWB                                                                             BWXWB    ",
            "    BWXWB                                                                             BWXWB    ",
            "   BWXWWB                                                                             BWWXWB   ",
            "   BWXWB                                                                               BWXWB   ",
            "  BWWXWB                                                                               BWXWWB  ",
            "  BWXWB                                                                                 BWXWB  ",
            "  BWXWB                                                                                 BWXWB  ",
            "  BWXWB                                                                                 BWXWB  ",
            " BWXWB                                                                                   BWXWB ",
            " BWXWB                                                                                   BWXWB ",
            " BWXWB                                                                                   BWXWB ",
            " BWXWB                                                                                   BWXWB ",
            " BWXWB                                                                                   BWXWB ",
            "BWXWB                                                                                     BWXWB",
            "BWXWB                                                                                     BWXWB",
            "BWXWB                                                                                     BWXWB",
            "BWXWB                                                                                     BWXWB",
            "BWXWB                                                                                     BWXWB",
            "BWXWB                                                                                     BWXWB",
            "BWXWB                                                                                     BWXWB",
            "BWXWB                                                                                     BWXWB",
            "BWXWB                                                                                     BWXWB",
            "BWXWB                                                                                     BWXWB",
            "BWXWB                                                                                     BWXWB",
            "BWXWB                                                                                     BWXWB",
            "BWXWB                                                                                     BWXWB",
            " BWXWB                                                                                   BWXWB ",
            " BWXWB                                                                                   BWXWB ",
            " BWXWB                                                                                   BWXWB ",
            " BWXWB                                                                                   BWXWB ",
            " BWXWB                                                                                   BWXWB ",
            "  BWXWB                                                                                 BWXWB  ",
            "  BWXWB                                                                                 BWXWB  ",
            "  BWXWB                                                                                 BWXWB  ",
            "  BWWXWB                                                                               BWXWWB  ",
            "   BWXWB                                                                               BWXWB   ",
            "   BWXWWB                                                                             BWWXWB   ",
            "    BWXWB                                                                             BWXWB    ",
            "    BWXWB                                                                             BWXWB    ",
            "    BWWXWB                                                                           BWXWWB    ",
            "     BWXWB                                                                           BWXWB     ",
            "     BWWXWB                                                                         BWXWWB     ",
            "      BWXWWB                                                                       BWWXWB      ",
            "       BWXWB                                                                       BWXWB       ",
            "       BWWXWB                                                                     BWXWWB       ",
            "        BWXWWB                                                                   BWWXWB        ",
            "         BWXWWB                                                                 BWWXWB         ",
            "         BWWXWB                                                                 BWXWWB         ",
            "          BWWXWB                                                               BWXWWB          ",
            "           BWXWWB                                                             BWWXWB           ",
            "            BWXWWB                                                           BWWXWB            ",
            "             BWXWWB                                                         BWWXWB             ",
            "              BWXWWBB                                                     BBWWXWB              ",
            "               BWXXWWB                                                   BWWXXWB               ",
            "                BWWXWWB                                                 BWWXWWB                ",
            "                 BWWXWWBB                                             BBWWXWWB                 ",
            "                  BWWXXWWB                                           BWWXXWWB                  ",
            "                   BBWWXWWBB                                       BBWWXWWBB                   ",
            "                     BWWXXWWBBB                                 BBBWWXXWWB                     ",
            "                      BBWWXXWWWBB                             BBWWWXXWWBB                      ",
            "                        BWWWXXWWWBBB                       BBBWWWXXWWWB                        ",
            "                         BBWWWXXXWWWBBBBB             BBBBBWWWXXXWWWBB                         ",
            "                           BBBWWWXXXWWWWWBBBBBBBBBBBBBWWWWWXXXWWWBBB                           ",
            "                              BBWWWWXXXXXWWWWWWWWWWWWWXXXXXWWWWBB                              ",
            "                                BBBBWWWWWXXXXXXXXXXXXXWWWWWBBBB                                ",
            "                                    BBBBBWWWWWWWWWWWWWBBBBB                                    ",
            "                                         BBBBBBBBBBBBB                                         "
        },
        {
            "                                         BBBB     BBBB                                         ",
            "                                    BBBBBWWWW     WWWWBBBBB                                    ",
            "                                BBBBWWWWWWWWW     WWWWWWWWWBBBB                                ",
            "                              BBWWWWWWWWWWWWW     WWWWWWWWWWWWWBB                              ",
            "                           BBBWWWWWWWWWWWBBBB     BBBBWWWWWWWWWWWBBB                           ",
            "                         BBWWWWWWWWWBBBBB             BBBBBWWWWWWWWWBB                         ",
            "                        BWWWWWWWWBBB                       BBBWWWWWWWWB                        ",
            "                      BBWWWWWWWBB                             BBWWWWWWWBB                      ",
            "                     BWWWWWWBBB                                 BBBWWWWWWB                     ",
            "                   BBWWWWWBB                                       BBWWWWWBB                   ",
            "                  BWWWWWWB                                           BWWWWWWB                  ",
            "                 BWWWWWBB                                             BBWWWWWB                 ",
            "                BWWWWWB                                                 BWWWWWB                ",
            "               BWWWWWB                                                   BWWWWWB               ",
            "              BWWWWBB                                                     BBWWWWB              ",
            "             BWWWWB                                                         BWWWWB             ",
            "            BWWWWB                                                           BWWWWB            ",
            "           BWWWWB                                                             BWWWWB           ",
            "          BWWWWB                                                               BWWWWB          ",
            "         BWWWWB                                                                 BWWWWB         ",
            "         BWWWWB                                                                 BWWWWB         ",
            "        BWWWWB                                                                   BWWWWB        ",
            "       BWWWWB                                                                     BWWWWB       ",
            "       BWWWB                                                                       BWWWB       ",
            "      BWWWWB                                                                       BWWWWB      ",
            "     BWWWWB                                                                         BWWWWB     ",
            "     BWWWB                                                                           BWWWB     ",
            "    BWWWWB                                                                           BWWWWB    ",
            "    BWWWB                                                                             BWWWB    ",
            "    BWWWB                                                                             BWWWB    ",
            "   BWWWWB                                                                             BWWWWB   ",
            "   BWWWB                                                                               BWWWB   ",
            "  BWWWWB                                                                               BWWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWWB                                                                               BWWWWB  ",
            "   BWWWB                                                                               BWWWB   ",
            "   BWWWWB                                                                             BWWWWB   ",
            "    BWWWB                                                                             BWWWB    ",
            "    BWWWB                                                                             BWWWB    ",
            "    BWWWWB                                                                           BWWWWB    ",
            "     BWWWB                                                                           BWWWB     ",
            "     BWWWWB                                                                         BWWWWB     ",
            "      BWWWWB                                                                       BWWWWB      ",
            "       BWWWB                                                                       BWWWB       ",
            "       BWWWWB                                                                     BWWWWB       ",
            "        BWWWWB                                                                   BWWWWB        ",
            "         BWWWWB                                                                 BWWWWB         ",
            "         BWWWWB                                                                 BWWWWB         ",
            "          BWWWWB                                                               BWWWWB          ",
            "           BWWWWB                                                             BWWWWB           ",
            "            BWWWWB                                                           BWWWWB            ",
            "             BWWWWB                                                         BWWWWB             ",
            "              BWWWWBB                                                     BBWWWWB              ",
            "               BWWWWWB                                                   BWWWWWB               ",
            "                BWWWWWB                                                 BWWWWWB                ",
            "                 BWWWWWBB                                             BBWWWWWB                 ",
            "                  BWWWWWWB                                           BWWWWWWB                  ",
            "                   BBWWWWWBB                                       BBWWWWWBB                   ",
            "                     BWWWWWWBBB                                 BBBWWWWWWB                     ",
            "                      BBWWWWWWWBB                             BBWWWWWWWBB                      ",
            "                        BWWWWWWWWBBB                       BBBWWWWWWWWB                        ",
            "                         BBWWWWWWWWWBBBBB             BBBBBWWWWWWWWWBB                         ",
            "                           BBBWWWWWWWWWWWBBBBBBBBBBBBBWWWWWWWWWWWBBB                           ",
            "                              BBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBB                              ",
            "                                BBBBWWWWWWWWWWWWWWWWWWWWWWWBBBB                                ",
            "                                    BBBBBWWWWWWWWWWWWWBBBBB                                    ",
            "                                         BBBBBBBBBBBBB                                         "
        },
        {
            "                                                                                               ",
            "                                         BBBB     BBBB                                         ",
            "                                    BBBBBBBBB     BBBBBBBBB                                    ",
            "                                BBBBBBBBBBBBB     BBBBBBBBBBBBB                                ",
            "                              BBBBBBBBBBB             BBBBBBBBBBB                              ",
            "                           BBBBBBBBB                       BBBBBBBBB                           ",
            "                         BBBBBBBB                             BBBBBBBB                         ",
            "                        BBBBBBB                                 BBBBBBB                        ",
            "                      BBBBBB                                       BBBBBB                      ",
            "                     BBBBB                                           BBBBB                     ",
            "                   BBBBBB                                             BBBBBB                   ",
            "                  BBBBB                                                 BBBBB                  ",
            "                 BBBBB                                                   BBBBB                 ",
            "                BBBBB                                                     BBBBB                ",
            "               BBBB                                                         BBBB               ",
            "              BBBB                                                           BBBB              ",
            "             BBBB                                                             BBBB             ",
            "            BBBB                                                               BBBB            ",
            "           BBBB                                                                 BBBB           ",
            "          BBBB                                                                   BBBB          ",
            "          BBBB                                                                   BBBB          ",
            "         BBBB                                                                     BBBB         ",
            "        BBBB                                                                       BBBB        ",
            "        BBB                                                                         BBB        ",
            "       BBBB                                                                         BBBB       ",
            "      BBBB                                                                           BBBB      ",
            "      BBB                                                                             BBB      ",
            "     BBBB                                                                             BBBB     ",
            "     BBB                                                                               BBB     ",
            "     BBB                                                                               BBB     ",
            "    BBBB                                                                               BBBB    ",
            "    BBB                                                                                 BBB    ",
            "   BBBB                                                                                 BBBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBBB                                                                                 BBBB   ",
            "    BBB                                                                                 BBB    ",
            "    BBBB                                                                               BBBB    ",
            "     BBB                                                                               BBB     ",
            "     BBB                                                                               BBB     ",
            "     BBBB                                                                             BBBB     ",
            "      BBB                                                                             BBB      ",
            "      BBBB                                                                           BBBB      ",
            "       BBBB                                                                         BBBB       ",
            "        BBB                                                                         BBB        ",
            "        BBBB                                                                       BBBB        ",
            "         BBBB                                                                     BBBB         ",
            "          BBBB                                                                   BBBB          ",
            "          BBBB                                                                   BBBB          ",
            "           BBBB                                                                 BBBB           ",
            "            BBBB                                                               BBBB            ",
            "             BBBB                                                             BBBB             ",
            "              BBBB                                                           BBBB              ",
            "               BBBB                                                         BBBB               ",
            "                BBBBB                                                     BBBBB                ",
            "                 BBBBB                                                   BBBBB                 ",
            "                  BBBBB                                                 BBBBB                  ",
            "                   BBBBBB                                             BBBBBB                   ",
            "                     BBBBB                                           BBBBB                     ",
            "                      BBBBBB                                       BBBBBB                      ",
            "                        BBBBBBB                                 BBBBBBB                        ",
            "                         BBBBBBBB                             BBBBBBBB                         ",
            "                           BBBBBBBBB                       BBBBBBBBB                           ",
            "                              BBBBBBBBBBB             BBBBBBBBBBB                              ",
            "                                BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                ",
            "                                    BBBBBBBBBBBBBBBBBBBBBBB                                    ",
            "                                         BBBBBBBBBBBBB                                         ",
            "                                                                                               "
        }
    });
}
