package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_7 {
    public static final String[][] CYCLOTRON_SHAPE_7_IDENTITY = transpose(new String[][] {
        {
            "                                                                                                         ",
            "                                             BBBBB     BBBBB                                             ",
            "                                        BBBBBBBBBB     BBBBBBBBBB                                        ",
            "                                     BBBBBBBBBBBBB     BBBBBBBBBBBBB                                     ",
            "                                  BBBBBBBBBBBB             BBBBBBBBBBBB                                  ",
            "                               BBBBBBBBBB                       BBBBBBBBBB                               ",
            "                             BBBBBBBB                               BBBBBBBB                             ",
            "                           BBBBBBBB                                   BBBBBBBB                           ",
            "                          BBBBBB                                         BBBBBB                          ",
            "                        BBBBBB                                             BBBBBB                        ",
            "                       BBBBB                                                 BBBBB                       ",
            "                     BBBBBB                                                   BBBBBB                     ",
            "                    BBBBB                                                       BBBBB                    ",
            "                   BBBBB                                                         BBBBB                   ",
            "                  BBBBB                                                           BBBBB                  ",
            "                BBBBB                                                               BBBBB                ",
            "               BBBBB                                                                 BBBBB               ",
            "               BBBB                                                                   BBBB               ",
            "              BBBB                                                                     BBBB              ",
            "             BBBB                                                                       BBBB             ",
            "            BBBB                                                                         BBBB            ",
            "           BBBB                                                                           BBBB           ",
            "           BBBB                                                                           BBBB           ",
            "          BBBB                                                                             BBBB          ",
            "         BBBB                                                                               BBBB         ",
            "         BBB                                                                                 BBB         ",
            "        BBBB                                                                                 BBBB        ",
            "       BBBB                                                                                   BBBB       ",
            "       BBB                                                                                     BBB       ",
            "      BBBB                                                                                     BBBB      ",
            "      BBB                                                                                       BBB      ",
            "     BBBB                                                                                       BBBB     ",
            "     BBB                                                                                         BBB     ",
            "     BBB                                                                                         BBB     ",
            "    BBBB                                                                                         BBBB    ",
            "    BBB                                                                                           BBB    ",
            "    BBB                                                                                           BBB    ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "  BBBB                                                                                             BBBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            " BBBB                                                                                               BBBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBBB                                                                                               BBBB ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBBB                                                                                             BBBB  ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "    BBB                                                                                           BBB    ",
            "    BBB                                                                                           BBB    ",
            "    BBBB                                                                                         BBBB    ",
            "     BBB                                                                                         BBB     ",
            "     BBB                                                                                         BBB     ",
            "     BBBB                                                                                       BBBB     ",
            "      BBB                                                                                       BBB      ",
            "      BBBB                                                                                     BBBB      ",
            "       BBB                                                                                     BBB       ",
            "       BBBB                                                                                   BBBB       ",
            "        BBBB                                                                                 BBBB        ",
            "         BBB                                                                                 BBB         ",
            "         BBBB                                                                               BBBB         ",
            "          BBBB                                                                             BBBB          ",
            "           BBBB                                                                           BBBB           ",
            "           BBBB                                                                           BBBB           ",
            "            BBBB                                                                         BBBB            ",
            "             BBBB                                                                       BBBB             ",
            "              BBBB                                                                     BBBB              ",
            "               BBBB                                                                   BBBB               ",
            "               BBBBB                                                                 BBBBB               ",
            "                BBBBB                                                               BBBBB                ",
            "                  BBBBB                                                           BBBBB                  ",
            "                   BBBBB                                                         BBBBB                   ",
            "                    BBBBB                                                       BBBBB                    ",
            "                     BBBBBB                                                   BBBBBB                     ",
            "                       BBBBB                                                 BBBBB                       ",
            "                        BBBBBB                                             BBBBBB                        ",
            "                          BBBBBB                                         BBBBBB                          ",
            "                           BBBBBBBB                                   BBBBBBBB                           ",
            "                             BBBBBBBB                               BBBBBBBB                             ",
            "                               BBBBBBBBBB                       BBBBBBBBBB                               ",
            "                                  BBBBBBBBBBBB             BBBBBBBBBBBB                                  ",
            "                                     BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                     ",
            "                                        BBBBBBBBBBBBBBBBBBBBBBBBB                                        ",
            "                                             BBBBBBBBBBBBBBB                                             ",
            "                                                                                                         "
        },
        {
            "                                             BBBBB     BBBBB                                             ",
            "                                        BBBBBWWWWW     WWWWWBBBBB                                        ",
            "                                     BBBWWWWWWWWWW     WWWWWWWWWWBBB                                     ",
            "                                  BBBWWWWWWWWWWWWW     WWWWWWWWWWWWWBBB                                  ",
            "                               BBBWWWWWWWWWWWWBBBB     BBBBWWWWWWWWWWWWBBB                               ",
            "                             BBWWWWWWWWWWBBBBB             BBBBBWWWWWWWWWWBB                             ",
            "                           BBWWWWWWWWBBBB                       BBBBWWWWWWWWBB                           ",
            "                          BWWWWWWWWBB                               BBWWWWWWWWB                          ",
            "                        BBWWWWWWBBB                                   BBBWWWWWWBB                        ",
            "                       BWWWWWWBB                                         BBWWWWWWB                       ",
            "                     BBWWWWWBB                                             BBWWWWWBB                     ",
            "                    BWWWWWWB                                                 BWWWWWWB                    ",
            "                   BWWWWWBB                                                   BBWWWWWB                   ",
            "                  BWWWWWB                                                       BWWWWWB                  ",
            "                BBWWWWWB                                                         BWWWWWBB                ",
            "               BWWWWWBB                                                           BBWWWWWB               ",
            "              BWWWWWB                                                               BWWWWWB              ",
            "              BWWWWB                                                                 BWWWWB              ",
            "             BWWWWB                                                                   BWWWWB             ",
            "            BWWWWB                                                                     BWWWWB            ",
            "           BWWWWB                                                                       BWWWWB           ",
            "          BWWWWB                                                                         BWWWWB          ",
            "          BWWWWB                                                                         BWWWWB          ",
            "         BWWWWB                                                                           BWWWWB         ",
            "        BWWWWB                                                                             BWWWWB        ",
            "        BWWWB                                                                               BWWWB        ",
            "       BWWWWB                                                                               BWWWWB       ",
            "      BWWWWB                                                                                 BWWWWB      ",
            "      BWWWB                                                                                   BWWWB      ",
            "     BWWWWB                                                                                   BWWWWB     ",
            "     BWWWB                                                                                     BWWWB     ",
            "    BWWWWB                                                                                     BWWWWB    ",
            "    BWWWB                                                                                       BWWWB    ",
            "    BWWWB                                                                                       BWWWB    ",
            "   BWWWWB                                                                                       BWWWWB   ",
            "   BWWWB                                                                                         BWWWB   ",
            "   BWWWB                                                                                         BWWWB   ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            " BWWWWB                                                                                           BWWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            "BWWWWB                                                                                             BWWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWWB                                                                                             BWWWWB",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWWB                                                                                           BWWWWB ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            "   BWWWB                                                                                         BWWWB   ",
            "   BWWWB                                                                                         BWWWB   ",
            "   BWWWWB                                                                                       BWWWWB   ",
            "    BWWWB                                                                                       BWWWB    ",
            "    BWWWB                                                                                       BWWWB    ",
            "    BWWWWB                                                                                     BWWWWB    ",
            "     BWWWB                                                                                     BWWWB     ",
            "     BWWWWB                                                                                   BWWWWB     ",
            "      BWWWB                                                                                   BWWWB      ",
            "      BWWWWB                                                                                 BWWWWB      ",
            "       BWWWWB                                                                               BWWWWB       ",
            "        BWWWB                                                                               BWWWB        ",
            "        BWWWWB                                                                             BWWWWB        ",
            "         BWWWWB                                                                           BWWWWB         ",
            "          BWWWWB                                                                         BWWWWB          ",
            "          BWWWWB                                                                         BWWWWB          ",
            "           BWWWWB                                                                       BWWWWB           ",
            "            BWWWWB                                                                     BWWWWB            ",
            "             BWWWWB                                                                   BWWWWB             ",
            "              BWWWWB                                                                 BWWWWB              ",
            "              BWWWWWB                                                               BWWWWWB              ",
            "               BWWWWWBB                                                           BBWWWWWB               ",
            "                BBWWWWWB                                                         BWWWWWBB                ",
            "                  BWWWWWB                                                       BWWWWWB                  ",
            "                   BWWWWWBB                                                   BBWWWWWB                   ",
            "                    BWWWWWWB                                                 BWWWWWWB                    ",
            "                     BBWWWWWBB                                             BBWWWWWBB                     ",
            "                       BWWWWWWBB                                         BBWWWWWWB                       ",
            "                        BBWWWWWWBBB                                   BBBWWWWWWBB                        ",
            "                          BWWWWWWWWBB                               BBWWWWWWWWB                          ",
            "                           BBWWWWWWWWBBBB                       BBBBWWWWWWWWBB                           ",
            "                             BBWWWWWWWWWWBBBBB             BBBBBWWWWWWWWWWBB                             ",
            "                               BBBWWWWWWWWWWWWBBBBBBBBBBBBBWWWWWWWWWWWWBBB                               ",
            "                                  BBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                  ",
            "                                     BBBWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                     ",
            "                                        BBBBBWWWWWWWWWWWWWWWBBBBB                                        ",
            "                                             BBBBBBBBBBBBBBB                                             "
        },
        {
            "                                             BBBBB     BBBBB                                             ",
            "                                        BBBBBWWWWW  ~  WWWWWBBBBB                                        ",
            "                                     BBBWWWWW---------------WWWWWBBB                                     ",
            "                                  BBBWWW-----WWWWW     WWWWW-----WWWBBB                                  ",
            "                               BBBWWW---WWWWWWBBBB     BBBBWWWWWW---WWWBBB                               ",
            "                             BBWWW---WWWWBBBBB             BBBBBWWWW---WWWBB                             ",
            "                           BBWWW--WWWBBBB                       BBBBWWW--WWWBB                           ",
            "                          BWWW--WWWBB                               BBWWW--WWWB                          ",
            "                        BBWW--WWBBB                                   BBBWW--WWBB                        ",
            "                       BWW--WWBB                                         BBWW--WWB                       ",
            "                     BBWW-WWBB                                             BBWW-WWBB                     ",
            "                    BWW--WWB                                                 BWW--WWB                    ",
            "                   BWW-WWBB                                                   BBWW-WWB                   ",
            "                  BWW-WWB                                                       BWW-WWB                  ",
            "                BBW--WWB                                                         BWW--WBB                ",
            "               BWW-WWBB                                                           BBWW-WWB               ",
            "              BWW-WWB                                                               BWW-WWB              ",
            "              BW-WWB                                                                 BWW-WB              ",
            "             BW-WWB                                                                   BWW-WB             ",
            "            BW-WWB                                                                     BWW-WB            ",
            "           BWW-WB                                                                       BW-WWB           ",
            "          BWW-WB                                                                         BW-WWB          ",
            "          BW-WWB                                                                         BWW-WB          ",
            "         BW-WWB                                                                           BWW-WB         ",
            "        BWW-WB                                                                             BW-WWB        ",
            "        BW-WB                                                                               BW-WB        ",
            "       BW-WWB                                                                               BWW-WB       ",
            "      BWW-WB                                                                                 BW-WWB      ",
            "      BW-WB                                                                                   BW-WB      ",
            "     BWW-WB                                                                                   BW-WWB     ",
            "     BW-WB                                                                                     BW-WB     ",
            "    BWW-WB                                                                                     BW-WWB    ",
            "    BW-WB                                                                                       BW-WB    ",
            "    BW-WB                                                                                       BW-WB    ",
            "   BW-WWB                                                                                       BWW-WB   ",
            "   BW-WB                                                                                         BW-WB   ",
            "   BW-WB                                                                                         BW-WB   ",
            "  BW-WB                                                                                           BW-WB  ",
            "  BW-WB                                                                                           BW-WB  ",
            "  BW-WB                                                                                           BW-WB  ",
            " BW-WWB                                                                                           BWW-WB ",
            " BW-WB                                                                                             BW-WB ",
            " BW-WB                                                                                             BW-WB ",
            " BW-WB                                                                                             BW-WB ",
            " BW-WB                                                                                             BW-WB ",
            "BW-WWB                                                                                             BWW-WB",
            "BW-WB                                                                                               BW-WB",
            "BW-WB                                                                                               BW-WB",
            "BW-WB                                                                                               BW-WB",
            "BW-WB                                                                                               BW-WB",
            "BW-WB                                                                                               BW-WB",
            "BW-WB                                                                                               BW-WB",
            "BW-WB                                                                                               BW-WB",
            "BW-WB                                                                                               BW-WB",
            "BW-WB                                                                                               BW-WB",
            "BW-WB                                                                                               BW-WB",
            "BW-WB                                                                                               BW-WB",
            "BW-WB                                                                                               BW-WB",
            "BW-WB                                                                                               BW-WB",
            "BW-WWB                                                                                             BWW-WB",
            " BW-WB                                                                                             BW-WB ",
            " BW-WB                                                                                             BW-WB ",
            " BW-WB                                                                                             BW-WB ",
            " BW-WB                                                                                             BW-WB ",
            " BW-WWB                                                                                           BWW-WB ",
            "  BW-WB                                                                                           BW-WB  ",
            "  BW-WB                                                                                           BW-WB  ",
            "  BW-WB                                                                                           BW-WB  ",
            "   BW-WB                                                                                         BW-WB   ",
            "   BW-WB                                                                                         BW-WB   ",
            "   BW-WWB                                                                                       BWW-WB   ",
            "    BW-WB                                                                                       BW-WB    ",
            "    BW-WB                                                                                       BW-WB    ",
            "    BWW-WB                                                                                     BW-WWB    ",
            "     BW-WB                                                                                     BW-WB     ",
            "     BWW-WB                                                                                   BW-WWB     ",
            "      BW-WB                                                                                   BW-WB      ",
            "      BWW-WB                                                                                 BW-WWB      ",
            "       BW-WWB                                                                               BWW-WB       ",
            "        BW-WB                                                                               BW-WB        ",
            "        BWW-WB                                                                             BW-WWB        ",
            "         BW-WWB                                                                           BWW-WB         ",
            "          BW-WWB                                                                         BWW-WB          ",
            "          BWW-WB                                                                         BW-WWB          ",
            "           BWW-WB                                                                       BW-WWB           ",
            "            BW-WWB                                                                     BWW-WB            ",
            "             BW-WWB                                                                   BWW-WB             ",
            "              BW-WWB                                                                 BWW-WB              ",
            "              BWW-WWB                                                               BWW-WWB              ",
            "               BWW-WWBB                                                           BBWW-WWB               ",
            "                BBW--WWB                                                         BWW--WBB                ",
            "                  BWW-WWB                                                       BWW-WWB                  ",
            "                   BWW-WWBB                                                   BBWW-WWB                   ",
            "                    BWW--WWB                                                 BWW--WWB                    ",
            "                     BBWW-WWBB                                             BBWW-WWBB                     ",
            "                       BWW--WWBB                                         BBWW--WWB                       ",
            "                        BBWW--WWBBB                                   BBBWW--WWBB                        ",
            "                          BWWW--WWWBB                               BBWWW--WWWB                          ",
            "                           BBWWW--WWWBBBB                       BBBBWWW--WWWBB                           ",
            "                             BBWWW---WWWWBBBBB             BBBBBWWWW---WWWBB                             ",
            "                               BBBWWW---WWWWWWBBBBBBBBBBBBBWWWWWW---WWWBBB                               ",
            "                                  BBBWWW-----WWWWWWWWWWWWWWW-----WWWBBB                                  ",
            "                                     BBBWWWWW---------------WWWWWBBB                                     ",
            "                                        BBBBBWWWWWWWWWWWWWWWBBBBB                                        ",
            "                                             BBBBBBBBBBBBBBB                                             "
        },
        {
            "                                             BBBBB     BBBBB                                             ",
            "                                        BBBBBWWWWW     WWWWWBBBBB                                        ",
            "                                     BBBWWWWWWWWWW     WWWWWWWWWWBBB                                     ",
            "                                  BBBWWWWWWWWWWWWW     WWWWWWWWWWWWWBBB                                  ",
            "                               BBBWWWWWWWWWWWWBBBB     BBBBWWWWWWWWWWWWBBB                               ",
            "                             BBWWWWWWWWWWBBBBB             BBBBBWWWWWWWWWWBB                             ",
            "                           BBWWWWWWWWBBBB                       BBBBWWWWWWWWBB                           ",
            "                          BWWWWWWWWBB                               BBWWWWWWWWB                          ",
            "                        BBWWWWWWBBB                                   BBBWWWWWWBB                        ",
            "                       BWWWWWWBB                                         BBWWWWWWB                       ",
            "                     BBWWWWWBB                                             BBWWWWWBB                     ",
            "                    BWWWWWWB                                                 BWWWWWWB                    ",
            "                   BWWWWWBB                                                   BBWWWWWB                   ",
            "                  BWWWWWB                                                       BWWWWWB                  ",
            "                BBWWWWWB                                                         BWWWWWBB                ",
            "               BWWWWWBB                                                           BBWWWWWB               ",
            "              BWWWWWB                                                               BWWWWWB              ",
            "              BWWWWB                                                                 BWWWWB              ",
            "             BWWWWB                                                                   BWWWWB             ",
            "            BWWWWB                                                                     BWWWWB            ",
            "           BWWWWB                                                                       BWWWWB           ",
            "          BWWWWB                                                                         BWWWWB          ",
            "          BWWWWB                                                                         BWWWWB          ",
            "         BWWWWB                                                                           BWWWWB         ",
            "        BWWWWB                                                                             BWWWWB        ",
            "        BWWWB                                                                               BWWWB        ",
            "       BWWWWB                                                                               BWWWWB       ",
            "      BWWWWB                                                                                 BWWWWB      ",
            "      BWWWB                                                                                   BWWWB      ",
            "     BWWWWB                                                                                   BWWWWB     ",
            "     BWWWB                                                                                     BWWWB     ",
            "    BWWWWB                                                                                     BWWWWB    ",
            "    BWWWB                                                                                       BWWWB    ",
            "    BWWWB                                                                                       BWWWB    ",
            "   BWWWWB                                                                                       BWWWWB   ",
            "   BWWWB                                                                                         BWWWB   ",
            "   BWWWB                                                                                         BWWWB   ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            " BWWWWB                                                                                           BWWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            "BWWWWB                                                                                             BWWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWB                                                                                               BWWWB",
            "BWWWWB                                                                                             BWWWWB",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWB                                                                                             BWWWB ",
            " BWWWWB                                                                                           BWWWWB ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            "  BWWWB                                                                                           BWWWB  ",
            "   BWWWB                                                                                         BWWWB   ",
            "   BWWWB                                                                                         BWWWB   ",
            "   BWWWWB                                                                                       BWWWWB   ",
            "    BWWWB                                                                                       BWWWB    ",
            "    BWWWB                                                                                       BWWWB    ",
            "    BWWWWB                                                                                     BWWWWB    ",
            "     BWWWB                                                                                     BWWWB     ",
            "     BWWWWB                                                                                   BWWWWB     ",
            "      BWWWB                                                                                   BWWWB      ",
            "      BWWWWB                                                                                 BWWWWB      ",
            "       BWWWWB                                                                               BWWWWB       ",
            "        BWWWB                                                                               BWWWB        ",
            "        BWWWWB                                                                             BWWWWB        ",
            "         BWWWWB                                                                           BWWWWB         ",
            "          BWWWWB                                                                         BWWWWB          ",
            "          BWWWWB                                                                         BWWWWB          ",
            "           BWWWWB                                                                       BWWWWB           ",
            "            BWWWWB                                                                     BWWWWB            ",
            "             BWWWWB                                                                   BWWWWB             ",
            "              BWWWWB                                                                 BWWWWB              ",
            "              BWWWWWB                                                               BWWWWWB              ",
            "               BWWWWWBB                                                           BBWWWWWB               ",
            "                BBWWWWWB                                                         BWWWWWBB                ",
            "                  BWWWWWB                                                       BWWWWWB                  ",
            "                   BWWWWWBB                                                   BBWWWWWB                   ",
            "                    BWWWWWWB                                                 BWWWWWWB                    ",
            "                     BBWWWWWBB                                             BBWWWWWBB                     ",
            "                       BWWWWWWBB                                         BBWWWWWWB                       ",
            "                        BBWWWWWWBBB                                   BBBWWWWWWBB                        ",
            "                          BWWWWWWWWBB                               BBWWWWWWWWB                          ",
            "                           BBWWWWWWWWBBBB                       BBBBWWWWWWWWBB                           ",
            "                             BBWWWWWWWWWWBBBBB             BBBBBWWWWWWWWWWBB                             ",
            "                               BBBWWWWWWWWWWWWBBBBBBBBBBBBBWWWWWWWWWWWWBBB                               ",
            "                                  BBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                  ",
            "                                     BBBWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                     ",
            "                                        BBBBBWWWWWWWWWWWWWWWBBBBB                                        ",
            "                                             BBBBBBBBBBBBBBB                                             "
        },
        {
            "                                                                                                         ",
            "                                             BBBBB     BBBBB                                             ",
            "                                        BBBBBBBBBB     BBBBBBBBBB                                        ",
            "                                     BBBBBBBBBBBBB     BBBBBBBBBBBBB                                     ",
            "                                  BBBBBBBBBBBB             BBBBBBBBBBBB                                  ",
            "                               BBBBBBBBBB                       BBBBBBBBBB                               ",
            "                             BBBBBBBB                               BBBBBBBB                             ",
            "                           BBBBBBBB                                   BBBBBBBB                           ",
            "                          BBBBBB                                         BBBBBB                          ",
            "                        BBBBBB                                             BBBBBB                        ",
            "                       BBBBB                                                 BBBBB                       ",
            "                     BBBBBB                                                   BBBBBB                     ",
            "                    BBBBB                                                       BBBBB                    ",
            "                   BBBBB                                                         BBBBB                   ",
            "                  BBBBB                                                           BBBBB                  ",
            "                BBBBB                                                               BBBBB                ",
            "               BBBBB                                                                 BBBBB               ",
            "               BBBB                                                                   BBBB               ",
            "              BBBB                                                                     BBBB              ",
            "             BBBB                                                                       BBBB             ",
            "            BBBB                                                                         BBBB            ",
            "           BBBB                                                                           BBBB           ",
            "           BBBB                                                                           BBBB           ",
            "          BBBB                                                                             BBBB          ",
            "         BBBB                                                                               BBBB         ",
            "         BBB                                                                                 BBB         ",
            "        BBBB                                                                                 BBBB        ",
            "       BBBB                                                                                   BBBB       ",
            "       BBB                                                                                     BBB       ",
            "      BBBB                                                                                     BBBB      ",
            "      BBB                                                                                       BBB      ",
            "     BBBB                                                                                       BBBB     ",
            "     BBB                                                                                         BBB     ",
            "     BBB                                                                                         BBB     ",
            "    BBBB                                                                                         BBBB    ",
            "    BBB                                                                                           BBB    ",
            "    BBB                                                                                           BBB    ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "  BBBB                                                                                             BBBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            " BBBB                                                                                               BBBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBB                                                                                                 BBB ",
            " BBBB                                                                                               BBBB ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBB                                                                                               BBB  ",
            "  BBBB                                                                                             BBBB  ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "   BBB                                                                                             BBB   ",
            "    BBB                                                                                           BBB    ",
            "    BBB                                                                                           BBB    ",
            "    BBBB                                                                                         BBBB    ",
            "     BBB                                                                                         BBB     ",
            "     BBB                                                                                         BBB     ",
            "     BBBB                                                                                       BBBB     ",
            "      BBB                                                                                       BBB      ",
            "      BBBB                                                                                     BBBB      ",
            "       BBB                                                                                     BBB       ",
            "       BBBB                                                                                   BBBB       ",
            "        BBBB                                                                                 BBBB        ",
            "         BBB                                                                                 BBB         ",
            "         BBBB                                                                               BBBB         ",
            "          BBBB                                                                             BBBB          ",
            "           BBBB                                                                           BBBB           ",
            "           BBBB                                                                           BBBB           ",
            "            BBBB                                                                         BBBB            ",
            "             BBBB                                                                       BBBB             ",
            "              BBBB                                                                     BBBB              ",
            "               BBBB                                                                   BBBB               ",
            "               BBBBB                                                                 BBBBB               ",
            "                BBBBB                                                               BBBBB                ",
            "                  BBBBB                                                           BBBBB                  ",
            "                   BBBBB                                                         BBBBB                   ",
            "                    BBBBB                                                       BBBBB                    ",
            "                     BBBBBB                                                   BBBBBB                     ",
            "                       BBBBB                                                 BBBBB                       ",
            "                        BBBBBB                                             BBBBBB                        ",
            "                          BBBBBB                                         BBBBBB                          ",
            "                           BBBBBBBB                                   BBBBBBBB                           ",
            "                             BBBBBBBB                               BBBBBBBB                             ",
            "                               BBBBBBBBBB                       BBBBBBBBBB                               ",
            "                                  BBBBBBBBBBBB             BBBBBBBBBBBB                                  ",
            "                                     BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                     ",
            "                                        BBBBBBBBBBBBBBBBBBBBBBBBB                                        ",
            "                                             BBBBBBBBBBBBBBB                                             ",
            "                                                                                                         "
        }
    });
}
