package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_9 {
    public static final String[][] CYCLOTRON_SHAPE_9_IDENTITY = transpose(new String[][] {
        {
            "                                                                                                                             ",
            "                                                       BBBBB     BBBBB                                                       ",
            "                                                 BBBBBBBBBBB     BBBBBBBBBBB                                                 ",
            "                                             BBBBBBBBBBBBBBB     BBBBBBBBBBBBBBB                                             ",
            "                                          BBBBBBBBBBBBB               BBBBBBBBBBBBB                                          ",
            "                                       BBBBBBBBBB                           BBBBBBBBBB                                       ",
            "                                     BBBBBBBBB                                 BBBBBBBBB                                     ",
            "                                   BBBBBBBB                                       BBBBBBBB                                   ",
            "                                 BBBBBBB                                             BBBBBBB                                 ",
            "                               BBBBBBB                                                 BBBBBBB                               ",
            "                              BBBBBB                                                     BBBBBB                              ",
            "                            BBBBBB                                                         BBBBBB                            ",
            "                           BBBBB                                                             BBBBB                           ",
            "                         BBBBBB                                                               BBBBBB                         ",
            "                        BBBBB                                                                   BBBBB                        ",
            "                       BBBBB                                                                     BBBBB                       ",
            "                     BBBBBB                                                                       BBBBBB                     ",
            "                    BBBBB                                                                           BBBBB                    ",
            "                   BBBBB                                                                             BBBBB                   ",
            "                  BBBBB                                                                               BBBBB                  ",
            "                 BBBBB                                                                                 BBBBB                 ",
            "                BBBBB                                                                                   BBBBB                ",
            "                BBBB                                                                                     BBBB                ",
            "               BBBB                                                                                       BBBB               ",
            "              BBBB                                                                                         BBBB              ",
            "             BBBB                                                                                           BBBB             ",
            "             BBBB                                                                                           BBBB             ",
            "            BBBB                                                                                             BBBB            ",
            "           BBBB                                                                                               BBBB           ",
            "           BBB                                                                                                 BBB           ",
            "          BBBB                                                                                                 BBBB          ",
            "         BBBB                                                                                                   BBBB         ",
            "         BBB                                                                                                     BBB         ",
            "        BBBB                                                                                                     BBBB        ",
            "        BBB                                                                                                       BBB        ",
            "       BBBB                                                                                                       BBBB       ",
            "       BBB                                                                                                         BBB       ",
            "      BBBB                                                                                                         BBBB      ",
            "      BBB                                                                                                           BBB      ",
            "     BBBB                                                                                                           BBBB     ",
            "     BBB                                                                                                             BBB     ",
            "     BBB                                                                                                             BBB     ",
            "    BBBB                                                                                                             BBBB    ",
            "    BBB                                                                                                               BBB    ",
            "    BBB                                                                                                               BBB    ",
            "   BBBB                                                                                                               BBBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBBB                                                                                                               BBBB   ",
            "    BBB                                                                                                               BBB    ",
            "    BBB                                                                                                               BBB    ",
            "    BBBB                                                                                                             BBBB    ",
            "     BBB                                                                                                             BBB     ",
            "     BBB                                                                                                             BBB     ",
            "     BBBB                                                                                                           BBBB     ",
            "      BBB                                                                                                           BBB      ",
            "      BBBB                                                                                                         BBBB      ",
            "       BBB                                                                                                         BBB       ",
            "       BBBB                                                                                                       BBBB       ",
            "        BBB                                                                                                       BBB        ",
            "        BBBB                                                                                                     BBBB        ",
            "         BBB                                                                                                     BBB         ",
            "         BBBB                                                                                                   BBBB         ",
            "          BBBB                                                                                                 BBBB          ",
            "           BBB                                                                                                 BBB           ",
            "           BBBB                                                                                               BBBB           ",
            "            BBBB                                                                                             BBBB            ",
            "             BBBB                                                                                           BBBB             ",
            "             BBBB                                                                                           BBBB             ",
            "              BBBB                                                                                         BBBB              ",
            "               BBBB                                                                                       BBBB               ",
            "                BBBB                                                                                     BBBB                ",
            "                BBBBB                                                                                   BBBBB                ",
            "                 BBBBB                                                                                 BBBBB                 ",
            "                  BBBBB                                                                               BBBBB                  ",
            "                   BBBBB                                                                             BBBBB                   ",
            "                    BBBBB                                                                           BBBBB                    ",
            "                     BBBBBB                                                                       BBBBBB                     ",
            "                       BBBBB                                                                     BBBBB                       ",
            "                        BBBBB                                                                   BBBBB                        ",
            "                         BBBBBB                                                               BBBBBB                         ",
            "                           BBBBB                                                             BBBBB                           ",
            "                            BBBBBB                                                         BBBBBB                            ",
            "                              BBBBBB                                                     BBBBBB                              ",
            "                               BBBBBBB                                                 BBBBBBB                               ",
            "                                 BBBBBBB                                             BBBBBBB                                 ",
            "                                   BBBBBBBB                                       BBBBBBBB                                   ",
            "                                     BBBBBBBBB                                 BBBBBBBBB                                     ",
            "                                       BBBBBBBBBB                           BBBBBBBBBB                                       ",
            "                                          BBBBBBBBBBBBB               BBBBBBBBBBBBB                                          ",
            "                                             BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                             ",
            "                                                 BBBBBBBBBBBBBBBBBBBBBBBBBBB                                                 ",
            "                                                       BBBBBBBBBBBBBBB                                                       ",
            "                                                                                                                             "
        },
        {
            "                                                       BBBBB     BBBBB                                                       ",
            "                                                 BBBBBBWWWWW     WWWWWBBBBBB                                                 ",
            "                                             BBBBWWWWWWWWWWW     WWWWWWWWWWWBBBB                                             ",
            "                                          BBBWWWWWWWWWWWWWWW     WWWWWWWWWWWWWWWBBB                                          ",
            "                                       BBBWWWWWWWWWWWWWBBBBB     BBBBBWWWWWWWWWWWWWBBB                                       ",
            "                                     BBWWWWWWWWWWBBBBBB               BBBBBBWWWWWWWWWWBB                                     ",
            "                                   BBWWWWWWWWWBBB                           BBBWWWWWWWWWBB                                   ",
            "                                 BBWWWWWWWWBBB                                 BBBWWWWWWWWBB                                 ",
            "                               BBWWWWWWWBBB                                       BBBWWWWWWWBB                               ",
            "                              BWWWWWWWBB                                             BBWWWWWWWB                              ",
            "                            BBWWWWWWBB                                                 BBWWWWWWBB                            ",
            "                           BWWWWWWBB                                                     BBWWWWWWB                           ",
            "                         BBWWWWWBB                                                         BBWWWWWBB                         ",
            "                        BWWWWWWB                                                             BWWWWWWB                        ",
            "                       BWWWWWBB                                                               BBWWWWWB                       ",
            "                     BBWWWWWB                                                                   BWWWWWBB                     ",
            "                    BWWWWWWB                                                                     BWWWWWWB                    ",
            "                   BWWWWWBB                                                                       BBWWWWWB                   ",
            "                  BWWWWWB                                                                           BWWWWWB                  ",
            "                 BWWWWWB                                                                             BWWWWWB                 ",
            "                BWWWWWB                                                                               BWWWWWB                ",
            "               BWWWWWB                                                                                 BWWWWWB               ",
            "               BWWWWB                                                                                   BWWWWB               ",
            "              BWWWWB                                                                                     BWWWWB              ",
            "             BWWWWB                                                                                       BWWWWB             ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "           BWWWWB                                                                                           BWWWWB           ",
            "          BWWWWB                                                                                             BWWWWB          ",
            "          BWWWB                                                                                               BWWWB          ",
            "         BWWWWB                                                                                               BWWWWB         ",
            "        BWWWWB                                                                                                 BWWWWB        ",
            "        BWWWB                                                                                                   BWWWB        ",
            "       BWWWWB                                                                                                   BWWWWB       ",
            "       BWWWB                                                                                                     BWWWB       ",
            "      BWWWWB                                                                                                     BWWWWB      ",
            "      BWWWB                                                                                                       BWWWB      ",
            "     BWWWWB                                                                                                       BWWWWB     ",
            "     BWWWB                                                                                                         BWWWB     ",
            "    BWWWWB                                                                                                         BWWWWB    ",
            "    BWWWB                                                                                                           BWWWB    ",
            "    BWWWB                                                                                                           BWWWB    ",
            "   BWWWWB                                                                                                           BWWWWB   ",
            "   BWWWB                                                                                                             BWWWB   ",
            "   BWWWB                                                                                                             BWWWB   ",
            "  BWWWWB                                                                                                             BWWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWWB                                                                                                             BWWWWB  ",
            "   BWWWB                                                                                                             BWWWB   ",
            "   BWWWB                                                                                                             BWWWB   ",
            "   BWWWWB                                                                                                           BWWWWB   ",
            "    BWWWB                                                                                                           BWWWB    ",
            "    BWWWB                                                                                                           BWWWB    ",
            "    BWWWWB                                                                                                         BWWWWB    ",
            "     BWWWB                                                                                                         BWWWB     ",
            "     BWWWWB                                                                                                       BWWWWB     ",
            "      BWWWB                                                                                                       BWWWB      ",
            "      BWWWWB                                                                                                     BWWWWB      ",
            "       BWWWB                                                                                                     BWWWB       ",
            "       BWWWWB                                                                                                   BWWWWB       ",
            "        BWWWB                                                                                                   BWWWB        ",
            "        BWWWWB                                                                                                 BWWWWB        ",
            "         BWWWWB                                                                                               BWWWWB         ",
            "          BWWWB                                                                                               BWWWB          ",
            "          BWWWWB                                                                                             BWWWWB          ",
            "           BWWWWB                                                                                           BWWWWB           ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "             BWWWWB                                                                                       BWWWWB             ",
            "              BWWWWB                                                                                     BWWWWB              ",
            "               BWWWWB                                                                                   BWWWWB               ",
            "               BWWWWWB                                                                                 BWWWWWB               ",
            "                BWWWWWB                                                                               BWWWWWB                ",
            "                 BWWWWWB                                                                             BWWWWWB                 ",
            "                  BWWWWWB                                                                           BWWWWWB                  ",
            "                   BWWWWWBB                                                                       BBWWWWWB                   ",
            "                    BWWWWWWB                                                                     BWWWWWWB                    ",
            "                     BBWWWWWB                                                                   BWWWWWBB                     ",
            "                       BWWWWWBB                                                               BBWWWWWB                       ",
            "                        BWWWWWWB                                                             BWWWWWWB                        ",
            "                         BBWWWWWBB                                                         BBWWWWWBB                         ",
            "                           BWWWWWWBB                                                     BBWWWWWWB                           ",
            "                            BBWWWWWWBB                                                 BBWWWWWWBB                            ",
            "                              BWWWWWWWBB                                             BBWWWWWWWB                              ",
            "                               BBWWWWWWWBBB                                       BBBWWWWWWWBB                               ",
            "                                 BBWWWWWWWWBBB                                 BBBWWWWWWWWBB                                 ",
            "                                   BBWWWWWWWWWBBB                           BBBWWWWWWWWWBB                                   ",
            "                                     BBWWWWWWWWWWBBBBBB               BBBBBBWWWWWWWWWWBB                                     ",
            "                                       BBBWWWWWWWWWWWWWBBBBBBBBBBBBBBBWWWWWWWWWWWWWBBB                                       ",
            "                                          BBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                          ",
            "                                             BBBBWWWWWWWWWWWWWWWWWWWWWWWWWWWBBBB                                             ",
            "                                                 BBBBBBWWWWWWWWWWWWWWWBBBBBB                                                 ",
            "                                                       BBBBBBBBBBBBBBB                                                       "
        },
        {
            "                                                       BBBBB     BBBBB                                                       ",
            "                                                 BBBBBBWWWWW  ~  WWWWWBBBBBB                                                 ",
            "                                             BBBBWWWWWW---------------WWWWWWBBBB                                             ",
            "                                          BBBWWWW------WWWWW     WWWWW------WWWWBBB                                          ",
            "                                       BBBWWW----WWWWWWBBBBB     BBBBBWWWWWW----WWWBBB                                       ",
            "                                     BBWWW---WWWWBBBBBB               BBBBBBWWWW---WWWBB                                     ",
            "                                   BBWWW--WWWWBBB                           BBBWWWW--WWWBB                                   ",
            "                                 BBWW---WWWBBB                                 BBBWWW---WWBB                                 ",
            "                               BBWW--WWWBBB                                       BBBWWW--WWBB                               ",
            "                              BWW--WWWBB                                             BBWWW--WWB                              ",
            "                            BBWW-WWWBB                                                 BBWWW-WWBB                            ",
            "                           BWW--WWBB                                                     BBWW--WWB                           ",
            "                         BBWW-WWBB                                                         BBWW-WWBB                         ",
            "                        BWW--WWB                                                             BWW--WWB                        ",
            "                       BWW-WWBB                                                               BBWW-WWB                       ",
            "                     BBWW-WWB                                                                   BWW-WWBB                     ",
            "                    BWW--WWB                                                                     BWW--WWB                    ",
            "                   BWW-WWBB                                                                       BBWW-WWB                   ",
            "                  BWW-WWB                                                                           BWW-WWB                  ",
            "                 BWW-WWB                                                                             BWW-WWB                 ",
            "                BWW-WWB                                                                               BWW-WWB                ",
            "               BWW-WWB                                                                                 BWW-WWB               ",
            "               BW-WWB                                                                                   BWW-WB               ",
            "              BW-WWB                                                                                     BWW-WB              ",
            "             BWW-WB                                                                                       BW-WWB             ",
            "            BWW-WB                                                                                         BW-WWB            ",
            "            BW-WWB                                                                                         BWW-WB            ",
            "           BW-WWB                                                                                           BWW-WB           ",
            "          BWW-WB                                                                                             BW-WWB          ",
            "          BW-WB                                                                                               BW-WB          ",
            "         BW-WWB                                                                                               BWW-WB         ",
            "        BWW-WB                                                                                                 BW-WWB        ",
            "        BW-WB                                                                                                   BW-WB        ",
            "       BW-WWB                                                                                                   BWW-WB       ",
            "       BW-WB                                                                                                     BW-WB       ",
            "      BW-WWB                                                                                                     BWW-WB      ",
            "      BW-WB                                                                                                       BW-WB      ",
            "     BW-WWB                                                                                                       BWW-WB     ",
            "     BW-WB                                                                                                         BW-WB     ",
            "    BWW-WB                                                                                                         BW-WWB    ",
            "    BW-WB                                                                                                           BW-WB    ",
            "    BW-WB                                                                                                           BW-WB    ",
            "   BW-WWB                                                                                                           BWW-WB   ",
            "   BW-WB                                                                                                             BW-WB   ",
            "   BW-WB                                                                                                             BW-WB   ",
            "  BW-WWB                                                                                                             BWW-WB  ",
            "  BW-WB                                                                                                               BW-WB  ",
            "  BW-WB                                                                                                               BW-WB  ",
            "  BW-WB                                                                                                               BW-WB  ",
            " BW-WB                                                                                                                 BW-WB ",
            " BW-WB                                                                                                                 BW-WB ",
            " BW-WB                                                                                                                 BW-WB ",
            " BW-WB                                                                                                                 BW-WB ",
            " BW-WB                                                                                                                 BW-WB ",
            " BW-WB                                                                                                                 BW-WB ",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            "BW-WB                                                                                                                   BW-WB",
            " BW-WB                                                                                                                 BW-WB ",
            " BW-WB                                                                                                                 BW-WB ",
            " BW-WB                                                                                                                 BW-WB ",
            " BW-WB                                                                                                                 BW-WB ",
            " BW-WB                                                                                                                 BW-WB ",
            " BW-WB                                                                                                                 BW-WB ",
            "  BW-WB                                                                                                               BW-WB  ",
            "  BW-WB                                                                                                               BW-WB  ",
            "  BW-WB                                                                                                               BW-WB  ",
            "  BW-WWB                                                                                                             BWW-WB  ",
            "   BW-WB                                                                                                             BW-WB   ",
            "   BW-WB                                                                                                             BW-WB   ",
            "   BW-WWB                                                                                                           BWW-WB   ",
            "    BW-WB                                                                                                           BW-WB    ",
            "    BW-WB                                                                                                           BW-WB    ",
            "    BWW-WB                                                                                                         BW-WWB    ",
            "     BW-WB                                                                                                         BW-WB     ",
            "     BW-WWB                                                                                                       BWW-WB     ",
            "      BW-WB                                                                                                       BW-WB      ",
            "      BW-WWB                                                                                                     BWW-WB      ",
            "       BW-WB                                                                                                     BW-WB       ",
            "       BW-WWB                                                                                                   BWW-WB       ",
            "        BW-WB                                                                                                   BW-WB        ",
            "        BWW-WB                                                                                                 BW-WWB        ",
            "         BW-WWB                                                                                               BWW-WB         ",
            "          BW-WB                                                                                               BW-WB          ",
            "          BWW-WB                                                                                             BW-WWB          ",
            "           BW-WWB                                                                                           BWW-WB           ",
            "            BW-WWB                                                                                         BWW-WB            ",
            "            BWW-WB                                                                                         BW-WWB            ",
            "             BWW-WB                                                                                       BW-WWB             ",
            "              BW-WWB                                                                                     BWW-WB              ",
            "               BW-WWB                                                                                   BWW-WB               ",
            "               BWW-WWB                                                                                 BWW-WWB               ",
            "                BWW-WWB                                                                               BWW-WWB                ",
            "                 BWW-WWB                                                                             BWW-WWB                 ",
            "                  BWW-WWB                                                                           BWW-WWB                  ",
            "                   BWW-WWBB                                                                       BBWW-WWB                   ",
            "                    BWW--WWB                                                                     BWW--WWB                    ",
            "                     BBWW-WWB                                                                   BWW-WWBB                     ",
            "                       BWW-WWBB                                                               BBWW-WWB                       ",
            "                        BWW--WWB                                                             BWW--WWB                        ",
            "                         BBWW-WWBB                                                         BBWW-WWBB                         ",
            "                           BWW--WWBB                                                     BBWW--WWB                           ",
            "                            BBWW-WWWBB                                                 BBWWW-WWBB                            ",
            "                              BWW--WWWBB                                             BBWWW--WWB                              ",
            "                               BBWW--WWWBBB                                       BBBWWW--WWBB                               ",
            "                                 BBWW---WWWBBB                                 BBBWWW---WWBB                                 ",
            "                                   BBWWW--WWWWBBB                           BBBWWWW--WWWBB                                   ",
            "                                     BBWWW---WWWWBBBBBB               BBBBBBWWWW---WWWBB                                     ",
            "                                       BBBWWW----WWWWWWBBBBBBBBBBBBBBBWWWWWW----WWWBBB                                       ",
            "                                          BBBWWWW------WWWWWWWWWWWWWWW------WWWWBBB                                          ",
            "                                             BBBBWWWWWW---------------WWWWWWBBBB                                             ",
            "                                                 BBBBBBWWWWWWWWWWWWWWWBBBBBB                                                 ",
            "                                                       BBBBBBBBBBBBBBB                                                       "
        },
        {
            "                                                       BBBBB     BBBBB                                                       ",
            "                                                 BBBBBBWWWWW     WWWWWBBBBBB                                                 ",
            "                                             BBBBWWWWWWWWWWW     WWWWWWWWWWWBBBB                                             ",
            "                                          BBBWWWWWWWWWWWWWWW     WWWWWWWWWWWWWWWBBB                                          ",
            "                                       BBBWWWWWWWWWWWWWBBBBB     BBBBBWWWWWWWWWWWWWBBB                                       ",
            "                                     BBWWWWWWWWWWBBBBBB               BBBBBBWWWWWWWWWWBB                                     ",
            "                                   BBWWWWWWWWWBBB                           BBBWWWWWWWWWBB                                   ",
            "                                 BBWWWWWWWWBBB                                 BBBWWWWWWWWBB                                 ",
            "                               BBWWWWWWWBBB                                       BBBWWWWWWWBB                               ",
            "                              BWWWWWWWBB                                             BBWWWWWWWB                              ",
            "                            BBWWWWWWBB                                                 BBWWWWWWBB                            ",
            "                           BWWWWWWBB                                                     BBWWWWWWB                           ",
            "                         BBWWWWWBB                                                         BBWWWWWBB                         ",
            "                        BWWWWWWB                                                             BWWWWWWB                        ",
            "                       BWWWWWBB                                                               BBWWWWWB                       ",
            "                     BBWWWWWB                                                                   BWWWWWBB                     ",
            "                    BWWWWWWB                                                                     BWWWWWWB                    ",
            "                   BWWWWWBB                                                                       BBWWWWWB                   ",
            "                  BWWWWWB                                                                           BWWWWWB                  ",
            "                 BWWWWWB                                                                             BWWWWWB                 ",
            "                BWWWWWB                                                                               BWWWWWB                ",
            "               BWWWWWB                                                                                 BWWWWWB               ",
            "               BWWWWB                                                                                   BWWWWB               ",
            "              BWWWWB                                                                                     BWWWWB              ",
            "             BWWWWB                                                                                       BWWWWB             ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "           BWWWWB                                                                                           BWWWWB           ",
            "          BWWWWB                                                                                             BWWWWB          ",
            "          BWWWB                                                                                               BWWWB          ",
            "         BWWWWB                                                                                               BWWWWB         ",
            "        BWWWWB                                                                                                 BWWWWB        ",
            "        BWWWB                                                                                                   BWWWB        ",
            "       BWWWWB                                                                                                   BWWWWB       ",
            "       BWWWB                                                                                                     BWWWB       ",
            "      BWWWWB                                                                                                     BWWWWB      ",
            "      BWWWB                                                                                                       BWWWB      ",
            "     BWWWWB                                                                                                       BWWWWB     ",
            "     BWWWB                                                                                                         BWWWB     ",
            "    BWWWWB                                                                                                         BWWWWB    ",
            "    BWWWB                                                                                                           BWWWB    ",
            "    BWWWB                                                                                                           BWWWB    ",
            "   BWWWWB                                                                                                           BWWWWB   ",
            "   BWWWB                                                                                                             BWWWB   ",
            "   BWWWB                                                                                                             BWWWB   ",
            "  BWWWWB                                                                                                             BWWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWWB                                                                                                             BWWWWB  ",
            "   BWWWB                                                                                                             BWWWB   ",
            "   BWWWB                                                                                                             BWWWB   ",
            "   BWWWWB                                                                                                           BWWWWB   ",
            "    BWWWB                                                                                                           BWWWB    ",
            "    BWWWB                                                                                                           BWWWB    ",
            "    BWWWWB                                                                                                         BWWWWB    ",
            "     BWWWB                                                                                                         BWWWB     ",
            "     BWWWWB                                                                                                       BWWWWB     ",
            "      BWWWB                                                                                                       BWWWB      ",
            "      BWWWWB                                                                                                     BWWWWB      ",
            "       BWWWB                                                                                                     BWWWB       ",
            "       BWWWWB                                                                                                   BWWWWB       ",
            "        BWWWB                                                                                                   BWWWB        ",
            "        BWWWWB                                                                                                 BWWWWB        ",
            "         BWWWWB                                                                                               BWWWWB         ",
            "          BWWWB                                                                                               BWWWB          ",
            "          BWWWWB                                                                                             BWWWWB          ",
            "           BWWWWB                                                                                           BWWWWB           ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "             BWWWWB                                                                                       BWWWWB             ",
            "              BWWWWB                                                                                     BWWWWB              ",
            "               BWWWWB                                                                                   BWWWWB               ",
            "               BWWWWWB                                                                                 BWWWWWB               ",
            "                BWWWWWB                                                                               BWWWWWB                ",
            "                 BWWWWWB                                                                             BWWWWWB                 ",
            "                  BWWWWWB                                                                           BWWWWWB                  ",
            "                   BWWWWWBB                                                                       BBWWWWWB                   ",
            "                    BWWWWWWB                                                                     BWWWWWWB                    ",
            "                     BBWWWWWB                                                                   BWWWWWBB                     ",
            "                       BWWWWWBB                                                               BBWWWWWB                       ",
            "                        BWWWWWWB                                                             BWWWWWWB                        ",
            "                         BBWWWWWBB                                                         BBWWWWWBB                         ",
            "                           BWWWWWWBB                                                     BBWWWWWWB                           ",
            "                            BBWWWWWWBB                                                 BBWWWWWWBB                            ",
            "                              BWWWWWWWBB                                             BBWWWWWWWB                              ",
            "                               BBWWWWWWWBBB                                       BBBWWWWWWWBB                               ",
            "                                 BBWWWWWWWWBBB                                 BBBWWWWWWWWBB                                 ",
            "                                   BBWWWWWWWWWBBB                           BBBWWWWWWWWWBB                                   ",
            "                                     BBWWWWWWWWWWBBBBBB               BBBBBBWWWWWWWWWWBB                                     ",
            "                                       BBBWWWWWWWWWWWWWBBBBBBBBBBBBBBBWWWWWWWWWWWWWBBB                                       ",
            "                                          BBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                          ",
            "                                             BBBBWWWWWWWWWWWWWWWWWWWWWWWWWWWBBBB                                             ",
            "                                                 BBBBBBWWWWWWWWWWWWWWWBBBBBB                                                 ",
            "                                                       BBBBBBBBBBBBBBB                                                       "
        },
        {
            "                                                                                                                             ",
            "                                                       BBBBB     BBBBB                                                       ",
            "                                                 BBBBBBBBBBB     BBBBBBBBBBB                                                 ",
            "                                             BBBBBBBBBBBBBBB     BBBBBBBBBBBBBBB                                             ",
            "                                          BBBBBBBBBBBBB               BBBBBBBBBBBBB                                          ",
            "                                       BBBBBBBBBB                           BBBBBBBBBB                                       ",
            "                                     BBBBBBBBB                                 BBBBBBBBB                                     ",
            "                                   BBBBBBBB                                       BBBBBBBB                                   ",
            "                                 BBBBBBB                                             BBBBBBB                                 ",
            "                               BBBBBBB                                                 BBBBBBB                               ",
            "                              BBBBBB                                                     BBBBBB                              ",
            "                            BBBBBB                                                         BBBBBB                            ",
            "                           BBBBB                                                             BBBBB                           ",
            "                         BBBBBB                                                               BBBBBB                         ",
            "                        BBBBB                                                                   BBBBB                        ",
            "                       BBBBB                                                                     BBBBB                       ",
            "                     BBBBBB                                                                       BBBBBB                     ",
            "                    BBBBB                                                                           BBBBB                    ",
            "                   BBBBB                                                                             BBBBB                   ",
            "                  BBBBB                                                                               BBBBB                  ",
            "                 BBBBB                                                                                 BBBBB                 ",
            "                BBBBB                                                                                   BBBBB                ",
            "                BBBB                                                                                     BBBB                ",
            "               BBBB                                                                                       BBBB               ",
            "              BBBB                                                                                         BBBB              ",
            "             BBBB                                                                                           BBBB             ",
            "             BBBB                                                                                           BBBB             ",
            "            BBBB                                                                                             BBBB            ",
            "           BBBB                                                                                               BBBB           ",
            "           BBB                                                                                                 BBB           ",
            "          BBBB                                                                                                 BBBB          ",
            "         BBBB                                                                                                   BBBB         ",
            "         BBB                                                                                                     BBB         ",
            "        BBBB                                                                                                     BBBB        ",
            "        BBB                                                                                                       BBB        ",
            "       BBBB                                                                                                       BBBB       ",
            "       BBB                                                                                                         BBB       ",
            "      BBBB                                                                                                         BBBB      ",
            "      BBB                                                                                                           BBB      ",
            "     BBBB                                                                                                           BBBB     ",
            "     BBB                                                                                                             BBB     ",
            "     BBB                                                                                                             BBB     ",
            "    BBBB                                                                                                             BBBB    ",
            "    BBB                                                                                                               BBB    ",
            "    BBB                                                                                                               BBB    ",
            "   BBBB                                                                                                               BBBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBBB                                                                                                               BBBB   ",
            "    BBB                                                                                                               BBB    ",
            "    BBB                                                                                                               BBB    ",
            "    BBBB                                                                                                             BBBB    ",
            "     BBB                                                                                                             BBB     ",
            "     BBB                                                                                                             BBB     ",
            "     BBBB                                                                                                           BBBB     ",
            "      BBB                                                                                                           BBB      ",
            "      BBBB                                                                                                         BBBB      ",
            "       BBB                                                                                                         BBB       ",
            "       BBBB                                                                                                       BBBB       ",
            "        BBB                                                                                                       BBB        ",
            "        BBBB                                                                                                     BBBB        ",
            "         BBB                                                                                                     BBB         ",
            "         BBBB                                                                                                   BBBB         ",
            "          BBBB                                                                                                 BBBB          ",
            "           BBB                                                                                                 BBB           ",
            "           BBBB                                                                                               BBBB           ",
            "            BBBB                                                                                             BBBB            ",
            "             BBBB                                                                                           BBBB             ",
            "             BBBB                                                                                           BBBB             ",
            "              BBBB                                                                                         BBBB              ",
            "               BBBB                                                                                       BBBB               ",
            "                BBBB                                                                                     BBBB                ",
            "                BBBBB                                                                                   BBBBB                ",
            "                 BBBBB                                                                                 BBBBB                 ",
            "                  BBBBB                                                                               BBBBB                  ",
            "                   BBBBB                                                                             BBBBB                   ",
            "                    BBBBB                                                                           BBBBB                    ",
            "                     BBBBBB                                                                       BBBBBB                     ",
            "                       BBBBB                                                                     BBBBB                       ",
            "                        BBBBB                                                                   BBBBB                        ",
            "                         BBBBBB                                                               BBBBBB                         ",
            "                           BBBBB                                                             BBBBB                           ",
            "                            BBBBBB                                                         BBBBBB                            ",
            "                              BBBBBB                                                     BBBBBB                              ",
            "                               BBBBBBB                                                 BBBBBBB                               ",
            "                                 BBBBBBB                                             BBBBBBB                                 ",
            "                                   BBBBBBBB                                       BBBBBBBB                                   ",
            "                                     BBBBBBBBB                                 BBBBBBBBB                                     ",
            "                                       BBBBBBBBBB                           BBBBBBBBBB                                       ",
            "                                          BBBBBBBBBBBBB               BBBBBBBBBBBBB                                          ",
            "                                             BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                             ",
            "                                                 BBBBBBBBBBBBBBBBBBBBBBBBBBB                                                 ",
            "                                                       BBBBBBBBBBBBBBB                                                       ",
            "                                                                                                                             "
        }
    });
}
