package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_8 {
    public static final String[][] CYCLOTRON_SHAPE_8_IDENTITY = transpose(new String[][] {
        {
            "                                                                                                                   ",
            "                                                  BBBBB     BBBBB                                                  ",
            "                                             BBBBBBBBBB     BBBBBBBBBB                                             ",
            "                                         BBBBBBBBBBBBBB     BBBBBBBBBBBBBB                                         ",
            "                                      BBBBBBBBBBBB               BBBBBBBBBBBB                                      ",
            "                                   BBBBBBBBBB                         BBBBBBBBBB                                   ",
            "                                 BBBBBBBB                                 BBBBBBBB                                 ",
            "                               BBBBBBBB                                     BBBBBBBB                               ",
            "                             BBBBBBB                                           BBBBBBB                             ",
            "                            BBBBBB                                               BBBBBB                            ",
            "                          BBBBBB                                                   BBBBBB                          ",
            "                         BBBBB                                                       BBBBB                         ",
            "                       BBBBBB                                                         BBBBBB                       ",
            "                      BBBBB                                                             BBBBB                      ",
            "                     BBBBB                                                               BBBBB                     ",
            "                    BBBBB                                                                 BBBBB                    ",
            "                  BBBBB                                                                     BBBBB                  ",
            "                 BBBBB                                                                       BBBBB                 ",
            "                BBBBB                                                                         BBBBB                ",
            "                BBBB                                                                           BBBB                ",
            "               BBBB                                                                             BBBB               ",
            "              BBBB                                                                               BBBB              ",
            "             BBBB                                                                                 BBBB             ",
            "            BBBB                                                                                   BBBB            ",
            "            BBBB                                                                                   BBBB            ",
            "           BBBB                                                                                     BBBB           ",
            "          BBBB                                                                                       BBBB          ",
            "          BBB                                                                                         BBB          ",
            "         BBBB                                                                                         BBBB         ",
            "        BBBB                                                                                           BBBB        ",
            "        BBB                                                                                             BBB        ",
            "       BBBB                                                                                             BBBB       ",
            "       BBB                                                                                               BBB       ",
            "      BBBB                                                                                               BBBB      ",
            "      BBB                                                                                                 BBB      ",
            "     BBBB                                                                                                 BBBB     ",
            "     BBB                                                                                                   BBB     ",
            "     BBB                                                                                                   BBB     ",
            "    BBBB                                                                                                   BBBB    ",
            "    BBB                                                                                                     BBB    ",
            "    BBB                                                                                                     BBB    ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "    BBB                                                                                                     BBB    ",
            "    BBB                                                                                                     BBB    ",
            "    BBBB                                                                                                   BBBB    ",
            "     BBB                                                                                                   BBB     ",
            "     BBB                                                                                                   BBB     ",
            "     BBBB                                                                                                 BBBB     ",
            "      BBB                                                                                                 BBB      ",
            "      BBBB                                                                                               BBBB      ",
            "       BBB                                                                                               BBB       ",
            "       BBBB                                                                                             BBBB       ",
            "        BBB                                                                                             BBB        ",
            "        BBBB                                                                                           BBBB        ",
            "         BBBB                                                                                         BBBB         ",
            "          BBB                                                                                         BBB          ",
            "          BBBB                                                                                       BBBB          ",
            "           BBBB                                                                                     BBBB           ",
            "            BBBB                                                                                   BBBB            ",
            "            BBBB                                                                                   BBBB            ",
            "             BBBB                                                                                 BBBB             ",
            "              BBBB                                                                               BBBB              ",
            "               BBBB                                                                             BBBB               ",
            "                BBBB                                                                           BBBB                ",
            "                BBBBB                                                                         BBBBB                ",
            "                 BBBBB                                                                       BBBBB                 ",
            "                  BBBBB                                                                     BBBBB                  ",
            "                    BBBBB                                                                 BBBBB                    ",
            "                     BBBBB                                                               BBBBB                     ",
            "                      BBBBB                                                             BBBBB                      ",
            "                       BBBBBB                                                         BBBBBB                       ",
            "                         BBBBB                                                       BBBBB                         ",
            "                          BBBBBB                                                   BBBBBB                          ",
            "                            BBBBBB                                               BBBBBB                            ",
            "                             BBBBBBB                                           BBBBBBB                             ",
            "                               BBBBBBBB                                     BBBBBBBB                               ",
            "                                 BBBBBBBB                                 BBBBBBBB                                 ",
            "                                   BBBBBBBBBB                         BBBBBBBBBB                                   ",
            "                                      BBBBBBBBBBBB               BBBBBBBBBBBB                                      ",
            "                                         BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                         ",
            "                                             BBBBBBBBBBBBBBBBBBBBBBBBB                                             ",
            "                                                  BBBBBBBBBBBBBBB                                                  ",
            "                                                                                                                   "
        },
        {
            "                                                  BBBBB     BBBBB                                                  ",
            "                                             BBBBBWWWWW     WWWWWBBBBB                                             ",
            "                                         BBBBWWWWWWWWWW     WWWWWWWWWWBBBB                                         ",
            "                                      BBBWWWWWWWWWWWWWW     WWWWWWWWWWWWWWBBB                                      ",
            "                                   BBBWWWWWWWWWWWWBBBBB     BBBBBWWWWWWWWWWWWBBB                                   ",
            "                                 BBWWWWWWWWWWBBBBB               BBBBBWWWWWWWWWWBB                                 ",
            "                               BBWWWWWWWWBBBB                         BBBBWWWWWWWWBB                               ",
            "                             BBWWWWWWWWBB                                 BBWWWWWWWWBB                             ",
            "                            BWWWWWWWBBB                                     BBBWWWWWWWB                            ",
            "                          BBWWWWWWBB                                           BBWWWWWWBB                          ",
            "                         BWWWWWWBB                                               BBWWWWWWB                         ",
            "                       BBWWWWWBB                                                   BBWWWWWBB                       ",
            "                      BWWWWWWB                                                       BWWWWWWB                      ",
            "                     BWWWWWBB                                                         BBWWWWWB                     ",
            "                    BWWWWWB                                                             BWWWWWB                    ",
            "                  BBWWWWWB                                                               BWWWWWBB                  ",
            "                 BWWWWWBB                                                                 BBWWWWWB                 ",
            "                BWWWWWB                                                                     BWWWWWB                ",
            "               BWWWWWB                                                                       BWWWWWB               ",
            "               BWWWWB                                                                         BWWWWB               ",
            "              BWWWWB                                                                           BWWWWB              ",
            "             BWWWWB                                                                             BWWWWB             ",
            "            BWWWWB                                                                               BWWWWB            ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "          BWWWWB                                                                                   BWWWWB          ",
            "         BWWWWB                                                                                     BWWWWB         ",
            "         BWWWB                                                                                       BWWWB         ",
            "        BWWWWB                                                                                       BWWWWB        ",
            "       BWWWWB                                                                                         BWWWWB       ",
            "       BWWWB                                                                                           BWWWB       ",
            "      BWWWWB                                                                                           BWWWWB      ",
            "      BWWWB                                                                                             BWWWB      ",
            "     BWWWWB                                                                                             BWWWWB     ",
            "     BWWWB                                                                                               BWWWB     ",
            "    BWWWWB                                                                                               BWWWWB    ",
            "    BWWWB                                                                                                 BWWWB    ",
            "    BWWWB                                                                                                 BWWWB    ",
            "   BWWWWB                                                                                                 BWWWWB   ",
            "   BWWWB                                                                                                   BWWWB   ",
            "   BWWWB                                                                                                   BWWWB   ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "   BWWWB                                                                                                   BWWWB   ",
            "   BWWWB                                                                                                   BWWWB   ",
            "   BWWWWB                                                                                                 BWWWWB   ",
            "    BWWWB                                                                                                 BWWWB    ",
            "    BWWWB                                                                                                 BWWWB    ",
            "    BWWWWB                                                                                               BWWWWB    ",
            "     BWWWB                                                                                               BWWWB     ",
            "     BWWWWB                                                                                             BWWWWB     ",
            "      BWWWB                                                                                             BWWWB      ",
            "      BWWWWB                                                                                           BWWWWB      ",
            "       BWWWB                                                                                           BWWWB       ",
            "       BWWWWB                                                                                         BWWWWB       ",
            "        BWWWWB                                                                                       BWWWWB        ",
            "         BWWWB                                                                                       BWWWB         ",
            "         BWWWWB                                                                                     BWWWWB         ",
            "          BWWWWB                                                                                   BWWWWB          ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "            BWWWWB                                                                               BWWWWB            ",
            "             BWWWWB                                                                             BWWWWB             ",
            "              BWWWWB                                                                           BWWWWB              ",
            "               BWWWWB                                                                         BWWWWB               ",
            "               BWWWWWB                                                                       BWWWWWB               ",
            "                BWWWWWB                                                                     BWWWWWB                ",
            "                 BWWWWWBB                                                                 BBWWWWWB                 ",
            "                  BBWWWWWB                                                               BWWWWWBB                  ",
            "                    BWWWWWB                                                             BWWWWWB                    ",
            "                     BWWWWWBB                                                         BBWWWWWB                     ",
            "                      BWWWWWWB                                                       BWWWWWWB                      ",
            "                       BBWWWWWBB                                                   BBWWWWWBB                       ",
            "                         BWWWWWWBB                                               BBWWWWWWB                         ",
            "                          BBWWWWWWBB                                           BBWWWWWWBB                          ",
            "                            BWWWWWWWBBB                                     BBBWWWWWWWB                            ",
            "                             BBWWWWWWWWBB                                 BBWWWWWWWWBB                             ",
            "                               BBWWWWWWWWBBBB                         BBBBWWWWWWWWBB                               ",
            "                                 BBWWWWWWWWWWBBBBB               BBBBBWWWWWWWWWWBB                                 ",
            "                                   BBBWWWWWWWWWWWWBBBBBBBBBBBBBBBWWWWWWWWWWWWBBB                                   ",
            "                                      BBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                      ",
            "                                         BBBBWWWWWWWWWWWWWWWWWWWWWWWWWBBBB                                         ",
            "                                             BBBBBWWWWWWWWWWWWWWWBBBBB                                             ",
            "                                                  BBBBBBBBBBBBBBB                                                  "
        },
        {
            "                                                  BBBBB     BBBBB                                                  ",
            "                                             BBBBBWWWWW  ~  WWWWWBBBBB                                             ",
            "                                         BBBBWWWWW---------------WWWWWBBBB                                         ",
            "                                      BBBWWWW-----WWWWW     WWWWW-----WWWWBBB                                      ",
            "                                   BBBWWW----WWWWWBBBBB     BBBBBWWWWW----WWWBBB                                   ",
            "                                 BBWWW---WWWWBBBBB               BBBBBWWWW---WWWBB                                 ",
            "                               BBWWW--WWWBBBB                         BBBBWWW--WWWBB                               ",
            "                             BBWWW--WWWBB                                 BBWWW--WWWBB                             ",
            "                            BWWW--WWBBB                                     BBBWW--WWWB                            ",
            "                          BBWW--WWBB                                           BBWW--WWBB                          ",
            "                         BWW--WWBB                                               BBWW--WWB                         ",
            "                       BBWW-WWBB                                                   BBWW-WWBB                       ",
            "                      BWW--WWB                                                       BWW--WWB                      ",
            "                     BWW-WWBB                                                         BBWW-WWB                     ",
            "                    BWW-WWB                                                             BWW-WWB                    ",
            "                  BBW--WWB                                                               BWW--WBB                  ",
            "                 BWW-WWBB                                                                 BBWW-WWB                 ",
            "                BWW-WWB                                                                     BWW-WWB                ",
            "               BWW-WWB                                                                       BWW-WWB               ",
            "               BW-WWB                                                                         BWW-WB               ",
            "              BW-WWB                                                                           BWW-WB              ",
            "             BW-WWB                                                                             BWW-WB             ",
            "            BWW-WB                                                                               BW-WWB            ",
            "           BWW-WB                                                                                 BW-WWB           ",
            "           BW-WWB                                                                                 BWW-WB           ",
            "          BW-WWB                                                                                   BWW-WB          ",
            "         BWW-WB                                                                                     BW-WWB         ",
            "         BW-WB                                                                                       BW-WB         ",
            "        BW-WWB                                                                                       BWW-WB        ",
            "       BWW-WB                                                                                         BW-WWB       ",
            "       BW-WB                                                                                           BW-WB       ",
            "      BWW-WB                                                                                           BW-WWB      ",
            "      BW-WB                                                                                             BW-WB      ",
            "     BWW-WB                                                                                             BW-WWB     ",
            "     BW-WB                                                                                               BW-WB     ",
            "    BWW-WB                                                                                               BW-WWB    ",
            "    BW-WB                                                                                                 BW-WB    ",
            "    BW-WB                                                                                                 BW-WB    ",
            "   BW-WWB                                                                                                 BWW-WB   ",
            "   BW-WB                                                                                                   BW-WB   ",
            "   BW-WB                                                                                                   BW-WB   ",
            "  BW-WB                                                                                                     BW-WB  ",
            "  BW-WB                                                                                                     BW-WB  ",
            "  BW-WB                                                                                                     BW-WB  ",
            "  BW-WB                                                                                                     BW-WB  ",
            " BW-WB                                                                                                       BW-WB ",
            " BW-WB                                                                                                       BW-WB ",
            " BW-WB                                                                                                       BW-WB ",
            " BW-WB                                                                                                       BW-WB ",
            " BW-WB                                                                                                       BW-WB ",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            "BW-WB                                                                                                         BW-WB",
            " BW-WB                                                                                                       BW-WB ",
            " BW-WB                                                                                                       BW-WB ",
            " BW-WB                                                                                                       BW-WB ",
            " BW-WB                                                                                                       BW-WB ",
            " BW-WB                                                                                                       BW-WB ",
            "  BW-WB                                                                                                     BW-WB  ",
            "  BW-WB                                                                                                     BW-WB  ",
            "  BW-WB                                                                                                     BW-WB  ",
            "  BW-WB                                                                                                     BW-WB  ",
            "   BW-WB                                                                                                   BW-WB   ",
            "   BW-WB                                                                                                   BW-WB   ",
            "   BW-WWB                                                                                                 BWW-WB   ",
            "    BW-WB                                                                                                 BW-WB    ",
            "    BW-WB                                                                                                 BW-WB    ",
            "    BWW-WB                                                                                               BW-WWB    ",
            "     BW-WB                                                                                               BW-WB     ",
            "     BWW-WB                                                                                             BW-WWB     ",
            "      BW-WB                                                                                             BW-WB      ",
            "      BWW-WB                                                                                           BW-WWB      ",
            "       BW-WB                                                                                           BW-WB       ",
            "       BWW-WB                                                                                         BW-WWB       ",
            "        BW-WWB                                                                                       BWW-WB        ",
            "         BW-WB                                                                                       BW-WB         ",
            "         BWW-WB                                                                                     BW-WWB         ",
            "          BW-WWB                                                                                   BWW-WB          ",
            "           BW-WWB                                                                                 BWW-WB           ",
            "           BWW-WB                                                                                 BW-WWB           ",
            "            BWW-WB                                                                               BW-WWB            ",
            "             BW-WWB                                                                             BWW-WB             ",
            "              BW-WWB                                                                           BWW-WB              ",
            "               BW-WWB                                                                         BWW-WB               ",
            "               BWW-WWB                                                                       BWW-WWB               ",
            "                BWW-WWB                                                                     BWW-WWB                ",
            "                 BWW-WWBB                                                                 BBWW-WWB                 ",
            "                  BBW--WWB                                                               BWW--WBB                  ",
            "                    BWW-WWB                                                             BWW-WWB                    ",
            "                     BWW-WWBB                                                         BBWW-WWB                     ",
            "                      BWW--WWB                                                       BWW--WWB                      ",
            "                       BBWW-WWBB                                                   BBWW-WWBB                       ",
            "                         BWW--WWBB                                               BBWW--WWB                         ",
            "                          BBWW--WWBB                                           BBWW--WWBB                          ",
            "                            BWWW--WWBBB                                     BBBWW--WWWB                            ",
            "                             BBWWW--WWWBB                                 BBWWW--WWWBB                             ",
            "                               BBWWW--WWWBBBB                         BBBBWWW--WWWBB                               ",
            "                                 BBWWW---WWWWBBBBB               BBBBBWWWW---WWWBB                                 ",
            "                                   BBBWWW----WWWWWBBBBBBBBBBBBBBBWWWWW----WWWBBB                                   ",
            "                                      BBBWWWW-----WWWWWWWWWWWWWWW-----WWWWBBB                                      ",
            "                                         BBBBWWWWW---------------WWWWWBBBB                                         ",
            "                                             BBBBBWWWWWWWWWWWWWWWBBBBB                                             ",
            "                                                  BBBBBBBBBBBBBBB                                                  "
        },
        {
            "                                                  BBBBB     BBBBB                                                  ",
            "                                             BBBBBWWWWW     WWWWWBBBBB                                             ",
            "                                         BBBBWWWWWWWWWW     WWWWWWWWWWBBBB                                         ",
            "                                      BBBWWWWWWWWWWWWWW     WWWWWWWWWWWWWWBBB                                      ",
            "                                   BBBWWWWWWWWWWWWBBBBB     BBBBBWWWWWWWWWWWWBBB                                   ",
            "                                 BBWWWWWWWWWWBBBBB               BBBBBWWWWWWWWWWBB                                 ",
            "                               BBWWWWWWWWBBBB                         BBBBWWWWWWWWBB                               ",
            "                             BBWWWWWWWWBB                                 BBWWWWWWWWBB                             ",
            "                            BWWWWWWWBBB                                     BBBWWWWWWWB                            ",
            "                          BBWWWWWWBB                                           BBWWWWWWBB                          ",
            "                         BWWWWWWBB                                               BBWWWWWWB                         ",
            "                       BBWWWWWBB                                                   BBWWWWWBB                       ",
            "                      BWWWWWWB                                                       BWWWWWWB                      ",
            "                     BWWWWWBB                                                         BBWWWWWB                     ",
            "                    BWWWWWB                                                             BWWWWWB                    ",
            "                  BBWWWWWB                                                               BWWWWWBB                  ",
            "                 BWWWWWBB                                                                 BBWWWWWB                 ",
            "                BWWWWWB                                                                     BWWWWWB                ",
            "               BWWWWWB                                                                       BWWWWWB               ",
            "               BWWWWB                                                                         BWWWWB               ",
            "              BWWWWB                                                                           BWWWWB              ",
            "             BWWWWB                                                                             BWWWWB             ",
            "            BWWWWB                                                                               BWWWWB            ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "          BWWWWB                                                                                   BWWWWB          ",
            "         BWWWWB                                                                                     BWWWWB         ",
            "         BWWWB                                                                                       BWWWB         ",
            "        BWWWWB                                                                                       BWWWWB        ",
            "       BWWWWB                                                                                         BWWWWB       ",
            "       BWWWB                                                                                           BWWWB       ",
            "      BWWWWB                                                                                           BWWWWB      ",
            "      BWWWB                                                                                             BWWWB      ",
            "     BWWWWB                                                                                             BWWWWB     ",
            "     BWWWB                                                                                               BWWWB     ",
            "    BWWWWB                                                                                               BWWWWB    ",
            "    BWWWB                                                                                                 BWWWB    ",
            "    BWWWB                                                                                                 BWWWB    ",
            "   BWWWWB                                                                                                 BWWWWB   ",
            "   BWWWB                                                                                                   BWWWB   ",
            "   BWWWB                                                                                                   BWWWB   ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            "BWWWB                                                                                                         BWWWB",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            " BWWWB                                                                                                       BWWWB ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "  BWWWB                                                                                                     BWWWB  ",
            "   BWWWB                                                                                                   BWWWB   ",
            "   BWWWB                                                                                                   BWWWB   ",
            "   BWWWWB                                                                                                 BWWWWB   ",
            "    BWWWB                                                                                                 BWWWB    ",
            "    BWWWB                                                                                                 BWWWB    ",
            "    BWWWWB                                                                                               BWWWWB    ",
            "     BWWWB                                                                                               BWWWB     ",
            "     BWWWWB                                                                                             BWWWWB     ",
            "      BWWWB                                                                                             BWWWB      ",
            "      BWWWWB                                                                                           BWWWWB      ",
            "       BWWWB                                                                                           BWWWB       ",
            "       BWWWWB                                                                                         BWWWWB       ",
            "        BWWWWB                                                                                       BWWWWB        ",
            "         BWWWB                                                                                       BWWWB         ",
            "         BWWWWB                                                                                     BWWWWB         ",
            "          BWWWWB                                                                                   BWWWWB          ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "           BWWWWB                                                                                 BWWWWB           ",
            "            BWWWWB                                                                               BWWWWB            ",
            "             BWWWWB                                                                             BWWWWB             ",
            "              BWWWWB                                                                           BWWWWB              ",
            "               BWWWWB                                                                         BWWWWB               ",
            "               BWWWWWB                                                                       BWWWWWB               ",
            "                BWWWWWB                                                                     BWWWWWB                ",
            "                 BWWWWWBB                                                                 BBWWWWWB                 ",
            "                  BBWWWWWB                                                               BWWWWWBB                  ",
            "                    BWWWWWB                                                             BWWWWWB                    ",
            "                     BWWWWWBB                                                         BBWWWWWB                     ",
            "                      BWWWWWWB                                                       BWWWWWWB                      ",
            "                       BBWWWWWBB                                                   BBWWWWWBB                       ",
            "                         BWWWWWWBB                                               BBWWWWWWB                         ",
            "                          BBWWWWWWBB                                           BBWWWWWWBB                          ",
            "                            BWWWWWWWBBB                                     BBBWWWWWWWB                            ",
            "                             BBWWWWWWWWBB                                 BBWWWWWWWWBB                             ",
            "                               BBWWWWWWWWBBBB                         BBBBWWWWWWWWBB                               ",
            "                                 BBWWWWWWWWWWBBBBB               BBBBBWWWWWWWWWWBB                                 ",
            "                                   BBBWWWWWWWWWWWWBBBBBBBBBBBBBBBWWWWWWWWWWWWBBB                                   ",
            "                                      BBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                      ",
            "                                         BBBBWWWWWWWWWWWWWWWWWWWWWWWWWBBBB                                         ",
            "                                             BBBBBWWWWWWWWWWWWWWWBBBBB                                             ",
            "                                                  BBBBBBBBBBBBBBB                                                  "
        },
        {
            "                                                                                                                   ",
            "                                                  BBBBB     BBBBB                                                  ",
            "                                             BBBBBBBBBB     BBBBBBBBBB                                             ",
            "                                         BBBBBBBBBBBBBB     BBBBBBBBBBBBBB                                         ",
            "                                      BBBBBBBBBBBB               BBBBBBBBBBBB                                      ",
            "                                   BBBBBBBBBB                         BBBBBBBBBB                                   ",
            "                                 BBBBBBBB                                 BBBBBBBB                                 ",
            "                               BBBBBBBB                                     BBBBBBBB                               ",
            "                             BBBBBBB                                           BBBBBBB                             ",
            "                            BBBBBB                                               BBBBBB                            ",
            "                          BBBBBB                                                   BBBBBB                          ",
            "                         BBBBB                                                       BBBBB                         ",
            "                       BBBBBB                                                         BBBBBB                       ",
            "                      BBBBB                                                             BBBBB                      ",
            "                     BBBBB                                                               BBBBB                     ",
            "                    BBBBB                                                                 BBBBB                    ",
            "                  BBBBB                                                                     BBBBB                  ",
            "                 BBBBB                                                                       BBBBB                 ",
            "                BBBBB                                                                         BBBBB                ",
            "                BBBB                                                                           BBBB                ",
            "               BBBB                                                                             BBBB               ",
            "              BBBB                                                                               BBBB              ",
            "             BBBB                                                                                 BBBB             ",
            "            BBBB                                                                                   BBBB            ",
            "            BBBB                                                                                   BBBB            ",
            "           BBBB                                                                                     BBBB           ",
            "          BBBB                                                                                       BBBB          ",
            "          BBB                                                                                         BBB          ",
            "         BBBB                                                                                         BBBB         ",
            "        BBBB                                                                                           BBBB        ",
            "        BBB                                                                                             BBB        ",
            "       BBBB                                                                                             BBBB       ",
            "       BBB                                                                                               BBB       ",
            "      BBBB                                                                                               BBBB      ",
            "      BBB                                                                                                 BBB      ",
            "     BBBB                                                                                                 BBBB     ",
            "     BBB                                                                                                   BBB     ",
            "     BBB                                                                                                   BBB     ",
            "    BBBB                                                                                                   BBBB    ",
            "    BBB                                                                                                     BBB    ",
            "    BBB                                                                                                     BBB    ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            " BBB                                                                                                           BBB ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "  BBB                                                                                                         BBB  ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "   BBB                                                                                                       BBB   ",
            "    BBB                                                                                                     BBB    ",
            "    BBB                                                                                                     BBB    ",
            "    BBBB                                                                                                   BBBB    ",
            "     BBB                                                                                                   BBB     ",
            "     BBB                                                                                                   BBB     ",
            "     BBBB                                                                                                 BBBB     ",
            "      BBB                                                                                                 BBB      ",
            "      BBBB                                                                                               BBBB      ",
            "       BBB                                                                                               BBB       ",
            "       BBBB                                                                                             BBBB       ",
            "        BBB                                                                                             BBB        ",
            "        BBBB                                                                                           BBBB        ",
            "         BBBB                                                                                         BBBB         ",
            "          BBB                                                                                         BBB          ",
            "          BBBB                                                                                       BBBB          ",
            "           BBBB                                                                                     BBBB           ",
            "            BBBB                                                                                   BBBB            ",
            "            BBBB                                                                                   BBBB            ",
            "             BBBB                                                                                 BBBB             ",
            "              BBBB                                                                               BBBB              ",
            "               BBBB                                                                             BBBB               ",
            "                BBBB                                                                           BBBB                ",
            "                BBBBB                                                                         BBBBB                ",
            "                 BBBBB                                                                       BBBBB                 ",
            "                  BBBBB                                                                     BBBBB                  ",
            "                    BBBBB                                                                 BBBBB                    ",
            "                     BBBBB                                                               BBBBB                     ",
            "                      BBBBB                                                             BBBBB                      ",
            "                       BBBBBB                                                         BBBBBB                       ",
            "                         BBBBB                                                       BBBBB                         ",
            "                          BBBBBB                                                   BBBBBB                          ",
            "                            BBBBBB                                               BBBBBB                            ",
            "                             BBBBBBB                                           BBBBBBB                             ",
            "                               BBBBBBBB                                     BBBBBBBB                               ",
            "                                 BBBBBBBB                                 BBBBBBBB                                 ",
            "                                   BBBBBBBBBB                         BBBBBBBBBB                                   ",
            "                                      BBBBBBBBBBBB               BBBBBBBBBBBB                                      ",
            "                                         BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                         ",
            "                                             BBBBBBBBBBBBBBBBBBBBBBBBB                                             ",
            "                                                  BBBBBBBBBBBBBBB                                                  ",
            "                                                                                                                   "
        }
    });
}
