package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_0 {
    public static final String[][] CYCLOTRON_SHAPE_0_IDENTITY = transpose(new String[][] {
        {
            "                                   ",
            "             BB     BB             ",
            "           BBBB     BBBB           ",
            "         BBBBBB     BBBBBB         ",
            "       BBBBBBB       BBBBBBB       ",
            "      BBBBB             BBBBB      ",
            "     BBBBB               BBBBB     ",
            "    BBBBB                 BBBBB    ",
            "    BBBB                   BBBB    ",
            "   BBBB                     BBBB   ",
            "   BBB                       BBB   ",
            "  BBB                         BBB  ",
            "  BBB                         BBB  ",
            " BBBB                         BBBB ",
            " BBB                           BBB ",
            " BBB                           BBB ",
            " BBB                           BBB ",
            " BBB                           BBB ",
            " BBB                           BBB ",
            " BBB                           BBB ",
            " BBB                           BBB ",
            " BBBB                         BBBB ",
            "  BBB                         BBB  ",
            "  BBB                         BBB  ",
            "   BBB                       BBB   ",
            "   BBBB                     BBBB   ",
            "    BBBB                   BBBB    ",
            "    BBBBB                 BBBBB    ",
            "     BBBBB               BBBBB     ",
            "      BBBBB             BBBBB      ",
            "       BBBBBBB       BBBBBBB       ",
            "         BBBBBBBBBBBBBBBBB         ",
            "           BBBBBBBBBBBBB           ",
            "             BBBBBBBBB             ",
            "                                   "
        },
        {
            "             BB     BB             ",
            "           BBWW     WWBB           ",
            "         BBWWWW     WWWWBB         ",
            "       BBWWWWWW     WWWWWWBB       ",
            "      BWWWWWWWB     BWWWWWWWB      ",
            "     BWWWWWBBB       BBBWWWWWB     ",
            "    BWWWWWB             BWWWWWB    ",
            "   BWWWWWB               BWWWWWB   ",
            "   BWWWWB                 BWWWWB   ",
            "  BWWWWB                   BWWWWB  ",
            "  BWWWB                     BWWWB  ",
            " BWWWB                       BWWWB ",
            " BWWWB                       BWWWB ",
            "BWWWWB                       BWWWWB",
            "BWWWB                         BWWWB",
            "BWWWB                         BWWWB",
            "BWWWB                         BWWWB",
            "BWWWB                         BWWWB",
            "BWWWB                         BWWWB",
            "BWWWB                         BWWWB",
            "BWWWB                         BWWWB",
            "BWWWWB                       BWWWWB",
            " BWWWB                       BWWWB ",
            " BWWWB                       BWWWB ",
            "  BWWWB                     BWWWB  ",
            "  BWWWWB                   BWWWWB  ",
            "   BWWWWB                 BWWWWB   ",
            "   BWWWWWB               BWWWWWB   ",
            "    BWWWWWB             BWWWWWB    ",
            "     BWWWWWBBB       BBBWWWWWB     ",
            "      BWWWWWWWBBBBBBBWWWWWWWB      ",
            "       BBWWWWWWWWWWWWWWWWWBB       ",
            "         BBWWWWWWWWWWWWWBB         ",
            "           BBWWWWWWWWWBB           ",
            "             BBBBBBBBB             "
        },
        {
            "             BB     BB             ",
            "           BBWW  ~  WWBB           ",
            "         BBWWW-------WWWBB         ",
            "       BBWW---W     W---WWBB       ",
            "      BWW--WWWB     BWWW--WWB      ",
            "     BWW-WWBBB       BBBWW-WWB     ",
            "    BWW-WWB             BWW-WWB    ",
            "   BWW-WWB               BWW-WWB   ",
            "   BW-WWB                 BWW-WB   ",
            "  BW-WWB                   BWW-WB  ",
            "  BW-WB                     BW-WB  ",
            " BW-WB                       BW-WB ",
            " BW-WB                       BW-WB ",
            "BWW-WB                       BW-WWB",
            "BW-WB                         BW-WB",
            "BW-WB                         BW-WB",
            "BW-WB                         BW-WB",
            "BW-WB                         BW-WB",
            "BW-WB                         BW-WB",
            "BW-WB                         BW-WB",
            "BW-WB                         BW-WB",
            "BWW-WB                       BW-WWB",
            " BW-WB                       BW-WB ",
            " BW-WB                       BW-WB ",
            "  BW-WB                     BW-WB  ",
            "  BW-WWB                   BWW-WB  ",
            "   BW-WWB                 BWW-WB   ",
            "   BWW-WWB               BWW-WWB   ",
            "    BWW-WWB             BWW-WWB    ",
            "     BWW-WWBBB       BBBWW-WWB     ",
            "      BWW--WWWBBBBBBBWWW--WWB      ",
            "       BBWW---WWWWWWW---WWBB       ",
            "         BBWWW-------WWWBB         ",
            "           BBWWWWWWWWWBB           ",
            "             BBBBBBBBB             "
        },
        {
            "             BB     BB             ",
            "           BBWW     WWBB           ",
            "         BBWWWW     WWWWBB         ",
            "       BBWWWWWW     WWWWWWBB       ",
            "      BWWWWWWWB     BWWWWWWWB      ",
            "     BWWWWWBBB       BBBWWWWWB     ",
            "    BWWWWWB             BWWWWWB    ",
            "   BWWWWWB               BWWWWWB   ",
            "   BWWWWB                 BWWWWB   ",
            "  BWWWWB                   BWWWWB  ",
            "  BWWWB                     BWWWB  ",
            " BWWWB                       BWWWB ",
            " BWWWB                       BWWWB ",
            "BWWWWB                       BWWWWB",
            "BWWWB                         BWWWB",
            "BWWWB                         BWWWB",
            "BWWWB                         BWWWB",
            "BWWWB                         BWWWB",
            "BWWWB                         BWWWB",
            "BWWWB                         BWWWB",
            "BWWWB                         BWWWB",
            "BWWWWB                       BWWWWB",
            " BWWWB                       BWWWB ",
            " BWWWB                       BWWWB ",
            "  BWWWB                     BWWWB  ",
            "  BWWWWB                   BWWWWB  ",
            "   BWWWWB                 BWWWWB   ",
            "   BWWWWWB               BWWWWWB   ",
            "    BWWWWWB             BWWWWWB    ",
            "     BWWWWWBBB       BBBWWWWWB     ",
            "      BWWWWWWWBBBBBBBWWWWWWWB      ",
            "       BBWWWWWWWWWWWWWWWWWBB       ",
            "         BBWWWWWWWWWWWWWBB         ",
            "           BBWWWWWWWWWBB           ",
            "             BBBBBBBBB             "
        },
        {
            "                                   ",
            "             BB     BB             ",
            "           BBBB     BBBB           ",
            "         BBBBBB     BBBBBB         ",
            "       BBBBBBB       BBBBBBB       ",
            "      BBBBB             BBBBB      ",
            "     BBBBB               BBBBB     ",
            "    BBBBB                 BBBBB    ",
            "    BBBB                   BBBB    ",
            "   BBBB                     BBBB   ",
            "   BBB                       BBB   ",
            "  BBB                         BBB  ",
            "  BBB                         BBB  ",
            " BBBB                         BBBB ",
            " BBB                           BBB ",
            " BBB                           BBB ",
            " BBB                           BBB ",
            " BBB                           BBB ",
            " BBB                           BBB ",
            " BBB                           BBB ",
            " BBB                           BBB ",
            " BBBB                         BBBB ",
            "  BBB                         BBB  ",
            "  BBB                         BBB  ",
            "   BBB                       BBB   ",
            "   BBBB                     BBBB   ",
            "    BBBB                   BBBB    ",
            "    BBBBB                 BBBBB    ",
            "     BBBBB               BBBBB     ",
            "      BBBBB             BBBBB      ",
            "       BBBBBBB       BBBBBBB       ",
            "         BBBBBBBBBBBBBBBBB         ",
            "           BBBBBBBBBBBBB           ",
            "             BBBBBBBBB             ",
            "                                   "
        }
    });
}
