package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

public abstract class CYCLOTRON_SHAPE_FILE_7 {
    public static final String[][] CYCLOTRON_SHAPE_7_IDENTITY = transpose(new String[][] {
        {
            "                                                                                                       ",
            "                                            AAAAAAAAAAAAAAA                                            ",
            "                                       AAAAA               AAAAA                                       ",
            "                                    AAA                         AAA                                    ",
            "                                 AAA                               AAA                                 ",
            "                               AA                                     AA                               ",
            "                             AA                                         AA                             ",
            "                           AA                                             AA                           ",
            "                         AA                                                 AA                         ",
            "                        A                                                     A                        ",
            "                      AA                                                       AA                      ",
            "                     A                                                           A                     ",
            "                    A                                                             A                    ",
            "                  AA                                                               AA                  ",
            "                 A                                                                   A                 ",
            "                A                                                                     A                ",
            "               A                                                                       A               ",
            "              A                                                                         A              ",
            "             A                                                                           A             ",
            "             A                                                                           A             ",
            "            A                                                                             A            ",
            "           A                                                                               A           ",
            "          A                                                                                 A          ",
            "          A                                                                                 A          ",
            "         A                                                                                   A         ",
            "        A                                                                                     A        ",
            "        A                                                                                     A        ",
            "       A                                                                                       A       ",
            "       A                                                                                       A       ",
            "      A                                                                                         A      ",
            "      A                                                                                         A      ",
            "     A                                                                                           A     ",
            "     A                                                                                           A     ",
            "    A                                                                                             A    ",
            "    A                                                                                             A    ",
            "    A                                                                                             A    ",
            "   A                                                                                               A   ",
            "   A                                                                                               A   ",
            "   A                                                                                               A   ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "   A                                                                                               A   ",
            "   A                                                                                               A   ",
            "   A                                                                                               A   ",
            "    A                                                                                             A    ",
            "    A                                                                                             A    ",
            "    A                                                                                             A    ",
            "     A                                                                                           A     ",
            "     A                                                                                           A     ",
            "      A                                                                                         A      ",
            "      A                                                                                         A      ",
            "       A                                                                                       A       ",
            "       A                                                                                       A       ",
            "        A                                                                                     A        ",
            "        A                                                                                     A        ",
            "         A                                                                                   A         ",
            "          A                                                                                 A          ",
            "          A                                                                                 A          ",
            "           A                                                                               A           ",
            "            A                                                                             A            ",
            "             A                                                                           A             ",
            "             A                                                                           A             ",
            "              A                                                                         A              ",
            "               A                                                                       A               ",
            "                A                                                                     A                ",
            "                 A                                                                   A                 ",
            "                  AA                                                               AA                  ",
            "                    A                                                             A                    ",
            "                     A                                                           A                     ",
            "                      AA                                                       AA                      ",
            "                        A                                                     A                        ",
            "                         AA                                                 AA                         ",
            "                           AA                                             AA                           ",
            "                             AA                                         AA                             ",
            "                               AA                                     AA                               ",
            "                                 AAA                               AAA                                 ",
            "                                    AAA                         AAA                                    ",
            "                                       AAAAA               AAAAA                                       ",
            "                                            AAAAAAAAAAAAAAA                                            ",
            "                                                                                                       "
        },
        {
            "                                            AAAAAAA~AAAAAAA                                            ",
            "                                       AAAAABBBBBBBBBBBBBBBAAAAA                                       ",
            "                                    AAABBBBBAAAAAAAAAAAAAAABBBBBAAA                                    ",
            "                                 AAABBBAAAAAA             AAAAAABBBAAA                                 ",
            "                               AABBBAAAA                       AAAABBBAA                               ",
            "                            AAABBAAA                               AAABBAAA                            ",
            "                           AABBAAA                                   AAABBAA                           ",
            "                         AABBAA                                         AABBAA                         ",
            "                       AABBAA                                             AABBAA                       ",
            "                      AABAA                                                 AABAA                      ",
            "                     ABBAA                                                   AABBA                     ",
            "                   AABAA                                                       AABAA                   ",
            "                  AABAA                                                         AABAA                  ",
            "                 ABBAA                                                           AABBA                 ",
            "                ABAA                                                               AABA                ",
            "               ABAA                                                                 AABA               ",
            "              ABAA                                                                   AABA              ",
            "             ABAA                                                                     AABA             ",
            "            ABAA                                                                       AABA            ",
            "           AABA                                                                         ABAA           ",
            "           ABA                                                                           ABA           ",
            "          ABAA                                                                           AABA          ",
            "         ABAA                                                                             AABA         ",
            "        AABA                                                                               ABAA        ",
            "        ABA                                                                                 ABA        ",
            "       ABAA                                                                                 AABA       ",
            "       ABA                                                                                   ABA       ",
            "      ABA                                                                                     ABA      ",
            "     AABA                                                                                     ABAA     ",
            "     ABA                                                                                       ABA     ",
            "     ABA                                                                                       ABA     ",
            "    ABA                                                                                         ABA    ",
            "    ABA                                                                                         ABA    ",
            "   ABAA                                                                                         AABA   ",
            "   ABA                                                                                           ABA   ",
            "   ABA                                                                                           ABA   ",
            "  ABA                                                                                             ABA  ",
            "  ABA                                                                                             ABA  ",
            "  ABA                                                                                             ABA  ",
            " ABAA                                                                                             AABA ",
            " ABA                                                                                               ABA ",
            " ABA                                                                                               ABA ",
            " ABA                                                                                               ABA ",
            " ABA                                                                                               ABA ",
            "ABAA                                                                                               AABA",
            "ABA                                                                                                 ABA",
            "ABA                                                                                                 ABA",
            "ABA                                                                                                 ABA",
            "ABA                                                                                                 ABA",
            "ABA                                                                                                 ABA",
            "ABA                                                                                                 ABA",
            "ABA                                                                                                 ABA",
            "ABA                                                                                                 ABA",
            "ABA                                                                                                 ABA",
            "ABA                                                                                                 ABA",
            "ABA                                                                                                 ABA",
            "ABA                                                                                                 ABA",
            "ABA                                                                                                 ABA",
            "ABAA                                                                                               AABA",
            " ABA                                                                                               ABA ",
            " ABA                                                                                               ABA ",
            " ABA                                                                                               ABA ",
            " ABA                                                                                               ABA ",
            " ABAA                                                                                             AABA ",
            "  ABA                                                                                             ABA  ",
            "  ABA                                                                                             ABA  ",
            "  ABA                                                                                             ABA  ",
            "   ABA                                                                                           ABA   ",
            "   ABA                                                                                           ABA   ",
            "   ABAA                                                                                         AABA   ",
            "    ABA                                                                                         ABA    ",
            "    ABA                                                                                         ABA    ",
            "     ABA                                                                                       ABA     ",
            "     ABA                                                                                       ABA     ",
            "     AABA                                                                                     ABAA     ",
            "      ABA                                                                                     ABA      ",
            "       ABA                                                                                   ABA       ",
            "       ABAA                                                                                 AABA       ",
            "        ABA                                                                                 ABA        ",
            "        AABA                                                                               ABAA        ",
            "         ABAA                                                                             AABA         ",
            "          ABAA                                                                           AABA          ",
            "           ABA                                                                           ABA           ",
            "           AABA                                                                         ABAA           ",
            "            ABAA                                                                       AABA            ",
            "             ABAA                                                                     AABA             ",
            "              ABAA                                                                   AABA              ",
            "               ABAA                                                                 AABA               ",
            "                ABAA                                                               AABA                ",
            "                 ABBAA                                                           AABBA                 ",
            "                  AABAA                                                         AABAA                  ",
            "                   AABAA                                                       AABAA                   ",
            "                     ABBAA                                                   AABBA                     ",
            "                      AABAA                                                 AABAA                      ",
            "                       AABBAA                                             AABBAA                       ",
            "                         AABBAA                                         AABBAA                         ",
            "                           AABBAAA                                   AAABBAA                           ",
            "                            AAABBAAA                               AAABBAAA                            ",
            "                               AABBBAAAA                       AAAABBBAA                               ",
            "                                 AAABBBAAAAAA             AAAAAABBBAAA                                 ",
            "                                    AAABBBBBAAAAAAAAAAAAAAABBBBBAAA                                    ",
            "                                       AAAAABBBBBBBBBBBBBBBAAAAA                                       ",
            "                                            AAAAAAAAAAAAAAA                                            "
        },
        {
            "                                                                                                       ",
            "                                            AAAAAAAAAAAAAAA                                            ",
            "                                       AAAAA               AAAAA                                       ",
            "                                    AAA                         AAA                                    ",
            "                                 AAA                               AAA                                 ",
            "                               AA                                     AA                               ",
            "                             AA                                         AA                             ",
            "                           AA                                             AA                           ",
            "                         AA                                                 AA                         ",
            "                        A                                                     A                        ",
            "                      AA                                                       AA                      ",
            "                     A                                                           A                     ",
            "                    A                                                             A                    ",
            "                  AA                                                               AA                  ",
            "                 A                                                                   A                 ",
            "                A                                                                     A                ",
            "               A                                                                       A               ",
            "              A                                                                         A              ",
            "             A                                                                           A             ",
            "             A                                                                           A             ",
            "            A                                                                             A            ",
            "           A                                                                               A           ",
            "          A                                                                                 A          ",
            "          A                                                                                 A          ",
            "         A                                                                                   A         ",
            "        A                                                                                     A        ",
            "        A                                                                                     A        ",
            "       A                                                                                       A       ",
            "       A                                                                                       A       ",
            "      A                                                                                         A      ",
            "      A                                                                                         A      ",
            "     A                                                                                           A     ",
            "     A                                                                                           A     ",
            "    A                                                                                             A    ",
            "    A                                                                                             A    ",
            "    A                                                                                             A    ",
            "   A                                                                                               A   ",
            "   A                                                                                               A   ",
            "   A                                                                                               A   ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            " A                                                                                                   A ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "  A                                                                                                 A  ",
            "   A                                                                                               A   ",
            "   A                                                                                               A   ",
            "   A                                                                                               A   ",
            "    A                                                                                             A    ",
            "    A                                                                                             A    ",
            "    A                                                                                             A    ",
            "     A                                                                                           A     ",
            "     A                                                                                           A     ",
            "      A                                                                                         A      ",
            "      A                                                                                         A      ",
            "       A                                                                                       A       ",
            "       A                                                                                       A       ",
            "        A                                                                                     A        ",
            "        A                                                                                     A        ",
            "         A                                                                                   A         ",
            "          A                                                                                 A          ",
            "          A                                                                                 A          ",
            "           A                                                                               A           ",
            "            A                                                                             A            ",
            "             A                                                                           A             ",
            "             A                                                                           A             ",
            "              A                                                                         A              ",
            "               A                                                                       A               ",
            "                A                                                                     A                ",
            "                 A                                                                   A                 ",
            "                  AA                                                               AA                  ",
            "                    A                                                             A                    ",
            "                     A                                                           A                     ",
            "                      AA                                                       AA                      ",
            "                        A                                                     A                        ",
            "                         AA                                                 AA                         ",
            "                           AA                                             AA                           ",
            "                             AA                                         AA                             ",
            "                               AA                                     AA                               ",
            "                                 AAA                               AAA                                 ",
            "                                    AAA                         AAA                                    ",
            "                                       AAAAA               AAAAA                                       ",
            "                                            AAAAAAAAAAAAAAA                                            ",
            "                                                                                                       "
        }
    });
}
