package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_4 {
    public static final String[][] CYCLOTRON_SHAPE_4_IDENTITY = transpose(new String[][] {
        {
            "                                                                           ",
            "                               BBBB     BBBB                               ",
            "                           BBBBBBBB     BBBBBBBB                           ",
            "                        BBBBBBBBBBB     BBBBBBBBBBB                        ",
            "                      BBBBBBBBBB           BBBBBBBBBB                      ",
            "                    BBBBBBBB                   BBBBBBBB                    ",
            "                  BBBBBBB                         BBBBBBB                  ",
            "                 BBBBBB                             BBBBBB                 ",
            "               BBBBBB                                 BBBBBB               ",
            "              BBBBB                                     BBBBB              ",
            "             BBBBB                                       BBBBB             ",
            "            BBBBB                                         BBBBB            ",
            "           BBBB                                             BBBB           ",
            "          BBBB                                               BBBB          ",
            "         BBBB                                                 BBBB         ",
            "        BBBB                                                   BBBB        ",
            "        BBBB                                                   BBBB        ",
            "       BBBB                                                     BBBB       ",
            "      BBBB                                                       BBBB      ",
            "      BBB                                                         BBB      ",
            "     BBBB                                                         BBBB     ",
            "     BBB                                                           BBB     ",
            "    BBBB                                                           BBBB    ",
            "    BBB                                                             BBB    ",
            "   BBBB                                                             BBBB   ",
            "   BBB                                                               BBB   ",
            "   BBB                                                               BBB   ",
            "  BBBB                                                               BBBB  ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            " BBBB                                                                 BBBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBBB                                                                 BBBB ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            "  BBBB                                                               BBBB  ",
            "   BBB                                                               BBB   ",
            "   BBB                                                               BBB   ",
            "   BBBB                                                             BBBB   ",
            "    BBB                                                             BBB    ",
            "    BBBB                                                           BBBB    ",
            "     BBB                                                           BBB     ",
            "     BBBB                                                         BBBB     ",
            "      BBB                                                         BBB      ",
            "      BBBB                                                       BBBB      ",
            "       BBBB                                                     BBBB       ",
            "        BBBB                                                   BBBB        ",
            "        BBBB                                                   BBBB        ",
            "         BBBB                                                 BBBB         ",
            "          BBBB                                               BBBB          ",
            "           BBBB                                             BBBB           ",
            "            BBBBB                                         BBBBB            ",
            "             BBBBB                                       BBBBB             ",
            "              BBBBB                                     BBBBB              ",
            "               BBBBBB                                 BBBBBB               ",
            "                 BBBBBB                             BBBBBB                 ",
            "                  BBBBBBB                         BBBBBBB                  ",
            "                    BBBBBBBB                   BBBBBBBB                    ",
            "                      BBBBBBBBBB           BBBBBBBBBB                      ",
            "                        BBBBBBBBBBBBBBBBBBBBBBBBBBB                        ",
            "                           BBBBBBBBBBBBBBBBBBBBB                           ",
            "                               BBBBBBBBBBBBB                               ",
            "                                                                           "
        },
        {
            "                               BBBB     BBBB                               ",
            "                           BBBBWWWW     WWWWBBBB                           ",
            "                        BBBWWWWWWWW     WWWWWWWWBBB                        ",
            "                      BBWWWWWWWWWWW     WWWWWWWWWWWBB                      ",
            "                    BBWWWWWWWWWWBBB     BBBWWWWWWWWWWBB                    ",
            "                  BBWWWWWWWWBBBB           BBBBWWWWWWWWBB                  ",
            "                 BWWWWWWWBBB                   BBBWWWWWWWB                 ",
            "               BBWWWWWWBB                         BBWWWWWWBB               ",
            "              BWWWWWWBB                             BBWWWWWWB              ",
            "             BWWWWWBB                                 BBWWWWWB             ",
            "            BWWWWWB                                     BWWWWWB            ",
            "           BWWWWWB                                       BWWWWWB           ",
            "          BWWWWBB                                         BBWWWWB          ",
            "         BWWWWB                                             BWWWWB         ",
            "        BWWWWB                                               BWWWWB        ",
            "       BWWWWB                                                 BWWWWB       ",
            "       BWWWWB                                                 BWWWWB       ",
            "      BWWWWB                                                   BWWWWB      ",
            "     BWWWWB                                                     BWWWWB     ",
            "     BWWWB                                                       BWWWB     ",
            "    BWWWWB                                                       BWWWWB    ",
            "    BWWWB                                                         BWWWB    ",
            "   BWWWWB                                                         BWWWWB   ",
            "   BWWWB                                                           BWWWB   ",
            "  BWWWWB                                                           BWWWWB  ",
            "  BWWWB                                                             BWWWB  ",
            "  BWWWB                                                             BWWWB  ",
            " BWWWWB                                                             BWWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            "BWWWWB                                                               BWWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWWB                                                               BWWWWB",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWWB                                                             BWWWWB ",
            "  BWWWB                                                             BWWWB  ",
            "  BWWWB                                                             BWWWB  ",
            "  BWWWWB                                                           BWWWWB  ",
            "   BWWWB                                                           BWWWB   ",
            "   BWWWWB                                                         BWWWWB   ",
            "    BWWWB                                                         BWWWB    ",
            "    BWWWWB                                                       BWWWWB    ",
            "     BWWWB                                                       BWWWB     ",
            "     BWWWWB                                                     BWWWWB     ",
            "      BWWWWB                                                   BWWWWB      ",
            "       BWWWWB                                                 BWWWWB       ",
            "       BWWWWB                                                 BWWWWB       ",
            "        BWWWWB                                               BWWWWB        ",
            "         BWWWWB                                             BWWWWB         ",
            "          BWWWWBB                                         BBWWWWB          ",
            "           BWWWWWB                                       BWWWWWB           ",
            "            BWWWWWB                                     BWWWWWB            ",
            "             BWWWWWBB                                 BBWWWWWB             ",
            "              BWWWWWWBB                             BBWWWWWWB              ",
            "               BBWWWWWWBB                         BBWWWWWWBB               ",
            "                 BWWWWWWWBBB                   BBBWWWWWWWB                 ",
            "                  BBWWWWWWWWBBBB           BBBBWWWWWWWWBB                  ",
            "                    BBWWWWWWWWWWBBBBBBBBBBBWWWWWWWWWWBB                    ",
            "                      BBWWWWWWWWWWWWWWWWWWWWWWWWWWWBB                      ",
            "                        BBBWWWWWWWWWWWWWWWWWWWWWBBB                        ",
            "                           BBBBWWWWWWWWWWWWWBBBB                           ",
            "                               BBBBBBBBBBBBB                               "
        },
        {
            "                               BBBB     BBBB                               ",
            "                           BBBBWWWW  ~  WWWWBBBB                           ",
            "                        BBBWWWWWXXXXXXXXXXXWWWWWBBB                        ",
            "                      BBWWWXXXXXWWW     WWWXXXXXWWWBB                      ",
            "                    BBWWWXXWWWWWBBB     BBBWWWWWXXWWWBB                    ",
            "                  BBWWXXXWWWBBBB           BBBBWWWXXXWWBB                  ",
            "                 BWWXXWWWBBB                   BBBWWWXXWWB                 ",
            "               BBWWXWWWBB                         BBWWWXWWBB               ",
            "              BWWXXWWBB                             BBWWXXWWB              ",
            "             BWWXWWBB                                 BBWWXWWB             ",
            "            BWWXWWB                                     BWWXWWB            ",
            "           BWWXWWB                                       BWWXWWB           ",
            "          BWWXWBB                                         BBWXWWB          ",
            "         BWWXWB                                             BWXWWB         ",
            "        BWWXWB                                               BWXWWB        ",
            "       BWWXWB                                                 BWXWWB       ",
            "       BWXWWB                                                 BWWXWB       ",
            "      BWXWWB                                                   BWWXWB      ",
            "     BWWXWB                                                     BWXWWB     ",
            "     BWXWB                                                       BWXWB     ",
            "    BWXWWB                                                       BWWXWB    ",
            "    BWXWB                                                         BWXWB    ",
            "   BWXWWB                                                         BWWXWB   ",
            "   BWXWB                                                           BWXWB   ",
            "  BWWXWB                                                           BWXWWB  ",
            "  BWXWB                                                             BWXWB  ",
            "  BWXWB                                                             BWXWB  ",
            " BWXWWB                                                             BWWXWB ",
            " BWXWB                                                               BWXWB ",
            " BWXWB                                                               BWXWB ",
            " BWXWB                                                               BWXWB ",
            "BWWXWB                                                               BWXWWB",
            "BWXWB                                                                 BWXWB",
            "BWXWB                                                                 BWXWB",
            "BWXWB                                                                 BWXWB",
            "BWXWB                                                                 BWXWB",
            "BWXWB                                                                 BWXWB",
            "BWXWB                                                                 BWXWB",
            "BWXWB                                                                 BWXWB",
            "BWXWB                                                                 BWXWB",
            "BWXWB                                                                 BWXWB",
            "BWXWB                                                                 BWXWB",
            "BWXWB                                                                 BWXWB",
            "BWWXWB                                                               BWXWWB",
            " BWXWB                                                               BWXWB ",
            " BWXWB                                                               BWXWB ",
            " BWXWB                                                               BWXWB ",
            " BWXWWB                                                             BWWXWB ",
            "  BWXWB                                                             BWXWB  ",
            "  BWXWB                                                             BWXWB  ",
            "  BWWXWB                                                           BWXWWB  ",
            "   BWXWB                                                           BWXWB   ",
            "   BWXWWB                                                         BWWXWB   ",
            "    BWXWB                                                         BWXWB    ",
            "    BWXWWB                                                       BWWXWB    ",
            "     BWXWB                                                       BWXWB     ",
            "     BWWXWB                                                     BWXWWB     ",
            "      BWXWWB                                                   BWWXWB      ",
            "       BWXWWB                                                 BWWXWB       ",
            "       BWWXWB                                                 BWXWWB       ",
            "        BWWXWB                                               BWXWWB        ",
            "         BWWXWB                                             BWXWWB         ",
            "          BWWXWBB                                         BBWXWWB          ",
            "           BWWXWWB                                       BWWXWWB           ",
            "            BWWXWWB                                     BWWXWWB            ",
            "             BWWXWWBB                                 BBWWXWWB             ",
            "              BWWXXWWBB                             BBWWXXWWB              ",
            "               BBWWXWWWBB                         BBWWWXWWBB               ",
            "                 BWWXXWWWBBB                   BBBWWWXXWWB                 ",
            "                  BBWWXXXWWWBBBB           BBBBWWWXXXWWBB                  ",
            "                    BBWWWXXWWWWWBBBBBBBBBBBWWWWWXXWWWBB                    ",
            "                      BBWWWXXXXXWWWWWWWWWWWXXXXXWWWBB                      ",
            "                        BBBWWWWWXXXXXXXXXXXWWWWWBBB                        ",
            "                           BBBBWWWWWWWWWWWWWBBBB                           ",
            "                               BBBBBBBBBBBBB                               "
        },
        {
            "                               BBBB     BBBB                               ",
            "                           BBBBWWWW     WWWWBBBB                           ",
            "                        BBBWWWWWWWW     WWWWWWWWBBB                        ",
            "                      BBWWWWWWWWWWW     WWWWWWWWWWWBB                      ",
            "                    BBWWWWWWWWWWBBB     BBBWWWWWWWWWWBB                    ",
            "                  BBWWWWWWWWBBBB           BBBBWWWWWWWWBB                  ",
            "                 BWWWWWWWBBB                   BBBWWWWWWWB                 ",
            "               BBWWWWWWBB                         BBWWWWWWBB               ",
            "              BWWWWWWBB                             BBWWWWWWB              ",
            "             BWWWWWBB                                 BBWWWWWB             ",
            "            BWWWWWB                                     BWWWWWB            ",
            "           BWWWWWB                                       BWWWWWB           ",
            "          BWWWWBB                                         BBWWWWB          ",
            "         BWWWWB                                             BWWWWB         ",
            "        BWWWWB                                               BWWWWB        ",
            "       BWWWWB                                                 BWWWWB       ",
            "       BWWWWB                                                 BWWWWB       ",
            "      BWWWWB                                                   BWWWWB      ",
            "     BWWWWB                                                     BWWWWB     ",
            "     BWWWB                                                       BWWWB     ",
            "    BWWWWB                                                       BWWWWB    ",
            "    BWWWB                                                         BWWWB    ",
            "   BWWWWB                                                         BWWWWB   ",
            "   BWWWB                                                           BWWWB   ",
            "  BWWWWB                                                           BWWWWB  ",
            "  BWWWB                                                             BWWWB  ",
            "  BWWWB                                                             BWWWB  ",
            " BWWWWB                                                             BWWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            "BWWWWB                                                               BWWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWWB                                                               BWWWWB",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWWB                                                             BWWWWB ",
            "  BWWWB                                                             BWWWB  ",
            "  BWWWB                                                             BWWWB  ",
            "  BWWWWB                                                           BWWWWB  ",
            "   BWWWB                                                           BWWWB   ",
            "   BWWWWB                                                         BWWWWB   ",
            "    BWWWB                                                         BWWWB    ",
            "    BWWWWB                                                       BWWWWB    ",
            "     BWWWB                                                       BWWWB     ",
            "     BWWWWB                                                     BWWWWB     ",
            "      BWWWWB                                                   BWWWWB      ",
            "       BWWWWB                                                 BWWWWB       ",
            "       BWWWWB                                                 BWWWWB       ",
            "        BWWWWB                                               BWWWWB        ",
            "         BWWWWB                                             BWWWWB         ",
            "          BWWWWBB                                         BBWWWWB          ",
            "           BWWWWWB                                       BWWWWWB           ",
            "            BWWWWWB                                     BWWWWWB            ",
            "             BWWWWWBB                                 BBWWWWWB             ",
            "              BWWWWWWBB                             BBWWWWWWB              ",
            "               BBWWWWWWBB                         BBWWWWWWBB               ",
            "                 BWWWWWWWBBB                   BBBWWWWWWWB                 ",
            "                  BBWWWWWWWWBBBB           BBBBWWWWWWWWBB                  ",
            "                    BBWWWWWWWWWWBBBBBBBBBBBWWWWWWWWWWBB                    ",
            "                      BBWWWWWWWWWWWWWWWWWWWWWWWWWWWBB                      ",
            "                        BBBWWWWWWWWWWWWWWWWWWWWWBBB                        ",
            "                           BBBBWWWWWWWWWWWWWBBBB                           ",
            "                               BBBBBBBBBBBBB                               "
        },
        {
            "                                                                           ",
            "                               BBBB     BBBB                               ",
            "                           BBBBBBBB     BBBBBBBB                           ",
            "                        BBBBBBBBBBB     BBBBBBBBBBB                        ",
            "                      BBBBBBBBBB           BBBBBBBBBB                      ",
            "                    BBBBBBBB                   BBBBBBBB                    ",
            "                  BBBBBBB                         BBBBBBB                  ",
            "                 BBBBBB                             BBBBBB                 ",
            "               BBBBBB                                 BBBBBB               ",
            "              BBBBB                                     BBBBB              ",
            "             BBBBB                                       BBBBB             ",
            "            BBBBB                                         BBBBB            ",
            "           BBBB                                             BBBB           ",
            "          BBBB                                               BBBB          ",
            "         BBBB                                                 BBBB         ",
            "        BBBB                                                   BBBB        ",
            "        BBBB                                                   BBBB        ",
            "       BBBB                                                     BBBB       ",
            "      BBBB                                                       BBBB      ",
            "      BBB                                                         BBB      ",
            "     BBBB                                                         BBBB     ",
            "     BBB                                                           BBB     ",
            "    BBBB                                                           BBBB    ",
            "    BBB                                                             BBB    ",
            "   BBBB                                                             BBBB   ",
            "   BBB                                                               BBB   ",
            "   BBB                                                               BBB   ",
            "  BBBB                                                               BBBB  ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            " BBBB                                                                 BBBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBBB                                                                 BBBB ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            "  BBBB                                                               BBBB  ",
            "   BBB                                                               BBB   ",
            "   BBB                                                               BBB   ",
            "   BBBB                                                             BBBB   ",
            "    BBB                                                             BBB    ",
            "    BBBB                                                           BBBB    ",
            "     BBB                                                           BBB     ",
            "     BBBB                                                         BBBB     ",
            "      BBB                                                         BBB      ",
            "      BBBB                                                       BBBB      ",
            "       BBBB                                                     BBBB       ",
            "        BBBB                                                   BBBB        ",
            "        BBBB                                                   BBBB        ",
            "         BBBB                                                 BBBB         ",
            "          BBBB                                               BBBB          ",
            "           BBBB                                             BBBB           ",
            "            BBBBB                                         BBBBB            ",
            "             BBBBB                                       BBBBB             ",
            "              BBBBB                                     BBBBB              ",
            "               BBBBBB                                 BBBBBB               ",
            "                 BBBBBB                             BBBBBB                 ",
            "                  BBBBBBB                         BBBBBBB                  ",
            "                    BBBBBBBB                   BBBBBBBB                    ",
            "                      BBBBBBBBBB           BBBBBBBBBB                      ",
            "                        BBBBBBBBBBBBBBBBBBBBBBBBBBB                        ",
            "                           BBBBBBBBBBBBBBBBBBBBB                           ",
            "                               BBBBBBBBBBBBB                               ",
            "                                                                           "
        }
    });
}
