package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_5 {
    public static final String[][] CYCLOTRON_SHAPE_5_IDENTITY = transpose(new String[][] {
        {
            "                                                                                     ",
            "                                    BBBB     BBBB                                    ",
            "                               BBBBBBBBB     BBBBBBBBB                               ",
            "                            BBBBBBBBBBBB     BBBBBBBBBBBB                            ",
            "                          BBBBBBBBBB             BBBBBBBBBB                          ",
            "                        BBBBBBBB                     BBBBBBBB                        ",
            "                      BBBBBBB                           BBBBBBB                      ",
            "                    BBBBBBB                               BBBBBBB                    ",
            "                   BBBBBB                                   BBBBBB                   ",
            "                 BBBBBB                                       BBBBBB                 ",
            "                BBBBB                                           BBBBB                ",
            "               BBBBB                                             BBBBB               ",
            "              BBBBB                                               BBBBB              ",
            "             BBBB                                                   BBBB             ",
            "            BBBB                                                     BBBB            ",
            "           BBBB                                                       BBBB           ",
            "          BBBB                                                         BBBB          ",
            "         BBBB                                                           BBBB         ",
            "         BBBB                                                           BBBB         ",
            "        BBBB                                                             BBBB        ",
            "       BBBB                                                               BBBB       ",
            "       BBB                                                                 BBB       ",
            "      BBBB                                                                 BBBB      ",
            "      BBB                                                                   BBB      ",
            "     BBBB                                                                   BBBB     ",
            "     BBB                                                                     BBB     ",
            "    BBBB                                                                     BBBB    ",
            "    BBB                                                                       BBB    ",
            "   BBBB                                                                       BBBB   ",
            "   BBB                                                                         BBB   ",
            "   BBB                                                                         BBB   ",
            "  BBBB                                                                         BBBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBBB                                                                         BBBB  ",
            "   BBB                                                                         BBB   ",
            "   BBB                                                                         BBB   ",
            "   BBBB                                                                       BBBB   ",
            "    BBB                                                                       BBB    ",
            "    BBBB                                                                     BBBB    ",
            "     BBB                                                                     BBB     ",
            "     BBBB                                                                   BBBB     ",
            "      BBB                                                                   BBB      ",
            "      BBBB                                                                 BBBB      ",
            "       BBB                                                                 BBB       ",
            "       BBBB                                                               BBBB       ",
            "        BBBB                                                             BBBB        ",
            "         BBBB                                                           BBBB         ",
            "         BBBB                                                           BBBB         ",
            "          BBBB                                                         BBBB          ",
            "           BBBB                                                       BBBB           ",
            "            BBBB                                                     BBBB            ",
            "             BBBB                                                   BBBB             ",
            "              BBBBB                                               BBBBB              ",
            "               BBBBB                                             BBBBB               ",
            "                BBBBB                                           BBBBB                ",
            "                 BBBBBB                                       BBBBBB                 ",
            "                   BBBBBB                                   BBBBBB                   ",
            "                    BBBBBBB                               BBBBBBB                    ",
            "                      BBBBBBB                           BBBBBBB                      ",
            "                        BBBBBBBB                     BBBBBBBB                        ",
            "                          BBBBBBBBBB             BBBBBBBBBB                          ",
            "                            BBBBBBBBBBBBBBBBBBBBBBBBBBBBB                            ",
            "                               BBBBBBBBBBBBBBBBBBBBBBB                               ",
            "                                    BBBBBBBBBBBBB                                    ",
            "                                                                                     "
        },
        {
            "                                    BBBB     BBBB                                    ",
            "                               BBBBBWWWW     WWWWBBBBB                               ",
            "                            BBBWWWWWWWWW     WWWWWWWWWBBB                            ",
            "                          BBWWWWWWWWWWWW     WWWWWWWWWWWWBB                          ",
            "                        BBWWWWWWWWWWBBBB     BBBBWWWWWWWWWWBB                        ",
            "                      BBWWWWWWWWBBBB             BBBBWWWWWWWWBB                      ",
            "                    BBWWWWWWWBBB                     BBBWWWWWWWBB                    ",
            "                   BWWWWWWWBB                           BBWWWWWWWB                   ",
            "                 BBWWWWWWBB                               BBWWWWWWBB                 ",
            "                BWWWWWWBB                                   BBWWWWWWB                ",
            "               BWWWWWBB                                       BBWWWWWB               ",
            "              BWWWWWB                                           BWWWWWB              ",
            "             BWWWWWB                                             BWWWWWB             ",
            "            BWWWWBB                                               BBWWWWB            ",
            "           BWWWWB                                                   BWWWWB           ",
            "          BWWWWB                                                     BWWWWB          ",
            "         BWWWWB                                                       BWWWWB         ",
            "        BWWWWB                                                         BWWWWB        ",
            "        BWWWWB                                                         BWWWWB        ",
            "       BWWWWB                                                           BWWWWB       ",
            "      BWWWWB                                                             BWWWWB      ",
            "      BWWWB                                                               BWWWB      ",
            "     BWWWWB                                                               BWWWWB     ",
            "     BWWWB                                                                 BWWWB     ",
            "    BWWWWB                                                                 BWWWWB    ",
            "    BWWWB                                                                   BWWWB    ",
            "   BWWWWB                                                                   BWWWWB   ",
            "   BWWWB                                                                     BWWWB   ",
            "  BWWWWB                                                                     BWWWWB  ",
            "  BWWWB                                                                       BWWWB  ",
            "  BWWWB                                                                       BWWWB  ",
            " BWWWWB                                                                       BWWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWWB                                                                       BWWWWB ",
            "  BWWWB                                                                       BWWWB  ",
            "  BWWWB                                                                       BWWWB  ",
            "  BWWWWB                                                                     BWWWWB  ",
            "   BWWWB                                                                     BWWWB   ",
            "   BWWWWB                                                                   BWWWWB   ",
            "    BWWWB                                                                   BWWWB    ",
            "    BWWWWB                                                                 BWWWWB    ",
            "     BWWWB                                                                 BWWWB     ",
            "     BWWWWB                                                               BWWWWB     ",
            "      BWWWB                                                               BWWWB      ",
            "      BWWWWB                                                             BWWWWB      ",
            "       BWWWWB                                                           BWWWWB       ",
            "        BWWWWB                                                         BWWWWB        ",
            "        BWWWWB                                                         BWWWWB        ",
            "         BWWWWB                                                       BWWWWB         ",
            "          BWWWWB                                                     BWWWWB          ",
            "           BWWWWB                                                   BWWWWB           ",
            "            BWWWWBB                                               BBWWWWB            ",
            "             BWWWWWB                                             BWWWWWB             ",
            "              BWWWWWB                                           BWWWWWB              ",
            "               BWWWWWBB                                       BBWWWWWB               ",
            "                BWWWWWWBB                                   BBWWWWWWB                ",
            "                 BBWWWWWWBB                               BBWWWWWWBB                 ",
            "                   BWWWWWWWBB                           BBWWWWWWWB                   ",
            "                    BBWWWWWWWBBB                     BBBWWWWWWWBB                    ",
            "                      BBWWWWWWWWBBBB             BBBBWWWWWWWWBB                      ",
            "                        BBWWWWWWWWWWBBBBBBBBBBBBBWWWWWWWWWWBB                        ",
            "                          BBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBB                          ",
            "                            BBBWWWWWWWWWWWWWWWWWWWWWWWBBB                            ",
            "                               BBBBBWWWWWWWWWWWWWBBBBB                               ",
            "                                    BBBBBBBBBBBBB                                    "
        },
        {
            "                                    BBBB     BBBB                                    ",
            "                               BBBBBWWWW  ~  WWWWBBBBB                               ",
            "                            BBBWWWWW-------------WWWWWBBB                            ",
            "                          BBWWWW----WWWW     WWWW----WWWWBB                          ",
            "                        BBWWW---WWWWBBBB     BBBBWWWW---WWWBB                        ",
            "                      BBWW---WWWBBBB             BBBBWWW---WWBB                      ",
            "                    BBWW--WWWBBB                     BBBWWW--WWBB                    ",
            "                   BWW--WWWBB                           BBWWW--WWB                   ",
            "                 BBWW-WWWBB                               BBWWW-WWBB                 ",
            "                BWW--WWBB                                   BBWW--WWB                ",
            "               BWW-WWBB                                       BBWW-WWB               ",
            "              BWW-WWB                                           BWW-WWB              ",
            "             BW--WWB                                             BWW--WB             ",
            "            BW-WWBB                                               BBWW-WB            ",
            "           BW-WWB                                                   BWW-WB           ",
            "          BW-WWB                                                     BWW-WB          ",
            "         BWW-WB                                                       BW-WWB         ",
            "        BWW-WB                                                         BW-WWB        ",
            "        BW-WWB                                                         BWW-WB        ",
            "       BW-WWB                                                           BWW-WB       ",
            "      BWW-WB                                                             BW-WWB      ",
            "      BW-WB                                                               BW-WB      ",
            "     BW-WWB                                                               BWW-WB     ",
            "     BW-WB                                                                 BW-WB     ",
            "    BW-WWB                                                                 BWW-WB    ",
            "    BW-WB                                                                   BW-WB    ",
            "   BW-WWB                                                                   BWW-WB   ",
            "   BW-WB                                                                     BW-WB   ",
            "  BWW-WB                                                                     BW-WWB  ",
            "  BW-WB                                                                       BW-WB  ",
            "  BW-WB                                                                       BW-WB  ",
            " BWW-WB                                                                       BW-WWB ",
            " BW-WB                                                                         BW-WB ",
            " BW-WB                                                                         BW-WB ",
            " BW-WB                                                                         BW-WB ",
            " BW-WB                                                                         BW-WB ",
            "BW-WB                                                                           BW-WB",
            "BW-WB                                                                           BW-WB",
            "BW-WB                                                                           BW-WB",
            "BW-WB                                                                           BW-WB",
            "BW-WB                                                                           BW-WB",
            "BW-WB                                                                           BW-WB",
            "BW-WB                                                                           BW-WB",
            "BW-WB                                                                           BW-WB",
            "BW-WB                                                                           BW-WB",
            "BW-WB                                                                           BW-WB",
            "BW-WB                                                                           BW-WB",
            "BW-WB                                                                           BW-WB",
            "BW-WB                                                                           BW-WB",
            " BW-WB                                                                         BW-WB ",
            " BW-WB                                                                         BW-WB ",
            " BW-WB                                                                         BW-WB ",
            " BW-WB                                                                         BW-WB ",
            " BWW-WB                                                                       BW-WWB ",
            "  BW-WB                                                                       BW-WB  ",
            "  BW-WB                                                                       BW-WB  ",
            "  BWW-WB                                                                     BW-WWB  ",
            "   BW-WB                                                                     BW-WB   ",
            "   BW-WWB                                                                   BWW-WB   ",
            "    BW-WB                                                                   BW-WB    ",
            "    BW-WWB                                                                 BWW-WB    ",
            "     BW-WB                                                                 BW-WB     ",
            "     BW-WWB                                                               BWW-WB     ",
            "      BW-WB                                                               BW-WB      ",
            "      BWW-WB                                                             BW-WWB      ",
            "       BW-WWB                                                           BWW-WB       ",
            "        BW-WWB                                                         BWW-WB        ",
            "        BWW-WB                                                         BW-WWB        ",
            "         BWW-WB                                                       BW-WWB         ",
            "          BW-WWB                                                     BWW-WB          ",
            "           BW-WWB                                                   BWW-WB           ",
            "            BW-WWBB                                               BBWW-WB            ",
            "             BW--WWB                                             BWW--WB             ",
            "              BWW-WWB                                           BWW-WWB              ",
            "               BWW-WWBB                                       BBWW-WWB               ",
            "                BWW--WWBB                                   BBWW--WWB                ",
            "                 BBWW-WWWBB                               BBWWW-WWBB                 ",
            "                   BWW--WWWBB                           BBWWW--WWB                   ",
            "                    BBWW--WWWBBB                     BBBWWW--WWBB                    ",
            "                      BBWW---WWWBBBB             BBBBWWW---WWBB                      ",
            "                        BBWWW---WWWWBBBBBBBBBBBBBWWWW---WWWBB                        ",
            "                          BBWWWW----WWWWWWWWWWWWW----WWWWBB                          ",
            "                            BBBWWWWW-------------WWWWWBBB                            ",
            "                               BBBBBWWWWWWWWWWWWWBBBBB                               ",
            "                                    BBBBBBBBBBBBB                                    "
        },
        {
            "                                    BBBB     BBBB                                    ",
            "                               BBBBBWWWW     WWWWBBBBB                               ",
            "                            BBBWWWWWWWWW     WWWWWWWWWBBB                            ",
            "                          BBWWWWWWWWWWWW     WWWWWWWWWWWWBB                          ",
            "                        BBWWWWWWWWWWBBBB     BBBBWWWWWWWWWWBB                        ",
            "                      BBWWWWWWWWBBBB             BBBBWWWWWWWWBB                      ",
            "                    BBWWWWWWWBBB                     BBBWWWWWWWBB                    ",
            "                   BWWWWWWWBB                           BBWWWWWWWB                   ",
            "                 BBWWWWWWBB                               BBWWWWWWBB                 ",
            "                BWWWWWWBB                                   BBWWWWWWB                ",
            "               BWWWWWBB                                       BBWWWWWB               ",
            "              BWWWWWB                                           BWWWWWB              ",
            "             BWWWWWB                                             BWWWWWB             ",
            "            BWWWWBB                                               BBWWWWB            ",
            "           BWWWWB                                                   BWWWWB           ",
            "          BWWWWB                                                     BWWWWB          ",
            "         BWWWWB                                                       BWWWWB         ",
            "        BWWWWB                                                         BWWWWB        ",
            "        BWWWWB                                                         BWWWWB        ",
            "       BWWWWB                                                           BWWWWB       ",
            "      BWWWWB                                                             BWWWWB      ",
            "      BWWWB                                                               BWWWB      ",
            "     BWWWWB                                                               BWWWWB     ",
            "     BWWWB                                                                 BWWWB     ",
            "    BWWWWB                                                                 BWWWWB    ",
            "    BWWWB                                                                   BWWWB    ",
            "   BWWWWB                                                                   BWWWWB   ",
            "   BWWWB                                                                     BWWWB   ",
            "  BWWWWB                                                                     BWWWWB  ",
            "  BWWWB                                                                       BWWWB  ",
            "  BWWWB                                                                       BWWWB  ",
            " BWWWWB                                                                       BWWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWWB                                                                       BWWWWB ",
            "  BWWWB                                                                       BWWWB  ",
            "  BWWWB                                                                       BWWWB  ",
            "  BWWWWB                                                                     BWWWWB  ",
            "   BWWWB                                                                     BWWWB   ",
            "   BWWWWB                                                                   BWWWWB   ",
            "    BWWWB                                                                   BWWWB    ",
            "    BWWWWB                                                                 BWWWWB    ",
            "     BWWWB                                                                 BWWWB     ",
            "     BWWWWB                                                               BWWWWB     ",
            "      BWWWB                                                               BWWWB      ",
            "      BWWWWB                                                             BWWWWB      ",
            "       BWWWWB                                                           BWWWWB       ",
            "        BWWWWB                                                         BWWWWB        ",
            "        BWWWWB                                                         BWWWWB        ",
            "         BWWWWB                                                       BWWWWB         ",
            "          BWWWWB                                                     BWWWWB          ",
            "           BWWWWB                                                   BWWWWB           ",
            "            BWWWWBB                                               BBWWWWB            ",
            "             BWWWWWB                                             BWWWWWB             ",
            "              BWWWWWB                                           BWWWWWB              ",
            "               BWWWWWBB                                       BBWWWWWB               ",
            "                BWWWWWWBB                                   BBWWWWWWB                ",
            "                 BBWWWWWWBB                               BBWWWWWWBB                 ",
            "                   BWWWWWWWBB                           BBWWWWWWWB                   ",
            "                    BBWWWWWWWBBB                     BBBWWWWWWWBB                    ",
            "                      BBWWWWWWWWBBBB             BBBBWWWWWWWWBB                      ",
            "                        BBWWWWWWWWWWBBBBBBBBBBBBBWWWWWWWWWWBB                        ",
            "                          BBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBB                          ",
            "                            BBBWWWWWWWWWWWWWWWWWWWWWWWBBB                            ",
            "                               BBBBBWWWWWWWWWWWWWBBBBB                               ",
            "                                    BBBBBBBBBBBBB                                    "
        },
        {
            "                                                                                     ",
            "                                    BBBB     BBBB                                    ",
            "                               BBBBBBBBB     BBBBBBBBB                               ",
            "                            BBBBBBBBBBBB     BBBBBBBBBBBB                            ",
            "                          BBBBBBBBBB             BBBBBBBBBB                          ",
            "                        BBBBBBBB                     BBBBBBBB                        ",
            "                      BBBBBBB                           BBBBBBB                      ",
            "                    BBBBBBB                               BBBBBBB                    ",
            "                   BBBBBB                                   BBBBBB                   ",
            "                 BBBBBB                                       BBBBBB                 ",
            "                BBBBB                                           BBBBB                ",
            "               BBBBB                                             BBBBB               ",
            "              BBBBB                                               BBBBB              ",
            "             BBBB                                                   BBBB             ",
            "            BBBB                                                     BBBB            ",
            "           BBBB                                                       BBBB           ",
            "          BBBB                                                         BBBB          ",
            "         BBBB                                                           BBBB         ",
            "         BBBB                                                           BBBB         ",
            "        BBBB                                                             BBBB        ",
            "       BBBB                                                               BBBB       ",
            "       BBB                                                                 BBB       ",
            "      BBBB                                                                 BBBB      ",
            "      BBB                                                                   BBB      ",
            "     BBBB                                                                   BBBB     ",
            "     BBB                                                                     BBB     ",
            "    BBBB                                                                     BBBB    ",
            "    BBB                                                                       BBB    ",
            "   BBBB                                                                       BBBB   ",
            "   BBB                                                                         BBB   ",
            "   BBB                                                                         BBB   ",
            "  BBBB                                                                         BBBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBBB                                                                         BBBB  ",
            "   BBB                                                                         BBB   ",
            "   BBB                                                                         BBB   ",
            "   BBBB                                                                       BBBB   ",
            "    BBB                                                                       BBB    ",
            "    BBBB                                                                     BBBB    ",
            "     BBB                                                                     BBB     ",
            "     BBBB                                                                   BBBB     ",
            "      BBB                                                                   BBB      ",
            "      BBBB                                                                 BBBB      ",
            "       BBB                                                                 BBB       ",
            "       BBBB                                                               BBBB       ",
            "        BBBB                                                             BBBB        ",
            "         BBBB                                                           BBBB         ",
            "         BBBB                                                           BBBB         ",
            "          BBBB                                                         BBBB          ",
            "           BBBB                                                       BBBB           ",
            "            BBBB                                                     BBBB            ",
            "             BBBB                                                   BBBB             ",
            "              BBBBB                                               BBBBB              ",
            "               BBBBB                                             BBBBB               ",
            "                BBBBB                                           BBBBB                ",
            "                 BBBBBB                                       BBBBBB                 ",
            "                   BBBBBB                                   BBBBBB                   ",
            "                    BBBBBBB                               BBBBBBB                    ",
            "                      BBBBBBB                           BBBBBBB                      ",
            "                        BBBBBBBB                     BBBBBBBB                        ",
            "                          BBBBBBBBBB             BBBBBBBBBB                          ",
            "                            BBBBBBBBBBBBBBBBBBBBBBBBBBBBB                            ",
            "                               BBBBBBBBBBBBBBBBBBBBBBB                               ",
            "                                    BBBBBBBBBBBBB                                    ",
            "                                                                                     "
        }
    });
}
