package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_6 {
    public static final String[][] CYCLOTRON_SHAPE_6_IDENTITY = transpose(new String[][] {
        {
            "                                                                                               ",
            "                                         BBBB     BBBB                                         ",
            "                                    BBBBBBBBB     BBBBBBBBB                                    ",
            "                                BBBBBBBBBBBBB     BBBBBBBBBBBBB                                ",
            "                              BBBBBBBBBBB             BBBBBBBBBBB                              ",
            "                           BBBBBBBBB                       BBBBBBBBB                           ",
            "                         BBBBBBBB                             BBBBBBBB                         ",
            "                        BBBBBBB                                 BBBBBBB                        ",
            "                      BBBBBB                                       BBBBBB                      ",
            "                     BBBBB                                           BBBBB                     ",
            "                   BBBBBB                                             BBBBBB                   ",
            "                  BBBBB                                                 BBBBB                  ",
            "                 BBBBB                                                   BBBBB                 ",
            "                BBBBB                                                     BBBBB                ",
            "               BBBB                                                         BBBB               ",
            "              BBBB                                                           BBBB              ",
            "             BBBB                                                             BBBB             ",
            "            BBBB                                                               BBBB            ",
            "           BBBB                                                                 BBBB           ",
            "          BBBB                                                                   BBBB          ",
            "          BBBB                                                                   BBBB          ",
            "         BBBB                                                                     BBBB         ",
            "        BBBB                                                                       BBBB        ",
            "        BBB                                                                         BBB        ",
            "       BBBB                                                                         BBBB       ",
            "      BBBB                                                                           BBBB      ",
            "      BBB                                                                             BBB      ",
            "     BBBB                                                                             BBBB     ",
            "     BBB                                                                               BBB     ",
            "     BBB                                                                               BBB     ",
            "    BBBB                                                                               BBBB    ",
            "    BBB                                                                                 BBB    ",
            "   BBBB                                                                                 BBBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBBB                                                                                 BBBB   ",
            "    BBB                                                                                 BBB    ",
            "    BBBB                                                                               BBBB    ",
            "     BBB                                                                               BBB     ",
            "     BBB                                                                               BBB     ",
            "     BBBB                                                                             BBBB     ",
            "      BBB                                                                             BBB      ",
            "      BBBB                                                                           BBBB      ",
            "       BBBB                                                                         BBBB       ",
            "        BBB                                                                         BBB        ",
            "        BBBB                                                                       BBBB        ",
            "         BBBB                                                                     BBBB         ",
            "          BBBB                                                                   BBBB          ",
            "          BBBB                                                                   BBBB          ",
            "           BBBB                                                                 BBBB           ",
            "            BBBB                                                               BBBB            ",
            "             BBBB                                                             BBBB             ",
            "              BBBB                                                           BBBB              ",
            "               BBBB                                                         BBBB               ",
            "                BBBBB                                                     BBBBB                ",
            "                 BBBBB                                                   BBBBB                 ",
            "                  BBBBB                                                 BBBBB                  ",
            "                   BBBBBB                                             BBBBBB                   ",
            "                     BBBBB                                           BBBBB                     ",
            "                      BBBBBB                                       BBBBBB                      ",
            "                        BBBBBBB                                 BBBBBBB                        ",
            "                         BBBBBBBB                             BBBBBBBB                         ",
            "                           BBBBBBBBB                       BBBBBBBBB                           ",
            "                              BBBBBBBBBBB             BBBBBBBBBBB                              ",
            "                                BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                ",
            "                                    BBBBBBBBBBBBBBBBBBBBBBB                                    ",
            "                                         BBBBBBBBBBBBB                                         ",
            "                                                                                               "
        },
        {
            "                                         BBBB     BBBB                                         ",
            "                                    BBBBBWWWW     WWWWBBBBB                                    ",
            "                                BBBBWWWWWWWWW     WWWWWWWWWBBBB                                ",
            "                              BBWWWWWWWWWWWWW     WWWWWWWWWWWWWBB                              ",
            "                           BBBWWWWWWWWWWWBBBB     BBBBWWWWWWWWWWWBBB                           ",
            "                         BBWWWWWWWWWBBBBB             BBBBBWWWWWWWWWBB                         ",
            "                        BWWWWWWWWBBB                       BBBWWWWWWWWB                        ",
            "                      BBWWWWWWWBB                             BBWWWWWWWBB                      ",
            "                     BWWWWWWBBB                                 BBBWWWWWWB                     ",
            "                   BBWWWWWBB                                       BBWWWWWBB                   ",
            "                  BWWWWWWB                                           BWWWWWWB                  ",
            "                 BWWWWWBB                                             BBWWWWWB                 ",
            "                BWWWWWB                                                 BWWWWWB                ",
            "               BWWWWWB                                                   BWWWWWB               ",
            "              BWWWWBB                                                     BBWWWWB              ",
            "             BWWWWB                                                         BWWWWB             ",
            "            BWWWWB                                                           BWWWWB            ",
            "           BWWWWB                                                             BWWWWB           ",
            "          BWWWWB                                                               BWWWWB          ",
            "         BWWWWB                                                                 BWWWWB         ",
            "         BWWWWB                                                                 BWWWWB         ",
            "        BWWWWB                                                                   BWWWWB        ",
            "       BWWWWB                                                                     BWWWWB       ",
            "       BWWWB                                                                       BWWWB       ",
            "      BWWWWB                                                                       BWWWWB      ",
            "     BWWWWB                                                                         BWWWWB     ",
            "     BWWWB                                                                           BWWWB     ",
            "    BWWWWB                                                                           BWWWWB    ",
            "    BWWWB                                                                             BWWWB    ",
            "    BWWWB                                                                             BWWWB    ",
            "   BWWWWB                                                                             BWWWWB   ",
            "   BWWWB                                                                               BWWWB   ",
            "  BWWWWB                                                                               BWWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWWB                                                                               BWWWWB  ",
            "   BWWWB                                                                               BWWWB   ",
            "   BWWWWB                                                                             BWWWWB   ",
            "    BWWWB                                                                             BWWWB    ",
            "    BWWWB                                                                             BWWWB    ",
            "    BWWWWB                                                                           BWWWWB    ",
            "     BWWWB                                                                           BWWWB     ",
            "     BWWWWB                                                                         BWWWWB     ",
            "      BWWWWB                                                                       BWWWWB      ",
            "       BWWWB                                                                       BWWWB       ",
            "       BWWWWB                                                                     BWWWWB       ",
            "        BWWWWB                                                                   BWWWWB        ",
            "         BWWWWB                                                                 BWWWWB         ",
            "         BWWWWB                                                                 BWWWWB         ",
            "          BWWWWB                                                               BWWWWB          ",
            "           BWWWWB                                                             BWWWWB           ",
            "            BWWWWB                                                           BWWWWB            ",
            "             BWWWWB                                                         BWWWWB             ",
            "              BWWWWBB                                                     BBWWWWB              ",
            "               BWWWWWB                                                   BWWWWWB               ",
            "                BWWWWWB                                                 BWWWWWB                ",
            "                 BWWWWWBB                                             BBWWWWWB                 ",
            "                  BWWWWWWB                                           BWWWWWWB                  ",
            "                   BBWWWWWBB                                       BBWWWWWBB                   ",
            "                     BWWWWWWBBB                                 BBBWWWWWWB                     ",
            "                      BBWWWWWWWBB                             BBWWWWWWWBB                      ",
            "                        BWWWWWWWWBBB                       BBBWWWWWWWWB                        ",
            "                         BBWWWWWWWWWBBBBB             BBBBBWWWWWWWWWBB                         ",
            "                           BBBWWWWWWWWWWWBBBBBBBBBBBBBWWWWWWWWWWWBBB                           ",
            "                              BBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBB                              ",
            "                                BBBBWWWWWWWWWWWWWWWWWWWWWWWBBBB                                ",
            "                                    BBBBBWWWWWWWWWWWWWBBBBB                                    ",
            "                                         BBBBBBBBBBBBB                                         "
        },
        {
            "                                         BBBB     BBBB                                         ",
            "                                    BBBBBWWWW  ~  WWWWBBBBB                                    ",
            "                                BBBBWWWWW-------------WWWWWBBBB                                ",
            "                              BBWWWW-----WWWW     WWWW-----WWWWBB                              ",
            "                           BBBWWW---WWWWWBBBB     BBBBWWWWW---WWWBBB                           ",
            "                         BBWWW---WWWBBBBB             BBBBBWWW---WWWBB                         ",
            "                        BWWW--WWWBBB                       BBBWWW--WWWB                        ",
            "                      BBWW--WWWBB                             BBWWW--WWBB                      ",
            "                     BWW--WWBBB                                 BBBWW--WWB                     ",
            "                   BBWW-WWBB                                       BBWW-WWBB                   ",
            "                  BWW--WWB                                           BWW--WWB                  ",
            "                 BWW-WWBB                                             BBWW-WWB                 ",
            "                BWW-WWB                                                 BWW-WWB                ",
            "               BW--WWB                                                   BWW--WB               ",
            "              BW-WWBB                                                     BBWW-WB              ",
            "             BW-WWB                                                         BWW-WB             ",
            "            BW-WWB                                                           BWW-WB            ",
            "           BW-WWB                                                             BWW-WB           ",
            "          BWW-WB                                                               BW-WWB          ",
            "         BWW-WB                                                                 BW-WWB         ",
            "         BW-WWB                                                                 BWW-WB         ",
            "        BW-WWB                                                                   BWW-WB        ",
            "       BWW-WB                                                                     BW-WWB       ",
            "       BW-WB                                                                       BW-WB       ",
            "      BW-WWB                                                                       BWW-WB      ",
            "     BWW-WB                                                                         BW-WWB     ",
            "     BW-WB                                                                           BW-WB     ",
            "    BWW-WB                                                                           BW-WWB    ",
            "    BW-WB                                                                             BW-WB    ",
            "    BW-WB                                                                             BW-WB    ",
            "   BW-WWB                                                                             BWW-WB   ",
            "   BW-WB                                                                               BW-WB   ",
            "  BWW-WB                                                                               BW-WWB  ",
            "  BW-WB                                                                                 BW-WB  ",
            "  BW-WB                                                                                 BW-WB  ",
            "  BW-WB                                                                                 BW-WB  ",
            " BW-WB                                                                                   BW-WB ",
            " BW-WB                                                                                   BW-WB ",
            " BW-WB                                                                                   BW-WB ",
            " BW-WB                                                                                   BW-WB ",
            " BW-WB                                                                                   BW-WB ",
            "BW-WB                                                                                     BW-WB",
            "BW-WB                                                                                     BW-WB",
            "BW-WB                                                                                     BW-WB",
            "BW-WB                                                                                     BW-WB",
            "BW-WB                                                                                     BW-WB",
            "BW-WB                                                                                     BW-WB",
            "BW-WB                                                                                     BW-WB",
            "BW-WB                                                                                     BW-WB",
            "BW-WB                                                                                     BW-WB",
            "BW-WB                                                                                     BW-WB",
            "BW-WB                                                                                     BW-WB",
            "BW-WB                                                                                     BW-WB",
            "BW-WB                                                                                     BW-WB",
            " BW-WB                                                                                   BW-WB ",
            " BW-WB                                                                                   BW-WB ",
            " BW-WB                                                                                   BW-WB ",
            " BW-WB                                                                                   BW-WB ",
            " BW-WB                                                                                   BW-WB ",
            "  BW-WB                                                                                 BW-WB  ",
            "  BW-WB                                                                                 BW-WB  ",
            "  BW-WB                                                                                 BW-WB  ",
            "  BWW-WB                                                                               BW-WWB  ",
            "   BW-WB                                                                               BW-WB   ",
            "   BW-WWB                                                                             BWW-WB   ",
            "    BW-WB                                                                             BW-WB    ",
            "    BW-WB                                                                             BW-WB    ",
            "    BWW-WB                                                                           BW-WWB    ",
            "     BW-WB                                                                           BW-WB     ",
            "     BWW-WB                                                                         BW-WWB     ",
            "      BW-WWB                                                                       BWW-WB      ",
            "       BW-WB                                                                       BW-WB       ",
            "       BWW-WB                                                                     BW-WWB       ",
            "        BW-WWB                                                                   BWW-WB        ",
            "         BW-WWB                                                                 BWW-WB         ",
            "         BWW-WB                                                                 BW-WWB         ",
            "          BWW-WB                                                               BW-WWB          ",
            "           BW-WWB                                                             BWW-WB           ",
            "            BW-WWB                                                           BWW-WB            ",
            "             BW-WWB                                                         BWW-WB             ",
            "              BW-WWBB                                                     BBWW-WB              ",
            "               BW--WWB                                                   BWW--WB               ",
            "                BWW-WWB                                                 BWW-WWB                ",
            "                 BWW-WWBB                                             BBWW-WWB                 ",
            "                  BWW--WWB                                           BWW--WWB                  ",
            "                   BBWW-WWBB                                       BBWW-WWBB                   ",
            "                     BWW--WWBBB                                 BBBWW--WWB                     ",
            "                      BBWW--WWWBB                             BBWWW--WWBB                      ",
            "                        BWWW--WWWBBB                       BBBWWW--WWWB                        ",
            "                         BBWWW---WWWBBBBB             BBBBBWWW---WWWBB                         ",
            "                           BBBWWW---WWWWWBBBBBBBBBBBBBWWWWW---WWWBBB                           ",
            "                              BBWWWW-----WWWWWWWWWWWWW-----WWWWBB                              ",
            "                                BBBBWWWWW-------------WWWWWBBBB                                ",
            "                                    BBBBBWWWWWWWWWWWWWBBBBB                                    ",
            "                                         BBBBBBBBBBBBB                                         "
        },
        {
            "                                         BBBB     BBBB                                         ",
            "                                    BBBBBWWWW     WWWWBBBBB                                    ",
            "                                BBBBWWWWWWWWW     WWWWWWWWWBBBB                                ",
            "                              BBWWWWWWWWWWWWW     WWWWWWWWWWWWWBB                              ",
            "                           BBBWWWWWWWWWWWBBBB     BBBBWWWWWWWWWWWBBB                           ",
            "                         BBWWWWWWWWWBBBBB             BBBBBWWWWWWWWWBB                         ",
            "                        BWWWWWWWWBBB                       BBBWWWWWWWWB                        ",
            "                      BBWWWWWWWBB                             BBWWWWWWWBB                      ",
            "                     BWWWWWWBBB                                 BBBWWWWWWB                     ",
            "                   BBWWWWWBB                                       BBWWWWWBB                   ",
            "                  BWWWWWWB                                           BWWWWWWB                  ",
            "                 BWWWWWBB                                             BBWWWWWB                 ",
            "                BWWWWWB                                                 BWWWWWB                ",
            "               BWWWWWB                                                   BWWWWWB               ",
            "              BWWWWBB                                                     BBWWWWB              ",
            "             BWWWWB                                                         BWWWWB             ",
            "            BWWWWB                                                           BWWWWB            ",
            "           BWWWWB                                                             BWWWWB           ",
            "          BWWWWB                                                               BWWWWB          ",
            "         BWWWWB                                                                 BWWWWB         ",
            "         BWWWWB                                                                 BWWWWB         ",
            "        BWWWWB                                                                   BWWWWB        ",
            "       BWWWWB                                                                     BWWWWB       ",
            "       BWWWB                                                                       BWWWB       ",
            "      BWWWWB                                                                       BWWWWB      ",
            "     BWWWWB                                                                         BWWWWB     ",
            "     BWWWB                                                                           BWWWB     ",
            "    BWWWWB                                                                           BWWWWB    ",
            "    BWWWB                                                                             BWWWB    ",
            "    BWWWB                                                                             BWWWB    ",
            "   BWWWWB                                                                             BWWWWB   ",
            "   BWWWB                                                                               BWWWB   ",
            "  BWWWWB                                                                               BWWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            "BWWWB                                                                                     BWWWB",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            " BWWWB                                                                                   BWWWB ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWB                                                                                 BWWWB  ",
            "  BWWWWB                                                                               BWWWWB  ",
            "   BWWWB                                                                               BWWWB   ",
            "   BWWWWB                                                                             BWWWWB   ",
            "    BWWWB                                                                             BWWWB    ",
            "    BWWWB                                                                             BWWWB    ",
            "    BWWWWB                                                                           BWWWWB    ",
            "     BWWWB                                                                           BWWWB     ",
            "     BWWWWB                                                                         BWWWWB     ",
            "      BWWWWB                                                                       BWWWWB      ",
            "       BWWWB                                                                       BWWWB       ",
            "       BWWWWB                                                                     BWWWWB       ",
            "        BWWWWB                                                                   BWWWWB        ",
            "         BWWWWB                                                                 BWWWWB         ",
            "         BWWWWB                                                                 BWWWWB         ",
            "          BWWWWB                                                               BWWWWB          ",
            "           BWWWWB                                                             BWWWWB           ",
            "            BWWWWB                                                           BWWWWB            ",
            "             BWWWWB                                                         BWWWWB             ",
            "              BWWWWBB                                                     BBWWWWB              ",
            "               BWWWWWB                                                   BWWWWWB               ",
            "                BWWWWWB                                                 BWWWWWB                ",
            "                 BWWWWWBB                                             BBWWWWWB                 ",
            "                  BWWWWWWB                                           BWWWWWWB                  ",
            "                   BBWWWWWBB                                       BBWWWWWBB                   ",
            "                     BWWWWWWBBB                                 BBBWWWWWWB                     ",
            "                      BBWWWWWWWBB                             BBWWWWWWWBB                      ",
            "                        BWWWWWWWWBBB                       BBBWWWWWWWWB                        ",
            "                         BBWWWWWWWWWBBBBB             BBBBBWWWWWWWWWBB                         ",
            "                           BBBWWWWWWWWWWWBBBBBBBBBBBBBWWWWWWWWWWWBBB                           ",
            "                              BBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBB                              ",
            "                                BBBBWWWWWWWWWWWWWWWWWWWWWWWBBBB                                ",
            "                                    BBBBBWWWWWWWWWWWWWBBBBB                                    ",
            "                                         BBBBBBBBBBBBB                                         "
        },
        {
            "                                                                                               ",
            "                                         BBBB     BBBB                                         ",
            "                                    BBBBBBBBB     BBBBBBBBB                                    ",
            "                                BBBBBBBBBBBBB     BBBBBBBBBBBBB                                ",
            "                              BBBBBBBBBBB             BBBBBBBBBBB                              ",
            "                           BBBBBBBBB                       BBBBBBBBB                           ",
            "                         BBBBBBBB                             BBBBBBBB                         ",
            "                        BBBBBBB                                 BBBBBBB                        ",
            "                      BBBBBB                                       BBBBBB                      ",
            "                     BBBBB                                           BBBBB                     ",
            "                   BBBBBB                                             BBBBBB                   ",
            "                  BBBBB                                                 BBBBB                  ",
            "                 BBBBB                                                   BBBBB                 ",
            "                BBBBB                                                     BBBBB                ",
            "               BBBB                                                         BBBB               ",
            "              BBBB                                                           BBBB              ",
            "             BBBB                                                             BBBB             ",
            "            BBBB                                                               BBBB            ",
            "           BBBB                                                                 BBBB           ",
            "          BBBB                                                                   BBBB          ",
            "          BBBB                                                                   BBBB          ",
            "         BBBB                                                                     BBBB         ",
            "        BBBB                                                                       BBBB        ",
            "        BBB                                                                         BBB        ",
            "       BBBB                                                                         BBBB       ",
            "      BBBB                                                                           BBBB      ",
            "      BBB                                                                             BBB      ",
            "     BBBB                                                                             BBBB     ",
            "     BBB                                                                               BBB     ",
            "     BBB                                                                               BBB     ",
            "    BBBB                                                                               BBBB    ",
            "    BBB                                                                                 BBB    ",
            "   BBBB                                                                                 BBBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            " BBB                                                                                       BBB ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "  BBB                                                                                     BBB  ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBB                                                                                   BBB   ",
            "   BBBB                                                                                 BBBB   ",
            "    BBB                                                                                 BBB    ",
            "    BBBB                                                                               BBBB    ",
            "     BBB                                                                               BBB     ",
            "     BBB                                                                               BBB     ",
            "     BBBB                                                                             BBBB     ",
            "      BBB                                                                             BBB      ",
            "      BBBB                                                                           BBBB      ",
            "       BBBB                                                                         BBBB       ",
            "        BBB                                                                         BBB        ",
            "        BBBB                                                                       BBBB        ",
            "         BBBB                                                                     BBBB         ",
            "          BBBB                                                                   BBBB          ",
            "          BBBB                                                                   BBBB          ",
            "           BBBB                                                                 BBBB           ",
            "            BBBB                                                               BBBB            ",
            "             BBBB                                                             BBBB             ",
            "              BBBB                                                           BBBB              ",
            "               BBBB                                                         BBBB               ",
            "                BBBBB                                                     BBBBB                ",
            "                 BBBBB                                                   BBBBB                 ",
            "                  BBBBB                                                 BBBBB                  ",
            "                   BBBBBB                                             BBBBBB                   ",
            "                     BBBBB                                           BBBBB                     ",
            "                      BBBBBB                                       BBBBBB                      ",
            "                        BBBBBBB                                 BBBBBBB                        ",
            "                         BBBBBBBB                             BBBBBBBB                         ",
            "                           BBBBBBBBB                       BBBBBBBBB                           ",
            "                              BBBBBBBBBBB             BBBBBBBBBBB                              ",
            "                                BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                ",
            "                                    BBBBBBBBBBBBBBBBBBBBBBB                                    ",
            "                                         BBBBBBBBBBBBB                                         ",
            "                                                                                               "
        }
    });
}
