package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_4 {
    public static final String[][] CYCLOTRON_SHAPE_4_IDENTITY = transpose(new String[][] {
        {
            "                                                                           ",
            "                               BBBB     BBBB                               ",
            "                           BBBBBBBB     BBBBBBBB                           ",
            "                        BBBBBBBBBBB     BBBBBBBBBBB                        ",
            "                      BBBBBBBBBB           BBBBBBBBBB                      ",
            "                    BBBBBBBB                   BBBBBBBB                    ",
            "                  BBBBBBB                         BBBBBBB                  ",
            "                 BBBBBB                             BBBBBB                 ",
            "               BBBBBB                                 BBBBBB               ",
            "              BBBBB                                     BBBBB              ",
            "             BBBBB                                       BBBBB             ",
            "            BBBBB                                         BBBBB            ",
            "           BBBB                                             BBBB           ",
            "          BBBB                                               BBBB          ",
            "         BBBB                                                 BBBB         ",
            "        BBBB                                                   BBBB        ",
            "        BBBB                                                   BBBB        ",
            "       BBBB                                                     BBBB       ",
            "      BBBB                                                       BBBB      ",
            "      BBB                                                         BBB      ",
            "     BBBB                                                         BBBB     ",
            "     BBB                                                           BBB     ",
            "    BBBB                                                           BBBB    ",
            "    BBB                                                             BBB    ",
            "   BBBB                                                             BBBB   ",
            "   BBB                                                               BBB   ",
            "   BBB                                                               BBB   ",
            "  BBBB                                                               BBBB  ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            " BBBB                                                                 BBBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBBB                                                                 BBBB ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            "  BBBB                                                               BBBB  ",
            "   BBB                                                               BBB   ",
            "   BBB                                                               BBB   ",
            "   BBBB                                                             BBBB   ",
            "    BBB                                                             BBB    ",
            "    BBBB                                                           BBBB    ",
            "     BBB                                                           BBB     ",
            "     BBBB                                                         BBBB     ",
            "      BBB                                                         BBB      ",
            "      BBBB                                                       BBBB      ",
            "       BBBB                                                     BBBB       ",
            "        BBBB                                                   BBBB        ",
            "        BBBB                                                   BBBB        ",
            "         BBBB                                                 BBBB         ",
            "          BBBB                                               BBBB          ",
            "           BBBB                                             BBBB           ",
            "            BBBBB                                         BBBBB            ",
            "             BBBBB                                       BBBBB             ",
            "              BBBBB                                     BBBBB              ",
            "               BBBBBB                                 BBBBBB               ",
            "                 BBBBBB                             BBBBBB                 ",
            "                  BBBBBBB                         BBBBBBB                  ",
            "                    BBBBBBBB                   BBBBBBBB                    ",
            "                      BBBBBBBBBB           BBBBBBBBBB                      ",
            "                        BBBBBBBBBBBBBBBBBBBBBBBBBBB                        ",
            "                           BBBBBBBBBBBBBBBBBBBBB                           ",
            "                               BBBBBBBBBBBBB                               ",
            "                                                                           "
        },
        {
            "                               BBBB     BBBB                               ",
            "                           BBBBWWWW     WWWWBBBB                           ",
            "                        BBBWWWWWWWW     WWWWWWWWBBB                        ",
            "                      BBWWWWWWWWWWW     WWWWWWWWWWWBB                      ",
            "                    BBWWWWWWWWWWBBB     BBBWWWWWWWWWWBB                    ",
            "                  BBWWWWWWWWBBBB           BBBBWWWWWWWWBB                  ",
            "                 BWWWWWWWBBB                   BBBWWWWWWWB                 ",
            "               BBWWWWWWBB                         BBWWWWWWBB               ",
            "              BWWWWWWBB                             BBWWWWWWB              ",
            "             BWWWWWBB                                 BBWWWWWB             ",
            "            BWWWWWB                                     BWWWWWB            ",
            "           BWWWWWB                                       BWWWWWB           ",
            "          BWWWWBB                                         BBWWWWB          ",
            "         BWWWWB                                             BWWWWB         ",
            "        BWWWWB                                               BWWWWB        ",
            "       BWWWWB                                                 BWWWWB       ",
            "       BWWWWB                                                 BWWWWB       ",
            "      BWWWWB                                                   BWWWWB      ",
            "     BWWWWB                                                     BWWWWB     ",
            "     BWWWB                                                       BWWWB     ",
            "    BWWWWB                                                       BWWWWB    ",
            "    BWWWB                                                         BWWWB    ",
            "   BWWWWB                                                         BWWWWB   ",
            "   BWWWB                                                           BWWWB   ",
            "  BWWWWB                                                           BWWWWB  ",
            "  BWWWB                                                             BWWWB  ",
            "  BWWWB                                                             BWWWB  ",
            " BWWWWB                                                             BWWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            "BWWWWB                                                               BWWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWWB                                                               BWWWWB",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWWB                                                             BWWWWB ",
            "  BWWWB                                                             BWWWB  ",
            "  BWWWB                                                             BWWWB  ",
            "  BWWWWB                                                           BWWWWB  ",
            "   BWWWB                                                           BWWWB   ",
            "   BWWWWB                                                         BWWWWB   ",
            "    BWWWB                                                         BWWWB    ",
            "    BWWWWB                                                       BWWWWB    ",
            "     BWWWB                                                       BWWWB     ",
            "     BWWWWB                                                     BWWWWB     ",
            "      BWWWWB                                                   BWWWWB      ",
            "       BWWWWB                                                 BWWWWB       ",
            "       BWWWWB                                                 BWWWWB       ",
            "        BWWWWB                                               BWWWWB        ",
            "         BWWWWB                                             BWWWWB         ",
            "          BWWWWBB                                         BBWWWWB          ",
            "           BWWWWWB                                       BWWWWWB           ",
            "            BWWWWWB                                     BWWWWWB            ",
            "             BWWWWWBB                                 BBWWWWWB             ",
            "              BWWWWWWBB                             BBWWWWWWB              ",
            "               BBWWWWWWBB                         BBWWWWWWBB               ",
            "                 BWWWWWWWBBB                   BBBWWWWWWWB                 ",
            "                  BBWWWWWWWWBBBB           BBBBWWWWWWWWBB                  ",
            "                    BBWWWWWWWWWWBBBBBBBBBBBWWWWWWWWWWBB                    ",
            "                      BBWWWWWWWWWWWWWWWWWWWWWWWWWWWBB                      ",
            "                        BBBWWWWWWWWWWWWWWWWWWWWWBBB                        ",
            "                           BBBBWWWWWWWWWWWWWBBBB                           ",
            "                               BBBBBBBBBBBBB                               "
        },
        {
            "                               BBBB     BBBB                               ",
            "                           BBBBWWWW  ~  WWWWBBBB                           ",
            "                        BBBWWWWW-----------WWWWWBBB                        ",
            "                      BBWWW-----WWW     WWW-----WWWBB                      ",
            "                    BBWWW--WWWWWBBB     BBBWWWWW--WWWBB                    ",
            "                  BBWW---WWWBBBB           BBBBWWW---WWBB                  ",
            "                 BWW--WWWBBB                   BBBWWW--WWB                 ",
            "               BBWW-WWWBB                         BBWWW-WWBB               ",
            "              BWW--WWBB                             BBWW--WWB              ",
            "             BWW-WWBB                                 BBWW-WWB             ",
            "            BWW-WWB                                     BWW-WWB            ",
            "           BWW-WWB                                       BWW-WWB           ",
            "          BWW-WBB                                         BBW-WWB          ",
            "         BWW-WB                                             BW-WWB         ",
            "        BWW-WB                                               BW-WWB        ",
            "       BWW-WB                                                 BW-WWB       ",
            "       BW-WWB                                                 BWW-WB       ",
            "      BW-WWB                                                   BWW-WB      ",
            "     BWW-WB                                                     BW-WWB     ",
            "     BW-WB                                                       BW-WB     ",
            "    BW-WWB                                                       BWW-WB    ",
            "    BW-WB                                                         BW-WB    ",
            "   BW-WWB                                                         BWW-WB   ",
            "   BW-WB                                                           BW-WB   ",
            "  BWW-WB                                                           BW-WWB  ",
            "  BW-WB                                                             BW-WB  ",
            "  BW-WB                                                             BW-WB  ",
            " BW-WWB                                                             BWW-WB ",
            " BW-WB                                                               BW-WB ",
            " BW-WB                                                               BW-WB ",
            " BW-WB                                                               BW-WB ",
            "BWW-WB                                                               BW-WWB",
            "BW-WB                                                                 BW-WB",
            "BW-WB                                                                 BW-WB",
            "BW-WB                                                                 BW-WB",
            "BW-WB                                                                 BW-WB",
            "BW-WB                                                                 BW-WB",
            "BW-WB                                                                 BW-WB",
            "BW-WB                                                                 BW-WB",
            "BW-WB                                                                 BW-WB",
            "BW-WB                                                                 BW-WB",
            "BW-WB                                                                 BW-WB",
            "BW-WB                                                                 BW-WB",
            "BWW-WB                                                               BW-WWB",
            " BW-WB                                                               BW-WB ",
            " BW-WB                                                               BW-WB ",
            " BW-WB                                                               BW-WB ",
            " BW-WWB                                                             BWW-WB ",
            "  BW-WB                                                             BW-WB  ",
            "  BW-WB                                                             BW-WB  ",
            "  BWW-WB                                                           BW-WWB  ",
            "   BW-WB                                                           BW-WB   ",
            "   BW-WWB                                                         BWW-WB   ",
            "    BW-WB                                                         BW-WB    ",
            "    BW-WWB                                                       BWW-WB    ",
            "     BW-WB                                                       BW-WB     ",
            "     BWW-WB                                                     BW-WWB     ",
            "      BW-WWB                                                   BWW-WB      ",
            "       BW-WWB                                                 BWW-WB       ",
            "       BWW-WB                                                 BW-WWB       ",
            "        BWW-WB                                               BW-WWB        ",
            "         BWW-WB                                             BW-WWB         ",
            "          BWW-WBB                                         BBW-WWB          ",
            "           BWW-WWB                                       BWW-WWB           ",
            "            BWW-WWB                                     BWW-WWB            ",
            "             BWW-WWBB                                 BBWW-WWB             ",
            "              BWW--WWBB                             BBWW--WWB              ",
            "               BBWW-WWWBB                         BBWWW-WWBB               ",
            "                 BWW--WWWBBB                   BBBWWW--WWB                 ",
            "                  BBWW---WWWBBBB           BBBBWWW---WWBB                  ",
            "                    BBWWW--WWWWWBBBBBBBBBBBWWWWW--WWWBB                    ",
            "                      BBWWW-----WWWWWWWWWWW-----WWWBB                      ",
            "                        BBBWWWWW-----------WWWWWBBB                        ",
            "                           BBBBWWWWWWWWWWWWWBBBB                           ",
            "                               BBBBBBBBBBBBB                               "
        },
        {
            "                               BBBB     BBBB                               ",
            "                           BBBBWWWW     WWWWBBBB                           ",
            "                        BBBWWWWWWWW     WWWWWWWWBBB                        ",
            "                      BBWWWWWWWWWWW     WWWWWWWWWWWBB                      ",
            "                    BBWWWWWWWWWWBBB     BBBWWWWWWWWWWBB                    ",
            "                  BBWWWWWWWWBBBB           BBBBWWWWWWWWBB                  ",
            "                 BWWWWWWWBBB                   BBBWWWWWWWB                 ",
            "               BBWWWWWWBB                         BBWWWWWWBB               ",
            "              BWWWWWWBB                             BBWWWWWWB              ",
            "             BWWWWWBB                                 BBWWWWWB             ",
            "            BWWWWWB                                     BWWWWWB            ",
            "           BWWWWWB                                       BWWWWWB           ",
            "          BWWWWBB                                         BBWWWWB          ",
            "         BWWWWB                                             BWWWWB         ",
            "        BWWWWB                                               BWWWWB        ",
            "       BWWWWB                                                 BWWWWB       ",
            "       BWWWWB                                                 BWWWWB       ",
            "      BWWWWB                                                   BWWWWB      ",
            "     BWWWWB                                                     BWWWWB     ",
            "     BWWWB                                                       BWWWB     ",
            "    BWWWWB                                                       BWWWWB    ",
            "    BWWWB                                                         BWWWB    ",
            "   BWWWWB                                                         BWWWWB   ",
            "   BWWWB                                                           BWWWB   ",
            "  BWWWWB                                                           BWWWWB  ",
            "  BWWWB                                                             BWWWB  ",
            "  BWWWB                                                             BWWWB  ",
            " BWWWWB                                                             BWWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            "BWWWWB                                                               BWWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWB                                                                 BWWWB",
            "BWWWWB                                                               BWWWWB",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWB                                                               BWWWB ",
            " BWWWWB                                                             BWWWWB ",
            "  BWWWB                                                             BWWWB  ",
            "  BWWWB                                                             BWWWB  ",
            "  BWWWWB                                                           BWWWWB  ",
            "   BWWWB                                                           BWWWB   ",
            "   BWWWWB                                                         BWWWWB   ",
            "    BWWWB                                                         BWWWB    ",
            "    BWWWWB                                                       BWWWWB    ",
            "     BWWWB                                                       BWWWB     ",
            "     BWWWWB                                                     BWWWWB     ",
            "      BWWWWB                                                   BWWWWB      ",
            "       BWWWWB                                                 BWWWWB       ",
            "       BWWWWB                                                 BWWWWB       ",
            "        BWWWWB                                               BWWWWB        ",
            "         BWWWWB                                             BWWWWB         ",
            "          BWWWWBB                                         BBWWWWB          ",
            "           BWWWWWB                                       BWWWWWB           ",
            "            BWWWWWB                                     BWWWWWB            ",
            "             BWWWWWBB                                 BBWWWWWB             ",
            "              BWWWWWWBB                             BBWWWWWWB              ",
            "               BBWWWWWWBB                         BBWWWWWWBB               ",
            "                 BWWWWWWWBBB                   BBBWWWWWWWB                 ",
            "                  BBWWWWWWWWBBBB           BBBBWWWWWWWWBB                  ",
            "                    BBWWWWWWWWWWBBBBBBBBBBBWWWWWWWWWWBB                    ",
            "                      BBWWWWWWWWWWWWWWWWWWWWWWWWWWWBB                      ",
            "                        BBBWWWWWWWWWWWWWWWWWWWWWBBB                        ",
            "                           BBBBWWWWWWWWWWWWWBBBB                           ",
            "                               BBBBBBBBBBBBB                               "
        },
        {
            "                                                                           ",
            "                               BBBB     BBBB                               ",
            "                           BBBBBBBB     BBBBBBBB                           ",
            "                        BBBBBBBBBBB     BBBBBBBBBBB                        ",
            "                      BBBBBBBBBB           BBBBBBBBBB                      ",
            "                    BBBBBBBB                   BBBBBBBB                    ",
            "                  BBBBBBB                         BBBBBBB                  ",
            "                 BBBBBB                             BBBBBB                 ",
            "               BBBBBB                                 BBBBBB               ",
            "              BBBBB                                     BBBBB              ",
            "             BBBBB                                       BBBBB             ",
            "            BBBBB                                         BBBBB            ",
            "           BBBB                                             BBBB           ",
            "          BBBB                                               BBBB          ",
            "         BBBB                                                 BBBB         ",
            "        BBBB                                                   BBBB        ",
            "        BBBB                                                   BBBB        ",
            "       BBBB                                                     BBBB       ",
            "      BBBB                                                       BBBB      ",
            "      BBB                                                         BBB      ",
            "     BBBB                                                         BBBB     ",
            "     BBB                                                           BBB     ",
            "    BBBB                                                           BBBB    ",
            "    BBB                                                             BBB    ",
            "   BBBB                                                             BBBB   ",
            "   BBB                                                               BBB   ",
            "   BBB                                                               BBB   ",
            "  BBBB                                                               BBBB  ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            " BBBB                                                                 BBBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBB                                                                   BBB ",
            " BBBB                                                                 BBBB ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            "  BBB                                                                 BBB  ",
            "  BBBB                                                               BBBB  ",
            "   BBB                                                               BBB   ",
            "   BBB                                                               BBB   ",
            "   BBBB                                                             BBBB   ",
            "    BBB                                                             BBB    ",
            "    BBBB                                                           BBBB    ",
            "     BBB                                                           BBB     ",
            "     BBBB                                                         BBBB     ",
            "      BBB                                                         BBB      ",
            "      BBBB                                                       BBBB      ",
            "       BBBB                                                     BBBB       ",
            "        BBBB                                                   BBBB        ",
            "        BBBB                                                   BBBB        ",
            "         BBBB                                                 BBBB         ",
            "          BBBB                                               BBBB          ",
            "           BBBB                                             BBBB           ",
            "            BBBBB                                         BBBBB            ",
            "             BBBBB                                       BBBBB             ",
            "              BBBBB                                     BBBBB              ",
            "               BBBBBB                                 BBBBBB               ",
            "                 BBBBBB                             BBBBBB                 ",
            "                  BBBBBBB                         BBBBBBB                  ",
            "                    BBBBBBBB                   BBBBBBBB                    ",
            "                      BBBBBBBBBB           BBBBBBBBBB                      ",
            "                        BBBBBBBBBBBBBBBBBBBBBBBBBBB                        ",
            "                           BBBBBBBBBBBBBBBBBBBBB                           ",
            "                               BBBBBBBBBBBBB                               ",
            "                                                                           "
        }
    });
}
