package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_3 {
    public static final String[][] CYCLOTRON_SHAPE_3_IDENTITY = transpose(new String[][] {
        {
            "                                                                 ",
            "                           BBB     BBB                           ",
            "                       BBBBBBB     BBBBBBB                       ",
            "                    BBBBBBBBBB     BBBBBBBBBB                    ",
            "                  BBBBBBBBB           BBBBBBBBB                  ",
            "                BBBBBBB                   BBBBBBB                ",
            "               BBBBBB                       BBBBBB               ",
            "             BBBBBB                           BBBBBB             ",
            "            BBBBB                               BBBBB            ",
            "           BBBBB                                 BBBBB           ",
            "          BBBBB                                   BBBBB          ",
            "         BBBB                                       BBBB         ",
            "        BBBB                                         BBBB        ",
            "       BBBB                                           BBBB       ",
            "       BBBB                                           BBBB       ",
            "      BBBB                                             BBBB      ",
            "     BBBB                                               BBBB     ",
            "     BBB                                                 BBB     ",
            "    BBBB                                                 BBBB    ",
            "    BBB                                                   BBB    ",
            "   BBBB                                                   BBBB   ",
            "   BBB                                                     BBB   ",
            "   BBB                                                     BBB   ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "   BBB                                                     BBB   ",
            "   BBB                                                     BBB   ",
            "   BBBB                                                   BBBB   ",
            "    BBB                                                   BBB    ",
            "    BBBB                                                 BBBB    ",
            "     BBB                                                 BBB     ",
            "     BBBB                                               BBBB     ",
            "      BBBB                                             BBBB      ",
            "       BBBB                                           BBBB       ",
            "       BBBB                                           BBBB       ",
            "        BBBB                                         BBBB        ",
            "         BBBB                                       BBBB         ",
            "          BBBBB                                   BBBBB          ",
            "           BBBBB                                 BBBBB           ",
            "            BBBBB                               BBBBB            ",
            "             BBBBBB                           BBBBBB             ",
            "               BBBBBB                       BBBBBB               ",
            "                BBBBBBB                   BBBBBBB                ",
            "                  BBBBBBBBB           BBBBBBBBB                  ",
            "                    BBBBBBBBBBBBBBBBBBBBBBBBB                    ",
            "                       BBBBBBBBBBBBBBBBBBB                       ",
            "                           BBBBBBBBBBB                           ",
            "                                                                 "
        },
        {
            "                           BBB     BBB                           ",
            "                       BBBBWWW     WWWBBBB                       ",
            "                    BBBWWWWWWW     WWWWWWWBBB                    ",
            "                  BBWWWWWWWWWW     WWWWWWWWWWBB                  ",
            "                BBWWWWWWWWWBBB     BBBWWWWWWWWWBB                ",
            "               BWWWWWWWBBBB           BBBBWWWWWWWB               ",
            "             BBWWWWWWBB                   BBWWWWWWBB             ",
            "            BWWWWWWBB                       BBWWWWWWB            ",
            "           BWWWWWBB                           BBWWWWWB           ",
            "          BWWWWWB                               BWWWWWB          ",
            "         BWWWWWB                                 BWWWWWB         ",
            "        BWWWWBB                                   BBWWWWB        ",
            "       BWWWWB                                       BWWWWB       ",
            "      BWWWWB                                         BWWWWB      ",
            "      BWWWWB                                         BWWWWB      ",
            "     BWWWWB                                           BWWWWB     ",
            "    BWWWWB                                             BWWWWB    ",
            "    BWWWB                                               BWWWB    ",
            "   BWWWWB                                               BWWWWB   ",
            "   BWWWB                                                 BWWWB   ",
            "  BWWWWB                                                 BWWWWB  ",
            "  BWWWB                                                   BWWWB  ",
            "  BWWWB                                                   BWWWB  ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            "  BWWWB                                                   BWWWB  ",
            "  BWWWB                                                   BWWWB  ",
            "  BWWWWB                                                 BWWWWB  ",
            "   BWWWB                                                 BWWWB   ",
            "   BWWWWB                                               BWWWWB   ",
            "    BWWWB                                               BWWWB    ",
            "    BWWWWB                                             BWWWWB    ",
            "     BWWWWB                                           BWWWWB     ",
            "      BWWWWB                                         BWWWWB      ",
            "      BWWWWB                                         BWWWWB      ",
            "       BWWWWB                                       BWWWWB       ",
            "        BWWWWBB                                   BBWWWWB        ",
            "         BWWWWWB                                 BWWWWWB         ",
            "          BWWWWWB                               BWWWWWB          ",
            "           BWWWWWBB                           BBWWWWWB           ",
            "            BWWWWWWBB                       BBWWWWWWB            ",
            "             BBWWWWWWBB                   BBWWWWWWBB             ",
            "               BWWWWWWWBBBB           BBBBWWWWWWWB               ",
            "                BBWWWWWWWWWBBBBBBBBBBBWWWWWWWWWBB                ",
            "                  BBWWWWWWWWWWWWWWWWWWWWWWWWWBB                  ",
            "                    BBBWWWWWWWWWWWWWWWWWWWBBB                    ",
            "                       BBBBWWWWWWWWWWWBBBB                       ",
            "                           BBBBBBBBBBB                           "
        },
        {
            "                           BBB     BBB                           ",
            "                       BBBBWWW  ~  WWWBBBB                       ",
            "                    BBBWWWW-----------WWWWBBB                    ",
            "                  BBWWW----WWW     WWW----WWWBB                  ",
            "                BBWWW--WWWWBBB     BBBWWWW--WWWBB                ",
            "               BWW---WWBBBB           BBBBWW---WWB               ",
            "             BBWW-WWWBB                   BBWWW-WWBB             ",
            "            BWW--WWBB                       BBWW--WWB            ",
            "           BWW-WWBB                           BBWW-WWB           ",
            "          BWW-WWB                               BWW-WWB          ",
            "         BWW-WWB                                 BWW-WWB         ",
            "        BWW-WBB                                   BBW-WWB        ",
            "       BWW-WB                                       BW-WWB       ",
            "      BWW-WB                                         BW-WWB      ",
            "      BW-WWB                                         BWW-WB      ",
            "     BW-WWB                                           BWW-WB     ",
            "    BWW-WB                                             BW-WWB    ",
            "    BW-WB                                               BW-WB    ",
            "   BW-WWB                                               BWW-WB   ",
            "   BW-WB                                                 BW-WB   ",
            "  BWW-WB                                                 BW-WWB  ",
            "  BW-WB                                                   BW-WB  ",
            "  BW-WB                                                   BW-WB  ",
            " BW-WB                                                     BW-WB ",
            " BW-WB                                                     BW-WB ",
            " BW-WB                                                     BW-WB ",
            " BW-WB                                                     BW-WB ",
            "BW-WB                                                       BW-WB",
            "BW-WB                                                       BW-WB",
            "BW-WB                                                       BW-WB",
            "BW-WB                                                       BW-WB",
            "BW-WB                                                       BW-WB",
            "BW-WB                                                       BW-WB",
            "BW-WB                                                       BW-WB",
            "BW-WB                                                       BW-WB",
            "BW-WB                                                       BW-WB",
            "BW-WB                                                       BW-WB",
            "BW-WB                                                       BW-WB",
            " BW-WB                                                     BW-WB ",
            " BW-WB                                                     BW-WB ",
            " BW-WB                                                     BW-WB ",
            " BW-WB                                                     BW-WB ",
            "  BW-WB                                                   BW-WB  ",
            "  BW-WB                                                   BW-WB  ",
            "  BWW-WB                                                 BW-WWB  ",
            "   BW-WB                                                 BW-WB   ",
            "   BW-WWB                                               BWW-WB   ",
            "    BW-WB                                               BW-WB    ",
            "    BWW-WB                                             BW-WWB    ",
            "     BW-WWB                                           BWW-WB     ",
            "      BW-WWB                                         BWW-WB      ",
            "      BWW-WB                                         BW-WWB      ",
            "       BWW-WB                                       BW-WWB       ",
            "        BWW-WBB                                   BBW-WWB        ",
            "         BWW-WWB                                 BWW-WWB         ",
            "          BWW-WWB                               BWW-WWB          ",
            "           BWW-WWBB                           BBWW-WWB           ",
            "            BWW--WWBB                       BBWW--WWB            ",
            "             BBWW-WWWBB                   BBWWW-WWBB             ",
            "               BWW---WWBBBB           BBBBWW---WWB               ",
            "                BBWWW--WWWWBBBBBBBBBBBWWWW--WWWBB                ",
            "                  BBWWW----WWWWWWWWWWW----WWWBB                  ",
            "                    BBBWWWW-----------WWWWBBB                    ",
            "                       BBBBWWWWWWWWWWWBBBB                       ",
            "                           BBBBBBBBBBB                           "
        },
        {
            "                           BBB     BBB                           ",
            "                       BBBBWWW     WWWBBBB                       ",
            "                    BBBWWWWWWW     WWWWWWWBBB                    ",
            "                  BBWWWWWWWWWW     WWWWWWWWWWBB                  ",
            "                BBWWWWWWWWWBBB     BBBWWWWWWWWWBB                ",
            "               BWWWWWWWBBBB           BBBBWWWWWWWB               ",
            "             BBWWWWWWBB                   BBWWWWWWBB             ",
            "            BWWWWWWBB                       BBWWWWWWB            ",
            "           BWWWWWBB                           BBWWWWWB           ",
            "          BWWWWWB                               BWWWWWB          ",
            "         BWWWWWB                                 BWWWWWB         ",
            "        BWWWWBB                                   BBWWWWB        ",
            "       BWWWWB                                       BWWWWB       ",
            "      BWWWWB                                         BWWWWB      ",
            "      BWWWWB                                         BWWWWB      ",
            "     BWWWWB                                           BWWWWB     ",
            "    BWWWWB                                             BWWWWB    ",
            "    BWWWB                                               BWWWB    ",
            "   BWWWWB                                               BWWWWB   ",
            "   BWWWB                                                 BWWWB   ",
            "  BWWWWB                                                 BWWWWB  ",
            "  BWWWB                                                   BWWWB  ",
            "  BWWWB                                                   BWWWB  ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            "BWWWB                                                       BWWWB",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            " BWWWB                                                     BWWWB ",
            "  BWWWB                                                   BWWWB  ",
            "  BWWWB                                                   BWWWB  ",
            "  BWWWWB                                                 BWWWWB  ",
            "   BWWWB                                                 BWWWB   ",
            "   BWWWWB                                               BWWWWB   ",
            "    BWWWB                                               BWWWB    ",
            "    BWWWWB                                             BWWWWB    ",
            "     BWWWWB                                           BWWWWB     ",
            "      BWWWWB                                         BWWWWB      ",
            "      BWWWWB                                         BWWWWB      ",
            "       BWWWWB                                       BWWWWB       ",
            "        BWWWWBB                                   BBWWWWB        ",
            "         BWWWWWB                                 BWWWWWB         ",
            "          BWWWWWB                               BWWWWWB          ",
            "           BWWWWWBB                           BBWWWWWB           ",
            "            BWWWWWWBB                       BBWWWWWWB            ",
            "             BBWWWWWWBB                   BBWWWWWWBB             ",
            "               BWWWWWWWBBBB           BBBBWWWWWWWB               ",
            "                BBWWWWWWWWWBBBBBBBBBBBWWWWWWWWWBB                ",
            "                  BBWWWWWWWWWWWWWWWWWWWWWWWWWBB                  ",
            "                    BBBWWWWWWWWWWWWWWWWWWWBBB                    ",
            "                       BBBBWWWWWWWWWWWBBBB                       ",
            "                           BBBBBBBBBBB                           "
        },
        {
            "                                                                 ",
            "                           BBB     BBB                           ",
            "                       BBBBBBB     BBBBBBB                       ",
            "                    BBBBBBBBBB     BBBBBBBBBB                    ",
            "                  BBBBBBBBB           BBBBBBBBB                  ",
            "                BBBBBBB                   BBBBBBB                ",
            "               BBBBBB                       BBBBBB               ",
            "             BBBBBB                           BBBBBB             ",
            "            BBBBB                               BBBBB            ",
            "           BBBBB                                 BBBBB           ",
            "          BBBBB                                   BBBBB          ",
            "         BBBB                                       BBBB         ",
            "        BBBB                                         BBBB        ",
            "       BBBB                                           BBBB       ",
            "       BBBB                                           BBBB       ",
            "      BBBB                                             BBBB      ",
            "     BBBB                                               BBBB     ",
            "     BBB                                                 BBB     ",
            "    BBBB                                                 BBBB    ",
            "    BBB                                                   BBB    ",
            "   BBBB                                                   BBBB   ",
            "   BBB                                                     BBB   ",
            "   BBB                                                     BBB   ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            " BBB                                                         BBB ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "  BBB                                                       BBB  ",
            "   BBB                                                     BBB   ",
            "   BBB                                                     BBB   ",
            "   BBBB                                                   BBBB   ",
            "    BBB                                                   BBB    ",
            "    BBBB                                                 BBBB    ",
            "     BBB                                                 BBB     ",
            "     BBBB                                               BBBB     ",
            "      BBBB                                             BBBB      ",
            "       BBBB                                           BBBB       ",
            "       BBBB                                           BBBB       ",
            "        BBBB                                         BBBB        ",
            "         BBBB                                       BBBB         ",
            "          BBBBB                                   BBBBB          ",
            "           BBBBB                                 BBBBB           ",
            "            BBBBB                               BBBBB            ",
            "             BBBBBB                           BBBBBB             ",
            "               BBBBBB                       BBBBBB               ",
            "                BBBBBBB                   BBBBBBB                ",
            "                  BBBBBBBBB           BBBBBBBBB                  ",
            "                    BBBBBBBBBBBBBBBBBBBBBBBBB                    ",
            "                       BBBBBBBBBBBBBBBBBBB                       ",
            "                           BBBBBBBBBBB                           ",
            "                                                                 "
        }
    });
}
