package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_1 {
    public static final String[][] CYCLOTRON_SHAPE_1_IDENTITY = transpose(new String[][] {
        {
            "                                             ",
            "                  BB     BB                  ",
            "               BBBBB     BBBBB               ",
            "            BBBBBBBB     BBBBBBBB            ",
            "           BBBBBBB         BBBBBBB           ",
            "         BBBBBB               BBBBBB         ",
            "        BBBBB                   BBBBB        ",
            "       BBBBB                     BBBBB       ",
            "      BBBBB                       BBBBB      ",
            "     BBBBB                         BBBBB     ",
            "     BBBB                           BBBB     ",
            "    BBBB                             BBBB    ",
            "   BBBB                               BBBB   ",
            "   BBB                                 BBB   ",
            "   BBB                                 BBB   ",
            "  BBB                                   BBB  ",
            "  BBB                                   BBB  ",
            "  BBB                                   BBB  ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            "  BBB                                   BBB  ",
            "  BBB                                   BBB  ",
            "  BBB                                   BBB  ",
            "   BBB                                 BBB   ",
            "   BBB                                 BBB   ",
            "   BBBB                               BBBB   ",
            "    BBBB                             BBBB    ",
            "     BBBB                           BBBB     ",
            "     BBBBB                         BBBBB     ",
            "      BBBBB                       BBBBB      ",
            "       BBBBB                     BBBBB       ",
            "        BBBBB                   BBBBB        ",
            "         BBBBBB               BBBBBB         ",
            "           BBBBBBB         BBBBBBB           ",
            "            BBBBBBBBBBBBBBBBBBBBB            ",
            "               BBBBBBBBBBBBBBB               ",
            "                  BBBBBBBBB                  ",
            "                                             "
        },
        {
            "                  BB     BB                  ",
            "               BBBWW     WWBBB               ",
            "            BBBWWWWW     WWWWWBBB            ",
            "           BWWWWWWWW     WWWWWWWWB           ",
            "         BBWWWWWWWBB     BBWWWWWWWBB         ",
            "        BWWWWWWBBB         BBBWWWWWWB        ",
            "       BWWWWWBB               BBWWWWWB       ",
            "      BWWWWWB                   BWWWWWB      ",
            "     BWWWWWB                     BWWWWWB     ",
            "    BWWWWWB                       BWWWWWB    ",
            "    BWWWWB                         BWWWWB    ",
            "   BWWWWB                           BWWWWB   ",
            "  BWWWWB                             BWWWWB  ",
            "  BWWWB                               BWWWB  ",
            "  BWWWB                               BWWWB  ",
            " BWWWB                                 BWWWB ",
            " BWWWB                                 BWWWB ",
            " BWWWB                                 BWWWB ",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            " BWWWB                                 BWWWB ",
            " BWWWB                                 BWWWB ",
            " BWWWB                                 BWWWB ",
            "  BWWWB                               BWWWB  ",
            "  BWWWB                               BWWWB  ",
            "  BWWWWB                             BWWWWB  ",
            "   BWWWWB                           BWWWWB   ",
            "    BWWWWB                         BWWWWB    ",
            "    BWWWWWB                       BWWWWWB    ",
            "     BWWWWWB                     BWWWWWB     ",
            "      BWWWWWB                   BWWWWWB      ",
            "       BWWWWWBB               BBWWWWWB       ",
            "        BWWWWWWBBB         BBBWWWWWWB        ",
            "         BBWWWWWWWBBBBBBBBBWWWWWWWBB         ",
            "           BWWWWWWWWWWWWWWWWWWWWWB           ",
            "            BBBWWWWWWWWWWWWWWWBBB            ",
            "               BBBWWWWWWWWWBBB               ",
            "                  BBBBBBBBB                  "
        },
        {
            "                  BB     BB                  ",
            "               BBBWW  ~  WWBBB               ",
            "            BBBWWW---------WWWBBB            ",
            "           BWWW---WW     WW---WWWB           ",
            "         BBWW--WWWBB     BBWWW--WWBB         ",
            "        BWW--WWBBB         BBBWW--WWB        ",
            "       BWW-WWBB               BBWW-WWB       ",
            "      BWW-WWB                   BWW-WWB      ",
            "     BWW-WWB                     BWW-WWB     ",
            "    BWW-WWB                       BWW-WWB    ",
            "    BW-WWB                         BWW-WB    ",
            "   BW-WWB                           BWW-WB   ",
            "  BWW-WB                             BW-WWB  ",
            "  BW-WB                               BW-WB  ",
            "  BW-WB                               BW-WB  ",
            " BW-WB                                 BW-WB ",
            " BW-WB                                 BW-WB ",
            " BW-WB                                 BW-WB ",
            "BW-WB                                   BW-WB",
            "BW-WB                                   BW-WB",
            "BW-WB                                   BW-WB",
            "BW-WB                                   BW-WB",
            "BW-WB                                   BW-WB",
            "BW-WB                                   BW-WB",
            "BW-WB                                   BW-WB",
            "BW-WB                                   BW-WB",
            "BW-WB                                   BW-WB",
            " BW-WB                                 BW-WB ",
            " BW-WB                                 BW-WB ",
            " BW-WB                                 BW-WB ",
            "  BW-WB                               BW-WB  ",
            "  BW-WB                               BW-WB  ",
            "  BWW-WB                             BW-WWB  ",
            "   BW-WWB                           BWW-WB   ",
            "    BW-WWB                         BWW-WB    ",
            "    BWW-WWB                       BWW-WWB    ",
            "     BWW-WWB                     BWW-WWB     ",
            "      BWW-WWB                   BWW-WWB      ",
            "       BWW-WWBB               BBWW-WWB       ",
            "        BWW--WWBBB         BBBWW--WWB        ",
            "         BBWW--WWWBBBBBBBBBWWW--WWBB         ",
            "           BWWW---WWWWWWWWW---WWWB           ",
            "            BBBWWW---------WWWBBB            ",
            "               BBBWWWWWWWWWBBB               ",
            "                  BBBBBBBBB                  "
        },
        {
            "                  BB     BB                  ",
            "               BBBWW     WWBBB               ",
            "            BBBWWWWW     WWWWWBBB            ",
            "           BWWWWWWWW     WWWWWWWWB           ",
            "         BBWWWWWWWBB     BBWWWWWWWBB         ",
            "        BWWWWWWBBB         BBBWWWWWWB        ",
            "       BWWWWWBB               BBWWWWWB       ",
            "      BWWWWWB                   BWWWWWB      ",
            "     BWWWWWB                     BWWWWWB     ",
            "    BWWWWWB                       BWWWWWB    ",
            "    BWWWWB                         BWWWWB    ",
            "   BWWWWB                           BWWWWB   ",
            "  BWWWWB                             BWWWWB  ",
            "  BWWWB                               BWWWB  ",
            "  BWWWB                               BWWWB  ",
            " BWWWB                                 BWWWB ",
            " BWWWB                                 BWWWB ",
            " BWWWB                                 BWWWB ",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            "BWWWB                                   BWWWB",
            " BWWWB                                 BWWWB ",
            " BWWWB                                 BWWWB ",
            " BWWWB                                 BWWWB ",
            "  BWWWB                               BWWWB  ",
            "  BWWWB                               BWWWB  ",
            "  BWWWWB                             BWWWWB  ",
            "   BWWWWB                           BWWWWB   ",
            "    BWWWWB                         BWWWWB    ",
            "    BWWWWWB                       BWWWWWB    ",
            "     BWWWWWB                     BWWWWWB     ",
            "      BWWWWWB                   BWWWWWB      ",
            "       BWWWWWBB               BBWWWWWB       ",
            "        BWWWWWWBBB         BBBWWWWWWB        ",
            "         BBWWWWWWWBBBBBBBBBWWWWWWWBB         ",
            "           BWWWWWWWWWWWWWWWWWWWWWB           ",
            "            BBBWWWWWWWWWWWWWWWBBB            ",
            "               BBBWWWWWWWWWBBB               ",
            "                  BBBBBBBBB                  "
        },
        {
            "                                             ",
            "                  BB     BB                  ",
            "               BBBBB     BBBBB               ",
            "            BBBBBBBB     BBBBBBBB            ",
            "           BBBBBBB         BBBBBBB           ",
            "         BBBBBB               BBBBBB         ",
            "        BBBBB                   BBBBB        ",
            "       BBBBB                     BBBBB       ",
            "      BBBBB                       BBBBB      ",
            "     BBBBB                         BBBBB     ",
            "     BBBB                           BBBB     ",
            "    BBBB                             BBBB    ",
            "   BBBB                               BBBB   ",
            "   BBB                                 BBB   ",
            "   BBB                                 BBB   ",
            "  BBB                                   BBB  ",
            "  BBB                                   BBB  ",
            "  BBB                                   BBB  ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            " BBB                                     BBB ",
            "  BBB                                   BBB  ",
            "  BBB                                   BBB  ",
            "  BBB                                   BBB  ",
            "   BBB                                 BBB   ",
            "   BBB                                 BBB   ",
            "   BBBB                               BBBB   ",
            "    BBBB                             BBBB    ",
            "     BBBB                           BBBB     ",
            "     BBBBB                         BBBBB     ",
            "      BBBBB                       BBBBB      ",
            "       BBBBB                     BBBBB       ",
            "        BBBBB                   BBBBB        ",
            "         BBBBBB               BBBBBB         ",
            "           BBBBBBB         BBBBBBB           ",
            "            BBBBBBBBBBBBBBBBBBBBB            ",
            "               BBBBBBBBBBBBBBB               ",
            "                  BBBBBBBBB                  ",
            "                                             "
        }
    });
}
