package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

public abstract class CYCLOTRON_SHAPE_FILE_5 {
    public static final String[][] CYCLOTRON_SHAPE_5_IDENTITY = transpose(new String[][] {
        {
            "                                                                                   ",
            "                                   AAAAAAAAAAAAA                                   ",
            "                               AAAA             AAAA                               ",
            "                            AAA                     AAA                            ",
            "                         AAA                           AAA                         ",
            "                       AA                                 AA                       ",
            "                     AA                                     AA                     ",
            "                    A                                         A                    ",
            "                  AA                                           AA                  ",
            "                 A                                               A                 ",
            "                A                                                 A                ",
            "              AA                                                   AA              ",
            "             A                                                       A             ",
            "            A                                                         A            ",
            "           A                                                           A           ",
            "           A                                                           A           ",
            "          A                                                             A          ",
            "         A                                                               A         ",
            "        A                                                                 A        ",
            "        A                                                                 A        ",
            "       A                                                                   A       ",
            "      A                                                                     A      ",
            "      A                                                                     A      ",
            "     A                                                                       A     ",
            "     A                                                                       A     ",
            "    A                                                                         A    ",
            "    A                                                                         A    ",
            "    A                                                                         A    ",
            "   A                                                                           A   ",
            "   A                                                                           A   ",
            "   A                                                                           A   ",
            "  A                                                                             A  ",
            "  A                                                                             A  ",
            "  A                                                                             A  ",
            "  A                                                                             A  ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            "  A                                                                             A  ",
            "  A                                                                             A  ",
            "  A                                                                             A  ",
            "  A                                                                             A  ",
            "   A                                                                           A   ",
            "   A                                                                           A   ",
            "   A                                                                           A   ",
            "    A                                                                         A    ",
            "    A                                                                         A    ",
            "    A                                                                         A    ",
            "     A                                                                       A     ",
            "     A                                                                       A     ",
            "      A                                                                     A      ",
            "      A                                                                     A      ",
            "       A                                                                   A       ",
            "        A                                                                 A        ",
            "        A                                                                 A        ",
            "         A                                                               A         ",
            "          A                                                             A          ",
            "           A                                                           A           ",
            "           A                                                           A           ",
            "            A                                                         A            ",
            "             A                                                       A             ",
            "              AA                                                   AA              ",
            "                A                                                 A                ",
            "                 A                                               A                 ",
            "                  AA                                           AA                  ",
            "                    A                                         A                    ",
            "                     AA                                     AA                     ",
            "                       AA                                 AA                       ",
            "                         AAA                           AAA                         ",
            "                            AAA                     AAA                            ",
            "                               AAAA             AAAA                               ",
            "                                   AAAAAAAAAAAAA                                   ",
            "                                                                                   "
        },
        {
            "                                   AAAAAA~AAAAAA                                   ",
            "                               AAAABBBBBBBBBBBBBAAAA                               ",
            "                           AAAABBBBAAAAAAAAAAAAABBBBAAAA                           ",
            "                         AAABBBAAAA             AAAABBBAAA                         ",
            "                       AABBBAAA                     AAABBBAA                       ",
            "                     AABBAAA                           AAABBAA                     ",
            "                   AABBAAA                               AAABBAA                   ",
            "                  AABAAA                                   AAABAA                  ",
            "                 ABBAA                                       AABBA                 ",
            "               AABAA                                           AABAA               ",
            "              AABAA                                             AABAA              ",
            "             ABBAA                                               AABBA             ",
            "            ABAA                                                   AABA            ",
            "           ABAA                                                     AABA           ",
            "          ABAA                                                       AABA          ",
            "         AABA                                                         ABAA         ",
            "         ABA                                                           ABA         ",
            "        ABAA                                                           AABA        ",
            "       ABAA                                                             AABA       ",
            "      AABA                                                               ABAA      ",
            "      ABA                                                                 ABA      ",
            "     ABAA                                                                 AABA     ",
            "     ABA                                                                   ABA     ",
            "    ABAA                                                                   AABA    ",
            "    ABA                                                                     ABA    ",
            "   ABAA                                                                     AABA   ",
            "   ABA                                                                       ABA   ",
            "  AABA                                                                       ABAA  ",
            "  ABA                                                                         ABA  ",
            "  ABA                                                                         ABA  ",
            "  ABA                                                                         ABA  ",
            " ABA                                                                           ABA ",
            " ABA                                                                           ABA ",
            " ABA                                                                           ABA ",
            " ABA                                                                           ABA ",
            "ABA                                                                             ABA",
            "ABA                                                                             ABA",
            "ABA                                                                             ABA",
            "ABA                                                                             ABA",
            "ABA                                                                             ABA",
            "ABA                                                                             ABA",
            "ABA                                                                             ABA",
            "ABA                                                                             ABA",
            "ABA                                                                             ABA",
            "ABA                                                                             ABA",
            "ABA                                                                             ABA",
            "ABA                                                                             ABA",
            "ABA                                                                             ABA",
            " ABA                                                                           ABA ",
            " ABA                                                                           ABA ",
            " ABA                                                                           ABA ",
            " ABA                                                                           ABA ",
            "  ABA                                                                         ABA  ",
            "  ABA                                                                         ABA  ",
            "  ABA                                                                         ABA  ",
            "  AABA                                                                       ABAA  ",
            "   ABA                                                                       ABA   ",
            "   ABAA                                                                     AABA   ",
            "    ABA                                                                     ABA    ",
            "    ABAA                                                                   AABA    ",
            "     ABA                                                                   ABA     ",
            "     ABAA                                                                 AABA     ",
            "      ABA                                                                 ABA      ",
            "      AABA                                                               ABAA      ",
            "       ABAA                                                             AABA       ",
            "        ABAA                                                           AABA        ",
            "         ABA                                                           ABA         ",
            "         AABA                                                         ABAA         ",
            "          ABAA                                                       AABA          ",
            "           ABAA                                                     AABA           ",
            "            ABAA                                                   AABA            ",
            "             ABBAA                                               AABBA             ",
            "              AABAA                                             AABAA              ",
            "               AABAA                                           AABAA               ",
            "                 ABBAA                                       AABBA                 ",
            "                  AABAAA                                   AAABAA                  ",
            "                   AABBAAA                               AAABBAA                   ",
            "                     AABBAAA                           AAABBAA                     ",
            "                       AABBBAAA                     AAABBBAA                       ",
            "                         AAABBBAAAA             AAAABBBAAA                         ",
            "                           AAAABBBBAAAAAAAAAAAAABBBBAAAA                           ",
            "                               AAAABBBBBBBBBBBBBAAAA                               ",
            "                                   AAAAAAAAAAAAA                                   "
        },
        {
            "                                                                                   ",
            "                                   AAAAAAAAAAAAA                                   ",
            "                               AAAA             AAAA                               ",
            "                            AAA                     AAA                            ",
            "                         AAA                           AAA                         ",
            "                       AA                                 AA                       ",
            "                     AA                                     AA                     ",
            "                    A                                         A                    ",
            "                  AA                                           AA                  ",
            "                 A                                               A                 ",
            "                A                                                 A                ",
            "              AA                                                   AA              ",
            "             A                                                       A             ",
            "            A                                                         A            ",
            "           A                                                           A           ",
            "           A                                                           A           ",
            "          A                                                             A          ",
            "         A                                                               A         ",
            "        A                                                                 A        ",
            "        A                                                                 A        ",
            "       A                                                                   A       ",
            "      A                                                                     A      ",
            "      A                                                                     A      ",
            "     A                                                                       A     ",
            "     A                                                                       A     ",
            "    A                                                                         A    ",
            "    A                                                                         A    ",
            "    A                                                                         A    ",
            "   A                                                                           A   ",
            "   A                                                                           A   ",
            "   A                                                                           A   ",
            "  A                                                                             A  ",
            "  A                                                                             A  ",
            "  A                                                                             A  ",
            "  A                                                                             A  ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            " A                                                                               A ",
            "  A                                                                             A  ",
            "  A                                                                             A  ",
            "  A                                                                             A  ",
            "  A                                                                             A  ",
            "   A                                                                           A   ",
            "   A                                                                           A   ",
            "   A                                                                           A   ",
            "    A                                                                         A    ",
            "    A                                                                         A    ",
            "    A                                                                         A    ",
            "     A                                                                       A     ",
            "     A                                                                       A     ",
            "      A                                                                     A      ",
            "      A                                                                     A      ",
            "       A                                                                   A       ",
            "        A                                                                 A        ",
            "        A                                                                 A        ",
            "         A                                                               A         ",
            "          A                                                             A          ",
            "           A                                                           A           ",
            "           A                                                           A           ",
            "            A                                                         A            ",
            "             A                                                       A             ",
            "              AA                                                   AA              ",
            "                A                                                 A                ",
            "                 A                                               A                 ",
            "                  AA                                           AA                  ",
            "                    A                                         A                    ",
            "                     AA                                     AA                     ",
            "                       AA                                 AA                       ",
            "                         AAA                           AAA                         ",
            "                            AAA                     AAA                            ",
            "                               AAAA             AAAA                               ",
            "                                   AAAAAAAAAAAAA                                   ",
            "                                                                                   "
        }
    });
}
