package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_9 {
    public static final String[][] CYCLOTRON_SHAPE_9_IDENTITY = transpose(new String[][] {
        {
            "                                                                                                                             ",
            "                                                       BBBBB     BBBBB                                                       ",
            "                                                 BBBBBBBBBBB     BBBBBBBBBBB                                                 ",
            "                                             BBBBBBBBBBBBBBB     BBBBBBBBBBBBBBB                                             ",
            "                                          BBBBBBBBBBBBB               BBBBBBBBBBBBB                                          ",
            "                                       BBBBBBBBBB                           BBBBBBBBBB                                       ",
            "                                     BBBBBBBBB                                 BBBBBBBBB                                     ",
            "                                   BBBBBBBB                                       BBBBBBBB                                   ",
            "                                 BBBBBBB                                             BBBBBBB                                 ",
            "                               BBBBBBB                                                 BBBBBBB                               ",
            "                              BBBBBB                                                     BBBBBB                              ",
            "                            BBBBBB                                                         BBBBBB                            ",
            "                           BBBBB                                                             BBBBB                           ",
            "                         BBBBBB                                                               BBBBBB                         ",
            "                        BBBBB                                                                   BBBBB                        ",
            "                       BBBBB                                                                     BBBBB                       ",
            "                     BBBBBB                                                                       BBBBBB                     ",
            "                    BBBBB                                                                           BBBBB                    ",
            "                   BBBBB                                                                             BBBBB                   ",
            "                  BBBBB                                                                               BBBBB                  ",
            "                 BBBBB                                                                                 BBBBB                 ",
            "                BBBBB                                                                                   BBBBB                ",
            "                BBBB                                                                                     BBBB                ",
            "               BBBB                                                                                       BBBB               ",
            "              BBBB                                                                                         BBBB              ",
            "             BBBB                                                                                           BBBB             ",
            "             BBBB                                                                                           BBBB             ",
            "            BBBB                                                                                             BBBB            ",
            "           BBBB                                                                                               BBBB           ",
            "           BBB                                                                                                 BBB           ",
            "          BBBB                                                                                                 BBBB          ",
            "         BBBB                                                                                                   BBBB         ",
            "         BBB                                                                                                     BBB         ",
            "        BBBB                                                                                                     BBBB        ",
            "        BBB                                                                                                       BBB        ",
            "       BBBB                                                                                                       BBBB       ",
            "       BBB                                                                                                         BBB       ",
            "      BBBB                                                                                                         BBBB      ",
            "      BBB                                                                                                           BBB      ",
            "     BBBB                                                                                                           BBBB     ",
            "     BBB                                                                                                             BBB     ",
            "     BBB                                                                                                             BBB     ",
            "    BBBB                                                                                                             BBBB    ",
            "    BBB                                                                                                               BBB    ",
            "    BBB                                                                                                               BBB    ",
            "   BBBB                                                                                                               BBBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBBB                                                                                                               BBBB   ",
            "    BBB                                                                                                               BBB    ",
            "    BBB                                                                                                               BBB    ",
            "    BBBB                                                                                                             BBBB    ",
            "     BBB                                                                                                             BBB     ",
            "     BBB                                                                                                             BBB     ",
            "     BBBB                                                                                                           BBBB     ",
            "      BBB                                                                                                           BBB      ",
            "      BBBB                                                                                                         BBBB      ",
            "       BBB                                                                                                         BBB       ",
            "       BBBB                                                                                                       BBBB       ",
            "        BBB                                                                                                       BBB        ",
            "        BBBB                                                                                                     BBBB        ",
            "         BBB                                                                                                     BBB         ",
            "         BBBB                                                                                                   BBBB         ",
            "          BBBB                                                                                                 BBBB          ",
            "           BBB                                                                                                 BBB           ",
            "           BBBB                                                                                               BBBB           ",
            "            BBBB                                                                                             BBBB            ",
            "             BBBB                                                                                           BBBB             ",
            "             BBBB                                                                                           BBBB             ",
            "              BBBB                                                                                         BBBB              ",
            "               BBBB                                                                                       BBBB               ",
            "                BBBB                                                                                     BBBB                ",
            "                BBBBB                                                                                   BBBBB                ",
            "                 BBBBB                                                                                 BBBBB                 ",
            "                  BBBBB                                                                               BBBBB                  ",
            "                   BBBBB                                                                             BBBBB                   ",
            "                    BBBBB                                                                           BBBBB                    ",
            "                     BBBBBB                                                                       BBBBBB                     ",
            "                       BBBBB                                                                     BBBBB                       ",
            "                        BBBBB                                                                   BBBBB                        ",
            "                         BBBBBB                                                               BBBBBB                         ",
            "                           BBBBB                                                             BBBBB                           ",
            "                            BBBBBB                                                         BBBBBB                            ",
            "                              BBBBBB                                                     BBBBBB                              ",
            "                               BBBBBBB                                                 BBBBBBB                               ",
            "                                 BBBBBBB                                             BBBBBBB                                 ",
            "                                   BBBBBBBB                                       BBBBBBBB                                   ",
            "                                     BBBBBBBBB                                 BBBBBBBBB                                     ",
            "                                       BBBBBBBBBB                           BBBBBBBBBB                                       ",
            "                                          BBBBBBBBBBBBB               BBBBBBBBBBBBB                                          ",
            "                                             BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                             ",
            "                                                 BBBBBBBBBBBBBBBBBBBBBBBBBBB                                                 ",
            "                                                       BBBBBBBBBBBBBBB                                                       ",
            "                                                                                                                             "
        },
        {
            "                                                       BBBBB     BBBBB                                                       ",
            "                                                 BBBBBBWWWWW     WWWWWBBBBBB                                                 ",
            "                                             BBBBWWWWWWWWWWW     WWWWWWWWWWWBBBB                                             ",
            "                                          BBBWWWWWWWWWWWWWWW     WWWWWWWWWWWWWWWBBB                                          ",
            "                                       BBBWWWWWWWWWWWWWBBBBB     BBBBBWWWWWWWWWWWWWBBB                                       ",
            "                                     BBWWWWWWWWWWBBBBBB               BBBBBBWWWWWWWWWWBB                                     ",
            "                                   BBWWWWWWWWWBBB                           BBBWWWWWWWWWBB                                   ",
            "                                 BBWWWWWWWWBBB                                 BBBWWWWWWWWBB                                 ",
            "                               BBWWWWWWWBBB                                       BBBWWWWWWWBB                               ",
            "                              BWWWWWWWBB                                             BBWWWWWWWB                              ",
            "                            BBWWWWWWBB                                                 BBWWWWWWBB                            ",
            "                           BWWWWWWBB                                                     BBWWWWWWB                           ",
            "                         BBWWWWWBB                                                         BBWWWWWBB                         ",
            "                        BWWWWWWB                                                             BWWWWWWB                        ",
            "                       BWWWWWBB                                                               BBWWWWWB                       ",
            "                     BBWWWWWB                                                                   BWWWWWBB                     ",
            "                    BWWWWWWB                                                                     BWWWWWWB                    ",
            "                   BWWWWWBB                                                                       BBWWWWWB                   ",
            "                  BWWWWWB                                                                           BWWWWWB                  ",
            "                 BWWWWWB                                                                             BWWWWWB                 ",
            "                BWWWWWB                                                                               BWWWWWB                ",
            "               BWWWWWB                                                                                 BWWWWWB               ",
            "               BWWWWB                                                                                   BWWWWB               ",
            "              BWWWWB                                                                                     BWWWWB              ",
            "             BWWWWB                                                                                       BWWWWB             ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "           BWWWWB                                                                                           BWWWWB           ",
            "          BWWWWB                                                                                             BWWWWB          ",
            "          BWWWB                                                                                               BWWWB          ",
            "         BWWWWB                                                                                               BWWWWB         ",
            "        BWWWWB                                                                                                 BWWWWB        ",
            "        BWWWB                                                                                                   BWWWB        ",
            "       BWWWWB                                                                                                   BWWWWB       ",
            "       BWWWB                                                                                                     BWWWB       ",
            "      BWWWWB                                                                                                     BWWWWB      ",
            "      BWWWB                                                                                                       BWWWB      ",
            "     BWWWWB                                                                                                       BWWWWB     ",
            "     BWWWB                                                                                                         BWWWB     ",
            "    BWWWWB                                                                                                         BWWWWB    ",
            "    BWWWB                                                                                                           BWWWB    ",
            "    BWWWB                                                                                                           BWWWB    ",
            "   BWWWWB                                                                                                           BWWWWB   ",
            "   BWWWB                                                                                                             BWWWB   ",
            "   BWWWB                                                                                                             BWWWB   ",
            "  BWWWWB                                                                                                             BWWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWWB                                                                                                             BWWWWB  ",
            "   BWWWB                                                                                                             BWWWB   ",
            "   BWWWB                                                                                                             BWWWB   ",
            "   BWWWWB                                                                                                           BWWWWB   ",
            "    BWWWB                                                                                                           BWWWB    ",
            "    BWWWB                                                                                                           BWWWB    ",
            "    BWWWWB                                                                                                         BWWWWB    ",
            "     BWWWB                                                                                                         BWWWB     ",
            "     BWWWWB                                                                                                       BWWWWB     ",
            "      BWWWB                                                                                                       BWWWB      ",
            "      BWWWWB                                                                                                     BWWWWB      ",
            "       BWWWB                                                                                                     BWWWB       ",
            "       BWWWWB                                                                                                   BWWWWB       ",
            "        BWWWB                                                                                                   BWWWB        ",
            "        BWWWWB                                                                                                 BWWWWB        ",
            "         BWWWWB                                                                                               BWWWWB         ",
            "          BWWWB                                                                                               BWWWB          ",
            "          BWWWWB                                                                                             BWWWWB          ",
            "           BWWWWB                                                                                           BWWWWB           ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "             BWWWWB                                                                                       BWWWWB             ",
            "              BWWWWB                                                                                     BWWWWB              ",
            "               BWWWWB                                                                                   BWWWWB               ",
            "               BWWWWWB                                                                                 BWWWWWB               ",
            "                BWWWWWB                                                                               BWWWWWB                ",
            "                 BWWWWWB                                                                             BWWWWWB                 ",
            "                  BWWWWWB                                                                           BWWWWWB                  ",
            "                   BWWWWWBB                                                                       BBWWWWWB                   ",
            "                    BWWWWWWB                                                                     BWWWWWWB                    ",
            "                     BBWWWWWB                                                                   BWWWWWBB                     ",
            "                       BWWWWWBB                                                               BBWWWWWB                       ",
            "                        BWWWWWWB                                                             BWWWWWWB                        ",
            "                         BBWWWWWBB                                                         BBWWWWWBB                         ",
            "                           BWWWWWWBB                                                     BBWWWWWWB                           ",
            "                            BBWWWWWWBB                                                 BBWWWWWWBB                            ",
            "                              BWWWWWWWBB                                             BBWWWWWWWB                              ",
            "                               BBWWWWWWWBBB                                       BBBWWWWWWWBB                               ",
            "                                 BBWWWWWWWWBBB                                 BBBWWWWWWWWBB                                 ",
            "                                   BBWWWWWWWWWBBB                           BBBWWWWWWWWWBB                                   ",
            "                                     BBWWWWWWWWWWBBBBBB               BBBBBBWWWWWWWWWWBB                                     ",
            "                                       BBBWWWWWWWWWWWWWBBBBBBBBBBBBBBBWWWWWWWWWWWWWBBB                                       ",
            "                                          BBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                          ",
            "                                             BBBBWWWWWWWWWWWWWWWWWWWWWWWWWWWBBBB                                             ",
            "                                                 BBBBBBWWWWWWWWWWWWWWWBBBBBB                                                 ",
            "                                                       BBBBBBBBBBBBBBB                                                       "
        },
        {
            "                                                       BBBBB     BBBBB                                                       ",
            "                                                 BBBBBBWWWWW  ~  WWWWWBBBBBB                                                 ",
            "                                             BBBBWWWWWWXXXXXXXXXXXXXXXWWWWWWBBBB                                             ",
            "                                          BBBWWWWXXXXXXWWWWW     WWWWWXXXXXXWWWWBBB                                          ",
            "                                       BBBWWWXXXXWWWWWWBBBBB     BBBBBWWWWWWXXXXWWWBBB                                       ",
            "                                     BBWWWXXXWWWWBBBBBB               BBBBBBWWWWXXXWWWBB                                     ",
            "                                   BBWWWXXWWWWBBB                           BBBWWWWXXWWWBB                                   ",
            "                                 BBWWXXXWWWBBB                                 BBBWWWXXXWWBB                                 ",
            "                               BBWWXXWWWBBB                                       BBBWWWXXWWBB                               ",
            "                              BWWXXWWWBB                                             BBWWWXXWWB                              ",
            "                            BBWWXWWWBB                                                 BBWWWXWWBB                            ",
            "                           BWWXXWWBB                                                     BBWWXXWWB                           ",
            "                         BBWWXWWBB                                                         BBWWXWWBB                         ",
            "                        BWWXXWWB                                                             BWWXXWWB                        ",
            "                       BWWXWWBB                                                               BBWWXWWB                       ",
            "                     BBWWXWWB                                                                   BWWXWWBB                     ",
            "                    BWWXXWWB                                                                     BWWXXWWB                    ",
            "                   BWWXWWBB                                                                       BBWWXWWB                   ",
            "                  BWWXWWB                                                                           BWWXWWB                  ",
            "                 BWWXWWB                                                                             BWWXWWB                 ",
            "                BWWXWWB                                                                               BWWXWWB                ",
            "               BWWXWWB                                                                                 BWWXWWB               ",
            "               BWXWWB                                                                                   BWWXWB               ",
            "              BWXWWB                                                                                     BWWXWB              ",
            "             BWWXWB                                                                                       BWXWWB             ",
            "            BWWXWB                                                                                         BWXWWB            ",
            "            BWXWWB                                                                                         BWWXWB            ",
            "           BWXWWB                                                                                           BWWXWB           ",
            "          BWWXWB                                                                                             BWXWWB          ",
            "          BWXWB                                                                                               BWXWB          ",
            "         BWXWWB                                                                                               BWWXWB         ",
            "        BWWXWB                                                                                                 BWXWWB        ",
            "        BWXWB                                                                                                   BWXWB        ",
            "       BWXWWB                                                                                                   BWWXWB       ",
            "       BWXWB                                                                                                     BWXWB       ",
            "      BWXWWB                                                                                                     BWWXWB      ",
            "      BWXWB                                                                                                       BWXWB      ",
            "     BWXWWB                                                                                                       BWWXWB     ",
            "     BWXWB                                                                                                         BWXWB     ",
            "    BWWXWB                                                                                                         BWXWWB    ",
            "    BWXWB                                                                                                           BWXWB    ",
            "    BWXWB                                                                                                           BWXWB    ",
            "   BWXWWB                                                                                                           BWWXWB   ",
            "   BWXWB                                                                                                             BWXWB   ",
            "   BWXWB                                                                                                             BWXWB   ",
            "  BWXWWB                                                                                                             BWWXWB  ",
            "  BWXWB                                                                                                               BWXWB  ",
            "  BWXWB                                                                                                               BWXWB  ",
            "  BWXWB                                                                                                               BWXWB  ",
            " BWXWB                                                                                                                 BWXWB ",
            " BWXWB                                                                                                                 BWXWB ",
            " BWXWB                                                                                                                 BWXWB ",
            " BWXWB                                                                                                                 BWXWB ",
            " BWXWB                                                                                                                 BWXWB ",
            " BWXWB                                                                                                                 BWXWB ",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            "BWXWB                                                                                                                   BWXWB",
            " BWXWB                                                                                                                 BWXWB ",
            " BWXWB                                                                                                                 BWXWB ",
            " BWXWB                                                                                                                 BWXWB ",
            " BWXWB                                                                                                                 BWXWB ",
            " BWXWB                                                                                                                 BWXWB ",
            " BWXWB                                                                                                                 BWXWB ",
            "  BWXWB                                                                                                               BWXWB  ",
            "  BWXWB                                                                                                               BWXWB  ",
            "  BWXWB                                                                                                               BWXWB  ",
            "  BWXWWB                                                                                                             BWWXWB  ",
            "   BWXWB                                                                                                             BWXWB   ",
            "   BWXWB                                                                                                             BWXWB   ",
            "   BWXWWB                                                                                                           BWWXWB   ",
            "    BWXWB                                                                                                           BWXWB    ",
            "    BWXWB                                                                                                           BWXWB    ",
            "    BWWXWB                                                                                                         BWXWWB    ",
            "     BWXWB                                                                                                         BWXWB     ",
            "     BWXWWB                                                                                                       BWWXWB     ",
            "      BWXWB                                                                                                       BWXWB      ",
            "      BWXWWB                                                                                                     BWWXWB      ",
            "       BWXWB                                                                                                     BWXWB       ",
            "       BWXWWB                                                                                                   BWWXWB       ",
            "        BWXWB                                                                                                   BWXWB        ",
            "        BWWXWB                                                                                                 BWXWWB        ",
            "         BWXWWB                                                                                               BWWXWB         ",
            "          BWXWB                                                                                               BWXWB          ",
            "          BWWXWB                                                                                             BWXWWB          ",
            "           BWXWWB                                                                                           BWWXWB           ",
            "            BWXWWB                                                                                         BWWXWB            ",
            "            BWWXWB                                                                                         BWXWWB            ",
            "             BWWXWB                                                                                       BWXWWB             ",
            "              BWXWWB                                                                                     BWWXWB              ",
            "               BWXWWB                                                                                   BWWXWB               ",
            "               BWWXWWB                                                                                 BWWXWWB               ",
            "                BWWXWWB                                                                               BWWXWWB                ",
            "                 BWWXWWB                                                                             BWWXWWB                 ",
            "                  BWWXWWB                                                                           BWWXWWB                  ",
            "                   BWWXWWBB                                                                       BBWWXWWB                   ",
            "                    BWWXXWWB                                                                     BWWXXWWB                    ",
            "                     BBWWXWWB                                                                   BWWXWWBB                     ",
            "                       BWWXWWBB                                                               BBWWXWWB                       ",
            "                        BWWXXWWB                                                             BWWXXWWB                        ",
            "                         BBWWXWWBB                                                         BBWWXWWBB                         ",
            "                           BWWXXWWBB                                                     BBWWXXWWB                           ",
            "                            BBWWXWWWBB                                                 BBWWWXWWBB                            ",
            "                              BWWXXWWWBB                                             BBWWWXXWWB                              ",
            "                               BBWWXXWWWBBB                                       BBBWWWXXWWBB                               ",
            "                                 BBWWXXXWWWBBB                                 BBBWWWXXXWWBB                                 ",
            "                                   BBWWWXXWWWWBBB                           BBBWWWWXXWWWBB                                   ",
            "                                     BBWWWXXXWWWWBBBBBB               BBBBBBWWWWXXXWWWBB                                     ",
            "                                       BBBWWWXXXXWWWWWWBBBBBBBBBBBBBBBWWWWWWXXXXWWWBBB                                       ",
            "                                          BBBWWWWXXXXXXWWWWWWWWWWWWWWWXXXXXXWWWWBBB                                          ",
            "                                             BBBBWWWWWWXXXXXXXXXXXXXXXWWWWWWBBBB                                             ",
            "                                                 BBBBBBWWWWWWWWWWWWWWWBBBBBB                                                 ",
            "                                                       BBBBBBBBBBBBBBB                                                       "
        },
        {
            "                                                       BBBBB     BBBBB                                                       ",
            "                                                 BBBBBBWWWWW     WWWWWBBBBBB                                                 ",
            "                                             BBBBWWWWWWWWWWW     WWWWWWWWWWWBBBB                                             ",
            "                                          BBBWWWWWWWWWWWWWWW     WWWWWWWWWWWWWWWBBB                                          ",
            "                                       BBBWWWWWWWWWWWWWBBBBB     BBBBBWWWWWWWWWWWWWBBB                                       ",
            "                                     BBWWWWWWWWWWBBBBBB               BBBBBBWWWWWWWWWWBB                                     ",
            "                                   BBWWWWWWWWWBBB                           BBBWWWWWWWWWBB                                   ",
            "                                 BBWWWWWWWWBBB                                 BBBWWWWWWWWBB                                 ",
            "                               BBWWWWWWWBBB                                       BBBWWWWWWWBB                               ",
            "                              BWWWWWWWBB                                             BBWWWWWWWB                              ",
            "                            BBWWWWWWBB                                                 BBWWWWWWBB                            ",
            "                           BWWWWWWBB                                                     BBWWWWWWB                           ",
            "                         BBWWWWWBB                                                         BBWWWWWBB                         ",
            "                        BWWWWWWB                                                             BWWWWWWB                        ",
            "                       BWWWWWBB                                                               BBWWWWWB                       ",
            "                     BBWWWWWB                                                                   BWWWWWBB                     ",
            "                    BWWWWWWB                                                                     BWWWWWWB                    ",
            "                   BWWWWWBB                                                                       BBWWWWWB                   ",
            "                  BWWWWWB                                                                           BWWWWWB                  ",
            "                 BWWWWWB                                                                             BWWWWWB                 ",
            "                BWWWWWB                                                                               BWWWWWB                ",
            "               BWWWWWB                                                                                 BWWWWWB               ",
            "               BWWWWB                                                                                   BWWWWB               ",
            "              BWWWWB                                                                                     BWWWWB              ",
            "             BWWWWB                                                                                       BWWWWB             ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "           BWWWWB                                                                                           BWWWWB           ",
            "          BWWWWB                                                                                             BWWWWB          ",
            "          BWWWB                                                                                               BWWWB          ",
            "         BWWWWB                                                                                               BWWWWB         ",
            "        BWWWWB                                                                                                 BWWWWB        ",
            "        BWWWB                                                                                                   BWWWB        ",
            "       BWWWWB                                                                                                   BWWWWB       ",
            "       BWWWB                                                                                                     BWWWB       ",
            "      BWWWWB                                                                                                     BWWWWB      ",
            "      BWWWB                                                                                                       BWWWB      ",
            "     BWWWWB                                                                                                       BWWWWB     ",
            "     BWWWB                                                                                                         BWWWB     ",
            "    BWWWWB                                                                                                         BWWWWB    ",
            "    BWWWB                                                                                                           BWWWB    ",
            "    BWWWB                                                                                                           BWWWB    ",
            "   BWWWWB                                                                                                           BWWWWB   ",
            "   BWWWB                                                                                                             BWWWB   ",
            "   BWWWB                                                                                                             BWWWB   ",
            "  BWWWWB                                                                                                             BWWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            "BWWWB                                                                                                                   BWWWB",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            " BWWWB                                                                                                                 BWWWB ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWB                                                                                                               BWWWB  ",
            "  BWWWWB                                                                                                             BWWWWB  ",
            "   BWWWB                                                                                                             BWWWB   ",
            "   BWWWB                                                                                                             BWWWB   ",
            "   BWWWWB                                                                                                           BWWWWB   ",
            "    BWWWB                                                                                                           BWWWB    ",
            "    BWWWB                                                                                                           BWWWB    ",
            "    BWWWWB                                                                                                         BWWWWB    ",
            "     BWWWB                                                                                                         BWWWB     ",
            "     BWWWWB                                                                                                       BWWWWB     ",
            "      BWWWB                                                                                                       BWWWB      ",
            "      BWWWWB                                                                                                     BWWWWB      ",
            "       BWWWB                                                                                                     BWWWB       ",
            "       BWWWWB                                                                                                   BWWWWB       ",
            "        BWWWB                                                                                                   BWWWB        ",
            "        BWWWWB                                                                                                 BWWWWB        ",
            "         BWWWWB                                                                                               BWWWWB         ",
            "          BWWWB                                                                                               BWWWB          ",
            "          BWWWWB                                                                                             BWWWWB          ",
            "           BWWWWB                                                                                           BWWWWB           ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "            BWWWWB                                                                                         BWWWWB            ",
            "             BWWWWB                                                                                       BWWWWB             ",
            "              BWWWWB                                                                                     BWWWWB              ",
            "               BWWWWB                                                                                   BWWWWB               ",
            "               BWWWWWB                                                                                 BWWWWWB               ",
            "                BWWWWWB                                                                               BWWWWWB                ",
            "                 BWWWWWB                                                                             BWWWWWB                 ",
            "                  BWWWWWB                                                                           BWWWWWB                  ",
            "                   BWWWWWBB                                                                       BBWWWWWB                   ",
            "                    BWWWWWWB                                                                     BWWWWWWB                    ",
            "                     BBWWWWWB                                                                   BWWWWWBB                     ",
            "                       BWWWWWBB                                                               BBWWWWWB                       ",
            "                        BWWWWWWB                                                             BWWWWWWB                        ",
            "                         BBWWWWWBB                                                         BBWWWWWBB                         ",
            "                           BWWWWWWBB                                                     BBWWWWWWB                           ",
            "                            BBWWWWWWBB                                                 BBWWWWWWBB                            ",
            "                              BWWWWWWWBB                                             BBWWWWWWWB                              ",
            "                               BBWWWWWWWBBB                                       BBBWWWWWWWBB                               ",
            "                                 BBWWWWWWWWBBB                                 BBBWWWWWWWWBB                                 ",
            "                                   BBWWWWWWWWWBBB                           BBBWWWWWWWWWBB                                   ",
            "                                     BBWWWWWWWWWWBBBBBB               BBBBBBWWWWWWWWWWBB                                     ",
            "                                       BBBWWWWWWWWWWWWWBBBBBBBBBBBBBBBWWWWWWWWWWWWWBBB                                       ",
            "                                          BBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBBB                                          ",
            "                                             BBBBWWWWWWWWWWWWWWWWWWWWWWWWWWWBBBB                                             ",
            "                                                 BBBBBBWWWWWWWWWWWWWWWBBBBBB                                                 ",
            "                                                       BBBBBBBBBBBBBBB                                                       "
        },
        {
            "                                                                                                                             ",
            "                                                       BBBBB     BBBBB                                                       ",
            "                                                 BBBBBBBBBBB     BBBBBBBBBBB                                                 ",
            "                                             BBBBBBBBBBBBBBB     BBBBBBBBBBBBBBB                                             ",
            "                                          BBBBBBBBBBBBB               BBBBBBBBBBBBB                                          ",
            "                                       BBBBBBBBBB                           BBBBBBBBBB                                       ",
            "                                     BBBBBBBBB                                 BBBBBBBBB                                     ",
            "                                   BBBBBBBB                                       BBBBBBBB                                   ",
            "                                 BBBBBBB                                             BBBBBBB                                 ",
            "                               BBBBBBB                                                 BBBBBBB                               ",
            "                              BBBBBB                                                     BBBBBB                              ",
            "                            BBBBBB                                                         BBBBBB                            ",
            "                           BBBBB                                                             BBBBB                           ",
            "                         BBBBBB                                                               BBBBBB                         ",
            "                        BBBBB                                                                   BBBBB                        ",
            "                       BBBBB                                                                     BBBBB                       ",
            "                     BBBBBB                                                                       BBBBBB                     ",
            "                    BBBBB                                                                           BBBBB                    ",
            "                   BBBBB                                                                             BBBBB                   ",
            "                  BBBBB                                                                               BBBBB                  ",
            "                 BBBBB                                                                                 BBBBB                 ",
            "                BBBBB                                                                                   BBBBB                ",
            "                BBBB                                                                                     BBBB                ",
            "               BBBB                                                                                       BBBB               ",
            "              BBBB                                                                                         BBBB              ",
            "             BBBB                                                                                           BBBB             ",
            "             BBBB                                                                                           BBBB             ",
            "            BBBB                                                                                             BBBB            ",
            "           BBBB                                                                                               BBBB           ",
            "           BBB                                                                                                 BBB           ",
            "          BBBB                                                                                                 BBBB          ",
            "         BBBB                                                                                                   BBBB         ",
            "         BBB                                                                                                     BBB         ",
            "        BBBB                                                                                                     BBBB        ",
            "        BBB                                                                                                       BBB        ",
            "       BBBB                                                                                                       BBBB       ",
            "       BBB                                                                                                         BBB       ",
            "      BBBB                                                                                                         BBBB      ",
            "      BBB                                                                                                           BBB      ",
            "     BBBB                                                                                                           BBBB     ",
            "     BBB                                                                                                             BBB     ",
            "     BBB                                                                                                             BBB     ",
            "    BBBB                                                                                                             BBBB    ",
            "    BBB                                                                                                               BBB    ",
            "    BBB                                                                                                               BBB    ",
            "   BBBB                                                                                                               BBBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            " BBB                                                                                                                     BBB ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "  BBB                                                                                                                   BBB  ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBB                                                                                                                 BBB   ",
            "   BBBB                                                                                                               BBBB   ",
            "    BBB                                                                                                               BBB    ",
            "    BBB                                                                                                               BBB    ",
            "    BBBB                                                                                                             BBBB    ",
            "     BBB                                                                                                             BBB     ",
            "     BBB                                                                                                             BBB     ",
            "     BBBB                                                                                                           BBBB     ",
            "      BBB                                                                                                           BBB      ",
            "      BBBB                                                                                                         BBBB      ",
            "       BBB                                                                                                         BBB       ",
            "       BBBB                                                                                                       BBBB       ",
            "        BBB                                                                                                       BBB        ",
            "        BBBB                                                                                                     BBBB        ",
            "         BBB                                                                                                     BBB         ",
            "         BBBB                                                                                                   BBBB         ",
            "          BBBB                                                                                                 BBBB          ",
            "           BBB                                                                                                 BBB           ",
            "           BBBB                                                                                               BBBB           ",
            "            BBBB                                                                                             BBBB            ",
            "             BBBB                                                                                           BBBB             ",
            "             BBBB                                                                                           BBBB             ",
            "              BBBB                                                                                         BBBB              ",
            "               BBBB                                                                                       BBBB               ",
            "                BBBB                                                                                     BBBB                ",
            "                BBBBB                                                                                   BBBBB                ",
            "                 BBBBB                                                                                 BBBBB                 ",
            "                  BBBBB                                                                               BBBBB                  ",
            "                   BBBBB                                                                             BBBBB                   ",
            "                    BBBBB                                                                           BBBBB                    ",
            "                     BBBBBB                                                                       BBBBBB                     ",
            "                       BBBBB                                                                     BBBBB                       ",
            "                        BBBBB                                                                   BBBBB                        ",
            "                         BBBBBB                                                               BBBBBB                         ",
            "                           BBBBB                                                             BBBBB                           ",
            "                            BBBBBB                                                         BBBBBB                            ",
            "                              BBBBBB                                                     BBBBBB                              ",
            "                               BBBBBBB                                                 BBBBBBB                               ",
            "                                 BBBBBBB                                             BBBBBBB                                 ",
            "                                   BBBBBBBB                                       BBBBBBBB                                   ",
            "                                     BBBBBBBBB                                 BBBBBBBBB                                     ",
            "                                       BBBBBBBBBB                           BBBBBBBBBB                                       ",
            "                                          BBBBBBBBBBBBB               BBBBBBBBBBBBB                                          ",
            "                                             BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                             ",
            "                                                 BBBBBBBBBBBBBBBBBBBBBBBBBBB                                                 ",
            "                                                       BBBBBBBBBBBBBBB                                                       ",
            "                                                                                                                             "
        }
    });
}
