package goodgenerator.util.cyclotron;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;

@SuppressWarnings("SpellCheckingInspection")
public abstract class CYCLOTRON_SHAPE_FILE_5 {
    public static final String[][] CYCLOTRON_SHAPE_5_IDENTITY = transpose(new String[][] {
        {
            "                                                                                     ",
            "                                    BBBB     BBBB                                    ",
            "                               BBBBBBBBB     BBBBBBBBB                               ",
            "                            BBBBBBBBBBBB     BBBBBBBBBBBB                            ",
            "                          BBBBBBBBBB             BBBBBBBBBB                          ",
            "                        BBBBBBBB                     BBBBBBBB                        ",
            "                      BBBBBBB                           BBBBBBB                      ",
            "                    BBBBBBB                               BBBBBBB                    ",
            "                   BBBBBB                                   BBBBBB                   ",
            "                 BBBBBB                                       BBBBBB                 ",
            "                BBBBB                                           BBBBB                ",
            "               BBBBB                                             BBBBB               ",
            "              BBBBB                                               BBBBB              ",
            "             BBBB                                                   BBBB             ",
            "            BBBB                                                     BBBB            ",
            "           BBBB                                                       BBBB           ",
            "          BBBB                                                         BBBB          ",
            "         BBBB                                                           BBBB         ",
            "         BBBB                                                           BBBB         ",
            "        BBBB                                                             BBBB        ",
            "       BBBB                                                               BBBB       ",
            "       BBB                                                                 BBB       ",
            "      BBBB                                                                 BBBB      ",
            "      BBB                                                                   BBB      ",
            "     BBBB                                                                   BBBB     ",
            "     BBB                                                                     BBB     ",
            "    BBBB                                                                     BBBB    ",
            "    BBB                                                                       BBB    ",
            "   BBBB                                                                       BBBB   ",
            "   BBB                                                                         BBB   ",
            "   BBB                                                                         BBB   ",
            "  BBBB                                                                         BBBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBBB                                                                         BBBB  ",
            "   BBB                                                                         BBB   ",
            "   BBB                                                                         BBB   ",
            "   BBBB                                                                       BBBB   ",
            "    BBB                                                                       BBB    ",
            "    BBBB                                                                     BBBB    ",
            "     BBB                                                                     BBB     ",
            "     BBBB                                                                   BBBB     ",
            "      BBB                                                                   BBB      ",
            "      BBBB                                                                 BBBB      ",
            "       BBB                                                                 BBB       ",
            "       BBBB                                                               BBBB       ",
            "        BBBB                                                             BBBB        ",
            "         BBBB                                                           BBBB         ",
            "         BBBB                                                           BBBB         ",
            "          BBBB                                                         BBBB          ",
            "           BBBB                                                       BBBB           ",
            "            BBBB                                                     BBBB            ",
            "             BBBB                                                   BBBB             ",
            "              BBBBB                                               BBBBB              ",
            "               BBBBB                                             BBBBB               ",
            "                BBBBB                                           BBBBB                ",
            "                 BBBBBB                                       BBBBBB                 ",
            "                   BBBBBB                                   BBBBBB                   ",
            "                    BBBBBBB                               BBBBBBB                    ",
            "                      BBBBBBB                           BBBBBBB                      ",
            "                        BBBBBBBB                     BBBBBBBB                        ",
            "                          BBBBBBBBBB             BBBBBBBBBB                          ",
            "                            BBBBBBBBBBBBBBBBBBBBBBBBBBBBB                            ",
            "                               BBBBBBBBBBBBBBBBBBBBBBB                               ",
            "                                    BBBBBBBBBBBBB                                    ",
            "                                                                                     "
        },
        {
            "                                    BBBB     BBBB                                    ",
            "                               BBBBBWWWW     WWWWBBBBB                               ",
            "                            BBBWWWWWWWWW     WWWWWWWWWBBB                            ",
            "                          BBWWWWWWWWWWWW     WWWWWWWWWWWWBB                          ",
            "                        BBWWWWWWWWWWBBBB     BBBBWWWWWWWWWWBB                        ",
            "                      BBWWWWWWWWBBBB             BBBBWWWWWWWWBB                      ",
            "                    BBWWWWWWWBBB                     BBBWWWWWWWBB                    ",
            "                   BWWWWWWWBB                           BBWWWWWWWB                   ",
            "                 BBWWWWWWBB                               BBWWWWWWBB                 ",
            "                BWWWWWWBB                                   BBWWWWWWB                ",
            "               BWWWWWBB                                       BBWWWWWB               ",
            "              BWWWWWB                                           BWWWWWB              ",
            "             BWWWWWB                                             BWWWWWB             ",
            "            BWWWWBB                                               BBWWWWB            ",
            "           BWWWWB                                                   BWWWWB           ",
            "          BWWWWB                                                     BWWWWB          ",
            "         BWWWWB                                                       BWWWWB         ",
            "        BWWWWB                                                         BWWWWB        ",
            "        BWWWWB                                                         BWWWWB        ",
            "       BWWWWB                                                           BWWWWB       ",
            "      BWWWWB                                                             BWWWWB      ",
            "      BWWWB                                                               BWWWB      ",
            "     BWWWWB                                                               BWWWWB     ",
            "     BWWWB                                                                 BWWWB     ",
            "    BWWWWB                                                                 BWWWWB    ",
            "    BWWWB                                                                   BWWWB    ",
            "   BWWWWB                                                                   BWWWWB   ",
            "   BWWWB                                                                     BWWWB   ",
            "  BWWWWB                                                                     BWWWWB  ",
            "  BWWWB                                                                       BWWWB  ",
            "  BWWWB                                                                       BWWWB  ",
            " BWWWWB                                                                       BWWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWWB                                                                       BWWWWB ",
            "  BWWWB                                                                       BWWWB  ",
            "  BWWWB                                                                       BWWWB  ",
            "  BWWWWB                                                                     BWWWWB  ",
            "   BWWWB                                                                     BWWWB   ",
            "   BWWWWB                                                                   BWWWWB   ",
            "    BWWWB                                                                   BWWWB    ",
            "    BWWWWB                                                                 BWWWWB    ",
            "     BWWWB                                                                 BWWWB     ",
            "     BWWWWB                                                               BWWWWB     ",
            "      BWWWB                                                               BWWWB      ",
            "      BWWWWB                                                             BWWWWB      ",
            "       BWWWWB                                                           BWWWWB       ",
            "        BWWWWB                                                         BWWWWB        ",
            "        BWWWWB                                                         BWWWWB        ",
            "         BWWWWB                                                       BWWWWB         ",
            "          BWWWWB                                                     BWWWWB          ",
            "           BWWWWB                                                   BWWWWB           ",
            "            BWWWWBB                                               BBWWWWB            ",
            "             BWWWWWB                                             BWWWWWB             ",
            "              BWWWWWB                                           BWWWWWB              ",
            "               BWWWWWBB                                       BBWWWWWB               ",
            "                BWWWWWWBB                                   BBWWWWWWB                ",
            "                 BBWWWWWWBB                               BBWWWWWWBB                 ",
            "                   BWWWWWWWBB                           BBWWWWWWWB                   ",
            "                    BBWWWWWWWBBB                     BBBWWWWWWWBB                    ",
            "                      BBWWWWWWWWBBBB             BBBBWWWWWWWWBB                      ",
            "                        BBWWWWWWWWWWBBBBBBBBBBBBBWWWWWWWWWWBB                        ",
            "                          BBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBB                          ",
            "                            BBBWWWWWWWWWWWWWWWWWWWWWWWBBB                            ",
            "                               BBBBBWWWWWWWWWWWWWBBBBB                               ",
            "                                    BBBBBBBBBBBBB                                    "
        },
        {
            "                                    BBBB     BBBB                                    ",
            "                               BBBBBWWWW  ~  WWWWBBBBB                               ",
            "                            BBBWWWWWXXXXXXXXXXXXXWWWWWBBB                            ",
            "                          BBWWWWXXXXWWWW     WWWWXXXXWWWWBB                          ",
            "                        BBWWWXXXWWWWBBBB     BBBBWWWWXXXWWWBB                        ",
            "                      BBWWXXXWWWBBBB             BBBBWWWXXXWWBB                      ",
            "                    BBWWXXWWWBBB                     BBBWWWXXWWBB                    ",
            "                   BWWXXWWWBB                           BBWWWXXWWB                   ",
            "                 BBWWXWWWBB                               BBWWWXWWBB                 ",
            "                BWWXXWWBB                                   BBWWXXWWB                ",
            "               BWWXWWBB                                       BBWWXWWB               ",
            "              BWWXWWB                                           BWWXWWB              ",
            "             BWXXWWB                                             BWWXXWB             ",
            "            BWXWWBB                                               BBWWXWB            ",
            "           BWXWWB                                                   BWWXWB           ",
            "          BWXWWB                                                     BWWXWB          ",
            "         BWWXWB                                                       BWXWWB         ",
            "        BWWXWB                                                         BWXWWB        ",
            "        BWXWWB                                                         BWWXWB        ",
            "       BWXWWB                                                           BWWXWB       ",
            "      BWWXWB                                                             BWXWWB      ",
            "      BWXWB                                                               BWXWB      ",
            "     BWXWWB                                                               BWWXWB     ",
            "     BWXWB                                                                 BWXWB     ",
            "    BWXWWB                                                                 BWWXWB    ",
            "    BWXWB                                                                   BWXWB    ",
            "   BWXWWB                                                                   BWWXWB   ",
            "   BWXWB                                                                     BWXWB   ",
            "  BWWXWB                                                                     BWXWWB  ",
            "  BWXWB                                                                       BWXWB  ",
            "  BWXWB                                                                       BWXWB  ",
            " BWWXWB                                                                       BWXWWB ",
            " BWXWB                                                                         BWXWB ",
            " BWXWB                                                                         BWXWB ",
            " BWXWB                                                                         BWXWB ",
            " BWXWB                                                                         BWXWB ",
            "BWXWB                                                                           BWXWB",
            "BWXWB                                                                           BWXWB",
            "BWXWB                                                                           BWXWB",
            "BWXWB                                                                           BWXWB",
            "BWXWB                                                                           BWXWB",
            "BWXWB                                                                           BWXWB",
            "BWXWB                                                                           BWXWB",
            "BWXWB                                                                           BWXWB",
            "BWXWB                                                                           BWXWB",
            "BWXWB                                                                           BWXWB",
            "BWXWB                                                                           BWXWB",
            "BWXWB                                                                           BWXWB",
            "BWXWB                                                                           BWXWB",
            " BWXWB                                                                         BWXWB ",
            " BWXWB                                                                         BWXWB ",
            " BWXWB                                                                         BWXWB ",
            " BWXWB                                                                         BWXWB ",
            " BWWXWB                                                                       BWXWWB ",
            "  BWXWB                                                                       BWXWB  ",
            "  BWXWB                                                                       BWXWB  ",
            "  BWWXWB                                                                     BWXWWB  ",
            "   BWXWB                                                                     BWXWB   ",
            "   BWXWWB                                                                   BWWXWB   ",
            "    BWXWB                                                                   BWXWB    ",
            "    BWXWWB                                                                 BWWXWB    ",
            "     BWXWB                                                                 BWXWB     ",
            "     BWXWWB                                                               BWWXWB     ",
            "      BWXWB                                                               BWXWB      ",
            "      BWWXWB                                                             BWXWWB      ",
            "       BWXWWB                                                           BWWXWB       ",
            "        BWXWWB                                                         BWWXWB        ",
            "        BWWXWB                                                         BWXWWB        ",
            "         BWWXWB                                                       BWXWWB         ",
            "          BWXWWB                                                     BWWXWB          ",
            "           BWXWWB                                                   BWWXWB           ",
            "            BWXWWBB                                               BBWWXWB            ",
            "             BWXXWWB                                             BWWXXWB             ",
            "              BWWXWWB                                           BWWXWWB              ",
            "               BWWXWWBB                                       BBWWXWWB               ",
            "                BWWXXWWBB                                   BBWWXXWWB                ",
            "                 BBWWXWWWBB                               BBWWWXWWBB                 ",
            "                   BWWXXWWWBB                           BBWWWXXWWB                   ",
            "                    BBWWXXWWWBBB                     BBBWWWXXWWBB                    ",
            "                      BBWWXXXWWWBBBB             BBBBWWWXXXWWBB                      ",
            "                        BBWWWXXXWWWWBBBBBBBBBBBBBWWWWXXXWWWBB                        ",
            "                          BBWWWWXXXXWWWWWWWWWWWWWXXXXWWWWBB                          ",
            "                            BBBWWWWWXXXXXXXXXXXXXWWWWWBBB                            ",
            "                               BBBBBWWWWWWWWWWWWWBBBBB                               ",
            "                                    BBBBBBBBBBBBB                                    "
        },
        {
            "                                    BBBB     BBBB                                    ",
            "                               BBBBBWWWW     WWWWBBBBB                               ",
            "                            BBBWWWWWWWWW     WWWWWWWWWBBB                            ",
            "                          BBWWWWWWWWWWWW     WWWWWWWWWWWWBB                          ",
            "                        BBWWWWWWWWWWBBBB     BBBBWWWWWWWWWWBB                        ",
            "                      BBWWWWWWWWBBBB             BBBBWWWWWWWWBB                      ",
            "                    BBWWWWWWWBBB                     BBBWWWWWWWBB                    ",
            "                   BWWWWWWWBB                           BBWWWWWWWB                   ",
            "                 BBWWWWWWBB                               BBWWWWWWBB                 ",
            "                BWWWWWWBB                                   BBWWWWWWB                ",
            "               BWWWWWBB                                       BBWWWWWB               ",
            "              BWWWWWB                                           BWWWWWB              ",
            "             BWWWWWB                                             BWWWWWB             ",
            "            BWWWWBB                                               BBWWWWB            ",
            "           BWWWWB                                                   BWWWWB           ",
            "          BWWWWB                                                     BWWWWB          ",
            "         BWWWWB                                                       BWWWWB         ",
            "        BWWWWB                                                         BWWWWB        ",
            "        BWWWWB                                                         BWWWWB        ",
            "       BWWWWB                                                           BWWWWB       ",
            "      BWWWWB                                                             BWWWWB      ",
            "      BWWWB                                                               BWWWB      ",
            "     BWWWWB                                                               BWWWWB     ",
            "     BWWWB                                                                 BWWWB     ",
            "    BWWWWB                                                                 BWWWWB    ",
            "    BWWWB                                                                   BWWWB    ",
            "   BWWWWB                                                                   BWWWWB   ",
            "   BWWWB                                                                     BWWWB   ",
            "  BWWWWB                                                                     BWWWWB  ",
            "  BWWWB                                                                       BWWWB  ",
            "  BWWWB                                                                       BWWWB  ",
            " BWWWWB                                                                       BWWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            "BWWWB                                                                           BWWWB",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWB                                                                         BWWWB ",
            " BWWWWB                                                                       BWWWWB ",
            "  BWWWB                                                                       BWWWB  ",
            "  BWWWB                                                                       BWWWB  ",
            "  BWWWWB                                                                     BWWWWB  ",
            "   BWWWB                                                                     BWWWB   ",
            "   BWWWWB                                                                   BWWWWB   ",
            "    BWWWB                                                                   BWWWB    ",
            "    BWWWWB                                                                 BWWWWB    ",
            "     BWWWB                                                                 BWWWB     ",
            "     BWWWWB                                                               BWWWWB     ",
            "      BWWWB                                                               BWWWB      ",
            "      BWWWWB                                                             BWWWWB      ",
            "       BWWWWB                                                           BWWWWB       ",
            "        BWWWWB                                                         BWWWWB        ",
            "        BWWWWB                                                         BWWWWB        ",
            "         BWWWWB                                                       BWWWWB         ",
            "          BWWWWB                                                     BWWWWB          ",
            "           BWWWWB                                                   BWWWWB           ",
            "            BWWWWBB                                               BBWWWWB            ",
            "             BWWWWWB                                             BWWWWWB             ",
            "              BWWWWWB                                           BWWWWWB              ",
            "               BWWWWWBB                                       BBWWWWWB               ",
            "                BWWWWWWBB                                   BBWWWWWWB                ",
            "                 BBWWWWWWBB                               BBWWWWWWBB                 ",
            "                   BWWWWWWWBB                           BBWWWWWWWB                   ",
            "                    BBWWWWWWWBBB                     BBBWWWWWWWBB                    ",
            "                      BBWWWWWWWWBBBB             BBBBWWWWWWWWBB                      ",
            "                        BBWWWWWWWWWWBBBBBBBBBBBBBWWWWWWWWWWBB                        ",
            "                          BBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBB                          ",
            "                            BBBWWWWWWWWWWWWWWWWWWWWWWWBBB                            ",
            "                               BBBBBWWWWWWWWWWWWWBBBBB                               ",
            "                                    BBBBBBBBBBBBB                                    "
        },
        {
            "                                                                                     ",
            "                                    BBBB     BBBB                                    ",
            "                               BBBBBBBBB     BBBBBBBBB                               ",
            "                            BBBBBBBBBBBB     BBBBBBBBBBBB                            ",
            "                          BBBBBBBBBB             BBBBBBBBBB                          ",
            "                        BBBBBBBB                     BBBBBBBB                        ",
            "                      BBBBBBB                           BBBBBBB                      ",
            "                    BBBBBBB                               BBBBBBB                    ",
            "                   BBBBBB                                   BBBBBB                   ",
            "                 BBBBBB                                       BBBBBB                 ",
            "                BBBBB                                           BBBBB                ",
            "               BBBBB                                             BBBBB               ",
            "              BBBBB                                               BBBBB              ",
            "             BBBB                                                   BBBB             ",
            "            BBBB                                                     BBBB            ",
            "           BBBB                                                       BBBB           ",
            "          BBBB                                                         BBBB          ",
            "         BBBB                                                           BBBB         ",
            "         BBBB                                                           BBBB         ",
            "        BBBB                                                             BBBB        ",
            "       BBBB                                                               BBBB       ",
            "       BBB                                                                 BBB       ",
            "      BBBB                                                                 BBBB      ",
            "      BBB                                                                   BBB      ",
            "     BBBB                                                                   BBBB     ",
            "     BBB                                                                     BBB     ",
            "    BBBB                                                                     BBBB    ",
            "    BBB                                                                       BBB    ",
            "   BBBB                                                                       BBBB   ",
            "   BBB                                                                         BBB   ",
            "   BBB                                                                         BBB   ",
            "  BBBB                                                                         BBBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            " BBB                                                                             BBB ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBB                                                                           BBB  ",
            "  BBBB                                                                         BBBB  ",
            "   BBB                                                                         BBB   ",
            "   BBB                                                                         BBB   ",
            "   BBBB                                                                       BBBB   ",
            "    BBB                                                                       BBB    ",
            "    BBBB                                                                     BBBB    ",
            "     BBB                                                                     BBB     ",
            "     BBBB                                                                   BBBB     ",
            "      BBB                                                                   BBB      ",
            "      BBBB                                                                 BBBB      ",
            "       BBB                                                                 BBB       ",
            "       BBBB                                                               BBBB       ",
            "        BBBB                                                             BBBB        ",
            "         BBBB                                                           BBBB         ",
            "         BBBB                                                           BBBB         ",
            "          BBBB                                                         BBBB          ",
            "           BBBB                                                       BBBB           ",
            "            BBBB                                                     BBBB            ",
            "             BBBB                                                   BBBB             ",
            "              BBBBB                                               BBBBB              ",
            "               BBBBB                                             BBBBB               ",
            "                BBBBB                                           BBBBB                ",
            "                 BBBBBB                                       BBBBBB                 ",
            "                   BBBBBB                                   BBBBBB                   ",
            "                    BBBBBBB                               BBBBBBB                    ",
            "                      BBBBBBB                           BBBBBBB                      ",
            "                        BBBBBBBB                     BBBBBBBB                        ",
            "                          BBBBBBBBBB             BBBBBBBBBB                          ",
            "                            BBBBBBBBBBBBBBBBBBBBBBBBBBBBB                            ",
            "                               BBBBBBBBBBBBBBBBBBBBBBB                               ",
            "                                    BBBBBBBBBBBBB                                    ",
            "                                                                                     "
        }
    });
}
